// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"gigaboo.io/lem/internal/ent/achievement"
	"gigaboo.io/lem/internal/ent/app"
	"gigaboo.io/lem/internal/ent/user"
)

// Achievement is the model entity for the Achievement schema.
type Achievement struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// AchievementID holds the value of the "achievement_id" field.
	AchievementID string `json:"achievement_id,omitempty"`
	// EarnedAt holds the value of the "earned_at" field.
	EarnedAt time.Time `json:"earned_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AchievementQuery when eager-loading is set.
	Edges             AchievementEdges `json:"edges"`
	app_achievements  *int
	user_achievements *int
	selectValues      sql.SelectValues
}

// AchievementEdges holds the relations/edges for other nodes in the graph.
type AchievementEdges struct {
	// App holds the value of the app edge.
	App *App `json:"app,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AppOrErr returns the App value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AchievementEdges) AppOrErr() (*App, error) {
	if e.App != nil {
		return e.App, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: app.Label}
	}
	return nil, &NotLoadedError{edge: "app"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AchievementEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Achievement) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case achievement.FieldID:
			values[i] = new(sql.NullInt64)
		case achievement.FieldAchievementID:
			values[i] = new(sql.NullString)
		case achievement.FieldEarnedAt:
			values[i] = new(sql.NullTime)
		case achievement.ForeignKeys[0]: // app_achievements
			values[i] = new(sql.NullInt64)
		case achievement.ForeignKeys[1]: // user_achievements
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Achievement fields.
func (_m *Achievement) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case achievement.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case achievement.FieldAchievementID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field achievement_id", values[i])
			} else if value.Valid {
				_m.AchievementID = value.String
			}
		case achievement.FieldEarnedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field earned_at", values[i])
			} else if value.Valid {
				_m.EarnedAt = value.Time
			}
		case achievement.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field app_achievements", value)
			} else if value.Valid {
				_m.app_achievements = new(int)
				*_m.app_achievements = int(value.Int64)
			}
		case achievement.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_achievements", value)
			} else if value.Valid {
				_m.user_achievements = new(int)
				*_m.user_achievements = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Achievement.
// This includes values selected through modifiers, order, etc.
func (_m *Achievement) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryApp queries the "app" edge of the Achievement entity.
func (_m *Achievement) QueryApp() *AppQuery {
	return NewAchievementClient(_m.config).QueryApp(_m)
}

// QueryUser queries the "user" edge of the Achievement entity.
func (_m *Achievement) QueryUser() *UserQuery {
	return NewAchievementClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this Achievement.
// Note that you need to call Achievement.Unwrap() before calling this method if this Achievement
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Achievement) Update() *AchievementUpdateOne {
	return NewAchievementClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Achievement entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Achievement) Unwrap() *Achievement {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Achievement is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Achievement) String() string {
	var builder strings.Builder
	builder.WriteString("Achievement(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("achievement_id=")
	builder.WriteString(_m.AchievementID)
	builder.WriteString(", ")
	builder.WriteString("earned_at=")
	builder.WriteString(_m.EarnedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Achievements is a parsable slice of Achievement.
type Achievements []*Achievement
