// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gigaboo.io/lem/internal/ent/achievement"
	"gigaboo.io/lem/internal/ent/app"
	"gigaboo.io/lem/internal/ent/user"
)

// AchievementCreate is the builder for creating a Achievement entity.
type AchievementCreate struct {
	config
	mutation *AchievementMutation
	hooks    []Hook
}

// SetAchievementID sets the "achievement_id" field.
func (_c *AchievementCreate) SetAchievementID(v string) *AchievementCreate {
	_c.mutation.SetAchievementID(v)
	return _c
}

// SetEarnedAt sets the "earned_at" field.
func (_c *AchievementCreate) SetEarnedAt(v time.Time) *AchievementCreate {
	_c.mutation.SetEarnedAt(v)
	return _c
}

// SetNillableEarnedAt sets the "earned_at" field if the given value is not nil.
func (_c *AchievementCreate) SetNillableEarnedAt(v *time.Time) *AchievementCreate {
	if v != nil {
		_c.SetEarnedAt(*v)
	}
	return _c
}

// SetAppID sets the "app" edge to the App entity by ID.
func (_c *AchievementCreate) SetAppID(id int) *AchievementCreate {
	_c.mutation.SetAppID(id)
	return _c
}

// SetApp sets the "app" edge to the App entity.
func (_c *AchievementCreate) SetApp(v *App) *AchievementCreate {
	return _c.SetAppID(v.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *AchievementCreate) SetUserID(id int) *AchievementCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *AchievementCreate) SetUser(v *User) *AchievementCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the AchievementMutation object of the builder.
func (_c *AchievementCreate) Mutation() *AchievementMutation {
	return _c.mutation
}

// Save creates the Achievement in the database.
func (_c *AchievementCreate) Save(ctx context.Context) (*Achievement, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AchievementCreate) SaveX(ctx context.Context) *Achievement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AchievementCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AchievementCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AchievementCreate) defaults() {
	if _, ok := _c.mutation.EarnedAt(); !ok {
		v := achievement.DefaultEarnedAt()
		_c.mutation.SetEarnedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AchievementCreate) check() error {
	if _, ok := _c.mutation.AchievementID(); !ok {
		return &ValidationError{Name: "achievement_id", err: errors.New(`ent: missing required field "Achievement.achievement_id"`)}
	}
	if v, ok := _c.mutation.AchievementID(); ok {
		if err := achievement.AchievementIDValidator(v); err != nil {
			return &ValidationError{Name: "achievement_id", err: fmt.Errorf(`ent: validator failed for field "Achievement.achievement_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EarnedAt(); !ok {
		return &ValidationError{Name: "earned_at", err: errors.New(`ent: missing required field "Achievement.earned_at"`)}
	}
	if len(_c.mutation.AppIDs()) == 0 {
		return &ValidationError{Name: "app", err: errors.New(`ent: missing required edge "Achievement.app"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Achievement.user"`)}
	}
	return nil
}

func (_c *AchievementCreate) sqlSave(ctx context.Context) (*Achievement, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AchievementCreate) createSpec() (*Achievement, *sqlgraph.CreateSpec) {
	var (
		_node = &Achievement{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(achievement.Table, sqlgraph.NewFieldSpec(achievement.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.AchievementID(); ok {
		_spec.SetField(achievement.FieldAchievementID, field.TypeString, value)
		_node.AchievementID = value
	}
	if value, ok := _c.mutation.EarnedAt(); ok {
		_spec.SetField(achievement.FieldEarnedAt, field.TypeTime, value)
		_node.EarnedAt = value
	}
	if nodes := _c.mutation.AppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   achievement.AppTable,
			Columns: []string{achievement.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.app_achievements = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   achievement.UserTable,
			Columns: []string{achievement.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_achievements = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AchievementCreateBulk is the builder for creating many Achievement entities in bulk.
type AchievementCreateBulk struct {
	config
	err      error
	builders []*AchievementCreate
}

// Save creates the Achievement entities in the database.
func (_c *AchievementCreateBulk) Save(ctx context.Context) ([]*Achievement, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Achievement, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AchievementMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AchievementCreateBulk) SaveX(ctx context.Context) []*Achievement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AchievementCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AchievementCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
