// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"gigaboo.io/lem/internal/ent/achievement"
	"gigaboo.io/lem/internal/ent/app"
	"gigaboo.io/lem/internal/ent/battleroom"
	"gigaboo.io/lem/internal/ent/battlesession"
	"gigaboo.io/lem/internal/ent/classroom"
	"gigaboo.io/lem/internal/ent/classroomsession"
	"gigaboo.io/lem/internal/ent/emailtemplate"
	"gigaboo.io/lem/internal/ent/livesession"
	"gigaboo.io/lem/internal/ent/organization"
	"gigaboo.io/lem/internal/ent/plan"
	"gigaboo.io/lem/internal/ent/predicate"
	"gigaboo.io/lem/internal/ent/shenbiprofile"
	"gigaboo.io/lem/internal/ent/shenbisettings"
	"gigaboo.io/lem/internal/ent/subscription"
	"gigaboo.io/lem/internal/ent/userapp"
	"gigaboo.io/lem/internal/ent/userprogress"
)

// AppUpdate is the builder for updating App entities.
type AppUpdate struct {
	config
	hooks    []Hook
	mutation *AppMutation
}

// Where appends a list predicates to the AppUpdate builder.
func (_u *AppUpdate) Where(ps ...predicate.App) *AppUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *AppUpdate) SetName(v string) *AppUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AppUpdate) SetNillableName(v *string) *AppUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *AppUpdate) SetSlug(v string) *AppUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *AppUpdate) SetNillableSlug(v *string) *AppUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetAPIKey sets the "api_key" field.
func (_u *AppUpdate) SetAPIKey(v string) *AppUpdate {
	_u.mutation.SetAPIKey(v)
	return _u
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (_u *AppUpdate) SetNillableAPIKey(v *string) *AppUpdate {
	if v != nil {
		_u.SetAPIKey(*v)
	}
	return _u
}

// SetAPISecret sets the "api_secret" field.
func (_u *AppUpdate) SetAPISecret(v string) *AppUpdate {
	_u.mutation.SetAPISecret(v)
	return _u
}

// SetNillableAPISecret sets the "api_secret" field if the given value is not nil.
func (_u *AppUpdate) SetNillableAPISecret(v *string) *AppUpdate {
	if v != nil {
		_u.SetAPISecret(*v)
	}
	return _u
}

// ClearAPISecret clears the value of the "api_secret" field.
func (_u *AppUpdate) ClearAPISecret() *AppUpdate {
	_u.mutation.ClearAPISecret()
	return _u
}

// SetAllowedOrigins sets the "allowed_origins" field.
func (_u *AppUpdate) SetAllowedOrigins(v []string) *AppUpdate {
	_u.mutation.SetAllowedOrigins(v)
	return _u
}

// AppendAllowedOrigins appends value to the "allowed_origins" field.
func (_u *AppUpdate) AppendAllowedOrigins(v []string) *AppUpdate {
	_u.mutation.AppendAllowedOrigins(v)
	return _u
}

// ClearAllowedOrigins clears the value of the "allowed_origins" field.
func (_u *AppUpdate) ClearAllowedOrigins() *AppUpdate {
	_u.mutation.ClearAllowedOrigins()
	return _u
}

// SetWebhookURL sets the "webhook_url" field.
func (_u *AppUpdate) SetWebhookURL(v string) *AppUpdate {
	_u.mutation.SetWebhookURL(v)
	return _u
}

// SetNillableWebhookURL sets the "webhook_url" field if the given value is not nil.
func (_u *AppUpdate) SetNillableWebhookURL(v *string) *AppUpdate {
	if v != nil {
		_u.SetWebhookURL(*v)
	}
	return _u
}

// ClearWebhookURL clears the value of the "webhook_url" field.
func (_u *AppUpdate) ClearWebhookURL() *AppUpdate {
	_u.mutation.ClearWebhookURL()
	return _u
}

// SetStripeProductID sets the "stripe_product_id" field.
func (_u *AppUpdate) SetStripeProductID(v string) *AppUpdate {
	_u.mutation.SetStripeProductID(v)
	return _u
}

// SetNillableStripeProductID sets the "stripe_product_id" field if the given value is not nil.
func (_u *AppUpdate) SetNillableStripeProductID(v *string) *AppUpdate {
	if v != nil {
		_u.SetStripeProductID(*v)
	}
	return _u
}

// ClearStripeProductID clears the value of the "stripe_product_id" field.
func (_u *AppUpdate) ClearStripeProductID() *AppUpdate {
	_u.mutation.ClearStripeProductID()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *AppUpdate) SetIsActive(v bool) *AppUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *AppUpdate) SetNillableIsActive(v *bool) *AppUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AppUpdate) SetUpdatedAt(v time.Time) *AppUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUserAppIDs adds the "user_apps" edge to the UserApp entity by IDs.
func (_u *AppUpdate) AddUserAppIDs(ids ...int) *AppUpdate {
	_u.mutation.AddUserAppIDs(ids...)
	return _u
}

// AddUserApps adds the "user_apps" edges to the UserApp entity.
func (_u *AppUpdate) AddUserApps(v ...*UserApp) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserAppIDs(ids...)
}

// AddOrganizationIDs adds the "organizations" edge to the Organization entity by IDs.
func (_u *AppUpdate) AddOrganizationIDs(ids ...int) *AppUpdate {
	_u.mutation.AddOrganizationIDs(ids...)
	return _u
}

// AddOrganizations adds the "organizations" edges to the Organization entity.
func (_u *AppUpdate) AddOrganizations(v ...*Organization) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOrganizationIDs(ids...)
}

// AddPlanIDs adds the "plans" edge to the Plan entity by IDs.
func (_u *AppUpdate) AddPlanIDs(ids ...int) *AppUpdate {
	_u.mutation.AddPlanIDs(ids...)
	return _u
}

// AddPlans adds the "plans" edges to the Plan entity.
func (_u *AppUpdate) AddPlans(v ...*Plan) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPlanIDs(ids...)
}

// AddSubscriptionIDs adds the "subscriptions" edge to the Subscription entity by IDs.
func (_u *AppUpdate) AddSubscriptionIDs(ids ...int) *AppUpdate {
	_u.mutation.AddSubscriptionIDs(ids...)
	return _u
}

// AddSubscriptions adds the "subscriptions" edges to the Subscription entity.
func (_u *AppUpdate) AddSubscriptions(v ...*Subscription) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubscriptionIDs(ids...)
}

// AddEmailTemplateIDs adds the "email_templates" edge to the EmailTemplate entity by IDs.
func (_u *AppUpdate) AddEmailTemplateIDs(ids ...int) *AppUpdate {
	_u.mutation.AddEmailTemplateIDs(ids...)
	return _u
}

// AddEmailTemplates adds the "email_templates" edges to the EmailTemplate entity.
func (_u *AppUpdate) AddEmailTemplates(v ...*EmailTemplate) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEmailTemplateIDs(ids...)
}

// AddShenbiProfileIDs adds the "shenbi_profiles" edge to the ShenbiProfile entity by IDs.
func (_u *AppUpdate) AddShenbiProfileIDs(ids ...int) *AppUpdate {
	_u.mutation.AddShenbiProfileIDs(ids...)
	return _u
}

// AddShenbiProfiles adds the "shenbi_profiles" edges to the ShenbiProfile entity.
func (_u *AppUpdate) AddShenbiProfiles(v ...*ShenbiProfile) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddShenbiProfileIDs(ids...)
}

// AddClassroomIDs adds the "classrooms" edge to the Classroom entity by IDs.
func (_u *AppUpdate) AddClassroomIDs(ids ...int) *AppUpdate {
	_u.mutation.AddClassroomIDs(ids...)
	return _u
}

// AddClassrooms adds the "classrooms" edges to the Classroom entity.
func (_u *AppUpdate) AddClassrooms(v ...*Classroom) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddClassroomIDs(ids...)
}

// AddUserProgresIDs adds the "user_progress" edge to the UserProgress entity by IDs.
func (_u *AppUpdate) AddUserProgresIDs(ids ...int) *AppUpdate {
	_u.mutation.AddUserProgresIDs(ids...)
	return _u
}

// AddUserProgress adds the "user_progress" edges to the UserProgress entity.
func (_u *AppUpdate) AddUserProgress(v ...*UserProgress) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserProgresIDs(ids...)
}

// AddAchievementIDs adds the "achievements" edge to the Achievement entity by IDs.
func (_u *AppUpdate) AddAchievementIDs(ids ...int) *AppUpdate {
	_u.mutation.AddAchievementIDs(ids...)
	return _u
}

// AddAchievements adds the "achievements" edges to the Achievement entity.
func (_u *AppUpdate) AddAchievements(v ...*Achievement) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAchievementIDs(ids...)
}

// AddBattleRoomIDs adds the "battle_rooms" edge to the BattleRoom entity by IDs.
func (_u *AppUpdate) AddBattleRoomIDs(ids ...int) *AppUpdate {
	_u.mutation.AddBattleRoomIDs(ids...)
	return _u
}

// AddBattleRooms adds the "battle_rooms" edges to the BattleRoom entity.
func (_u *AppUpdate) AddBattleRooms(v ...*BattleRoom) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBattleRoomIDs(ids...)
}

// AddBattleSessionIDs adds the "battle_sessions" edge to the BattleSession entity by IDs.
func (_u *AppUpdate) AddBattleSessionIDs(ids ...int) *AppUpdate {
	_u.mutation.AddBattleSessionIDs(ids...)
	return _u
}

// AddBattleSessions adds the "battle_sessions" edges to the BattleSession entity.
func (_u *AppUpdate) AddBattleSessions(v ...*BattleSession) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBattleSessionIDs(ids...)
}

// AddLiveSessionIDs adds the "live_sessions" edge to the LiveSession entity by IDs.
func (_u *AppUpdate) AddLiveSessionIDs(ids ...int) *AppUpdate {
	_u.mutation.AddLiveSessionIDs(ids...)
	return _u
}

// AddLiveSessions adds the "live_sessions" edges to the LiveSession entity.
func (_u *AppUpdate) AddLiveSessions(v ...*LiveSession) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLiveSessionIDs(ids...)
}

// AddClassroomSessionIDs adds the "classroom_sessions" edge to the ClassroomSession entity by IDs.
func (_u *AppUpdate) AddClassroomSessionIDs(ids ...int) *AppUpdate {
	_u.mutation.AddClassroomSessionIDs(ids...)
	return _u
}

// AddClassroomSessions adds the "classroom_sessions" edges to the ClassroomSession entity.
func (_u *AppUpdate) AddClassroomSessions(v ...*ClassroomSession) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddClassroomSessionIDs(ids...)
}

// AddShenbiSettingIDs adds the "shenbi_settings" edge to the ShenbiSettings entity by IDs.
func (_u *AppUpdate) AddShenbiSettingIDs(ids ...int) *AppUpdate {
	_u.mutation.AddShenbiSettingIDs(ids...)
	return _u
}

// AddShenbiSettings adds the "shenbi_settings" edges to the ShenbiSettings entity.
func (_u *AppUpdate) AddShenbiSettings(v ...*ShenbiSettings) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddShenbiSettingIDs(ids...)
}

// Mutation returns the AppMutation object of the builder.
func (_u *AppUpdate) Mutation() *AppMutation {
	return _u.mutation
}

// ClearUserApps clears all "user_apps" edges to the UserApp entity.
func (_u *AppUpdate) ClearUserApps() *AppUpdate {
	_u.mutation.ClearUserApps()
	return _u
}

// RemoveUserAppIDs removes the "user_apps" edge to UserApp entities by IDs.
func (_u *AppUpdate) RemoveUserAppIDs(ids ...int) *AppUpdate {
	_u.mutation.RemoveUserAppIDs(ids...)
	return _u
}

// RemoveUserApps removes "user_apps" edges to UserApp entities.
func (_u *AppUpdate) RemoveUserApps(v ...*UserApp) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserAppIDs(ids...)
}

// ClearOrganizations clears all "organizations" edges to the Organization entity.
func (_u *AppUpdate) ClearOrganizations() *AppUpdate {
	_u.mutation.ClearOrganizations()
	return _u
}

// RemoveOrganizationIDs removes the "organizations" edge to Organization entities by IDs.
func (_u *AppUpdate) RemoveOrganizationIDs(ids ...int) *AppUpdate {
	_u.mutation.RemoveOrganizationIDs(ids...)
	return _u
}

// RemoveOrganizations removes "organizations" edges to Organization entities.
func (_u *AppUpdate) RemoveOrganizations(v ...*Organization) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOrganizationIDs(ids...)
}

// ClearPlans clears all "plans" edges to the Plan entity.
func (_u *AppUpdate) ClearPlans() *AppUpdate {
	_u.mutation.ClearPlans()
	return _u
}

// RemovePlanIDs removes the "plans" edge to Plan entities by IDs.
func (_u *AppUpdate) RemovePlanIDs(ids ...int) *AppUpdate {
	_u.mutation.RemovePlanIDs(ids...)
	return _u
}

// RemovePlans removes "plans" edges to Plan entities.
func (_u *AppUpdate) RemovePlans(v ...*Plan) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePlanIDs(ids...)
}

// ClearSubscriptions clears all "subscriptions" edges to the Subscription entity.
func (_u *AppUpdate) ClearSubscriptions() *AppUpdate {
	_u.mutation.ClearSubscriptions()
	return _u
}

// RemoveSubscriptionIDs removes the "subscriptions" edge to Subscription entities by IDs.
func (_u *AppUpdate) RemoveSubscriptionIDs(ids ...int) *AppUpdate {
	_u.mutation.RemoveSubscriptionIDs(ids...)
	return _u
}

// RemoveSubscriptions removes "subscriptions" edges to Subscription entities.
func (_u *AppUpdate) RemoveSubscriptions(v ...*Subscription) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubscriptionIDs(ids...)
}

// ClearEmailTemplates clears all "email_templates" edges to the EmailTemplate entity.
func (_u *AppUpdate) ClearEmailTemplates() *AppUpdate {
	_u.mutation.ClearEmailTemplates()
	return _u
}

// RemoveEmailTemplateIDs removes the "email_templates" edge to EmailTemplate entities by IDs.
func (_u *AppUpdate) RemoveEmailTemplateIDs(ids ...int) *AppUpdate {
	_u.mutation.RemoveEmailTemplateIDs(ids...)
	return _u
}

// RemoveEmailTemplates removes "email_templates" edges to EmailTemplate entities.
func (_u *AppUpdate) RemoveEmailTemplates(v ...*EmailTemplate) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEmailTemplateIDs(ids...)
}

// ClearShenbiProfiles clears all "shenbi_profiles" edges to the ShenbiProfile entity.
func (_u *AppUpdate) ClearShenbiProfiles() *AppUpdate {
	_u.mutation.ClearShenbiProfiles()
	return _u
}

// RemoveShenbiProfileIDs removes the "shenbi_profiles" edge to ShenbiProfile entities by IDs.
func (_u *AppUpdate) RemoveShenbiProfileIDs(ids ...int) *AppUpdate {
	_u.mutation.RemoveShenbiProfileIDs(ids...)
	return _u
}

// RemoveShenbiProfiles removes "shenbi_profiles" edges to ShenbiProfile entities.
func (_u *AppUpdate) RemoveShenbiProfiles(v ...*ShenbiProfile) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveShenbiProfileIDs(ids...)
}

// ClearClassrooms clears all "classrooms" edges to the Classroom entity.
func (_u *AppUpdate) ClearClassrooms() *AppUpdate {
	_u.mutation.ClearClassrooms()
	return _u
}

// RemoveClassroomIDs removes the "classrooms" edge to Classroom entities by IDs.
func (_u *AppUpdate) RemoveClassroomIDs(ids ...int) *AppUpdate {
	_u.mutation.RemoveClassroomIDs(ids...)
	return _u
}

// RemoveClassrooms removes "classrooms" edges to Classroom entities.
func (_u *AppUpdate) RemoveClassrooms(v ...*Classroom) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveClassroomIDs(ids...)
}

// ClearUserProgress clears all "user_progress" edges to the UserProgress entity.
func (_u *AppUpdate) ClearUserProgress() *AppUpdate {
	_u.mutation.ClearUserProgress()
	return _u
}

// RemoveUserProgresIDs removes the "user_progress" edge to UserProgress entities by IDs.
func (_u *AppUpdate) RemoveUserProgresIDs(ids ...int) *AppUpdate {
	_u.mutation.RemoveUserProgresIDs(ids...)
	return _u
}

// RemoveUserProgress removes "user_progress" edges to UserProgress entities.
func (_u *AppUpdate) RemoveUserProgress(v ...*UserProgress) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserProgresIDs(ids...)
}

// ClearAchievements clears all "achievements" edges to the Achievement entity.
func (_u *AppUpdate) ClearAchievements() *AppUpdate {
	_u.mutation.ClearAchievements()
	return _u
}

// RemoveAchievementIDs removes the "achievements" edge to Achievement entities by IDs.
func (_u *AppUpdate) RemoveAchievementIDs(ids ...int) *AppUpdate {
	_u.mutation.RemoveAchievementIDs(ids...)
	return _u
}

// RemoveAchievements removes "achievements" edges to Achievement entities.
func (_u *AppUpdate) RemoveAchievements(v ...*Achievement) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAchievementIDs(ids...)
}

// ClearBattleRooms clears all "battle_rooms" edges to the BattleRoom entity.
func (_u *AppUpdate) ClearBattleRooms() *AppUpdate {
	_u.mutation.ClearBattleRooms()
	return _u
}

// RemoveBattleRoomIDs removes the "battle_rooms" edge to BattleRoom entities by IDs.
func (_u *AppUpdate) RemoveBattleRoomIDs(ids ...int) *AppUpdate {
	_u.mutation.RemoveBattleRoomIDs(ids...)
	return _u
}

// RemoveBattleRooms removes "battle_rooms" edges to BattleRoom entities.
func (_u *AppUpdate) RemoveBattleRooms(v ...*BattleRoom) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBattleRoomIDs(ids...)
}

// ClearBattleSessions clears all "battle_sessions" edges to the BattleSession entity.
func (_u *AppUpdate) ClearBattleSessions() *AppUpdate {
	_u.mutation.ClearBattleSessions()
	return _u
}

// RemoveBattleSessionIDs removes the "battle_sessions" edge to BattleSession entities by IDs.
func (_u *AppUpdate) RemoveBattleSessionIDs(ids ...int) *AppUpdate {
	_u.mutation.RemoveBattleSessionIDs(ids...)
	return _u
}

// RemoveBattleSessions removes "battle_sessions" edges to BattleSession entities.
func (_u *AppUpdate) RemoveBattleSessions(v ...*BattleSession) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBattleSessionIDs(ids...)
}

// ClearLiveSessions clears all "live_sessions" edges to the LiveSession entity.
func (_u *AppUpdate) ClearLiveSessions() *AppUpdate {
	_u.mutation.ClearLiveSessions()
	return _u
}

// RemoveLiveSessionIDs removes the "live_sessions" edge to LiveSession entities by IDs.
func (_u *AppUpdate) RemoveLiveSessionIDs(ids ...int) *AppUpdate {
	_u.mutation.RemoveLiveSessionIDs(ids...)
	return _u
}

// RemoveLiveSessions removes "live_sessions" edges to LiveSession entities.
func (_u *AppUpdate) RemoveLiveSessions(v ...*LiveSession) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLiveSessionIDs(ids...)
}

// ClearClassroomSessions clears all "classroom_sessions" edges to the ClassroomSession entity.
func (_u *AppUpdate) ClearClassroomSessions() *AppUpdate {
	_u.mutation.ClearClassroomSessions()
	return _u
}

// RemoveClassroomSessionIDs removes the "classroom_sessions" edge to ClassroomSession entities by IDs.
func (_u *AppUpdate) RemoveClassroomSessionIDs(ids ...int) *AppUpdate {
	_u.mutation.RemoveClassroomSessionIDs(ids...)
	return _u
}

// RemoveClassroomSessions removes "classroom_sessions" edges to ClassroomSession entities.
func (_u *AppUpdate) RemoveClassroomSessions(v ...*ClassroomSession) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveClassroomSessionIDs(ids...)
}

// ClearShenbiSettings clears all "shenbi_settings" edges to the ShenbiSettings entity.
func (_u *AppUpdate) ClearShenbiSettings() *AppUpdate {
	_u.mutation.ClearShenbiSettings()
	return _u
}

// RemoveShenbiSettingIDs removes the "shenbi_settings" edge to ShenbiSettings entities by IDs.
func (_u *AppUpdate) RemoveShenbiSettingIDs(ids ...int) *AppUpdate {
	_u.mutation.RemoveShenbiSettingIDs(ids...)
	return _u
}

// RemoveShenbiSettings removes "shenbi_settings" edges to ShenbiSettings entities.
func (_u *AppUpdate) RemoveShenbiSettings(v ...*ShenbiSettings) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveShenbiSettingIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AppUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AppUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AppUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AppUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AppUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := app.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AppUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := app.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "App.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := app.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "App.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIKey(); ok {
		if err := app.APIKeyValidator(v); err != nil {
			return &ValidationError{Name: "api_key", err: fmt.Errorf(`ent: validator failed for field "App.api_key": %w`, err)}
		}
	}
	return nil
}

func (_u *AppUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(app.Table, app.Columns, sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(app.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(app.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKey(); ok {
		_spec.SetField(app.FieldAPIKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.APISecret(); ok {
		_spec.SetField(app.FieldAPISecret, field.TypeString, value)
	}
	if _u.mutation.APISecretCleared() {
		_spec.ClearField(app.FieldAPISecret, field.TypeString)
	}
	if value, ok := _u.mutation.AllowedOrigins(); ok {
		_spec.SetField(app.FieldAllowedOrigins, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedOrigins(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, app.FieldAllowedOrigins, value)
		})
	}
	if _u.mutation.AllowedOriginsCleared() {
		_spec.ClearField(app.FieldAllowedOrigins, field.TypeJSON)
	}
	if value, ok := _u.mutation.WebhookURL(); ok {
		_spec.SetField(app.FieldWebhookURL, field.TypeString, value)
	}
	if _u.mutation.WebhookURLCleared() {
		_spec.ClearField(app.FieldWebhookURL, field.TypeString)
	}
	if value, ok := _u.mutation.StripeProductID(); ok {
		_spec.SetField(app.FieldStripeProductID, field.TypeString, value)
	}
	if _u.mutation.StripeProductIDCleared() {
		_spec.ClearField(app.FieldStripeProductID, field.TypeString)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(app.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(app.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserAppsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.UserAppsTable,
			Columns: []string{app.UserAppsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userapp.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserAppsIDs(); len(nodes) > 0 && !_u.mutation.UserAppsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.UserAppsTable,
			Columns: []string{app.UserAppsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userapp.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserAppsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.UserAppsTable,
			Columns: []string{app.UserAppsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userapp.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrganizationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.OrganizationsTable,
			Columns: []string{app.OrganizationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOrganizationsIDs(); len(nodes) > 0 && !_u.mutation.OrganizationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.OrganizationsTable,
			Columns: []string{app.OrganizationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.OrganizationsTable,
			Columns: []string{app.OrganizationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.PlansTable,
			Columns: []string{app.PlansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPlansIDs(); len(nodes) > 0 && !_u.mutation.PlansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.PlansTable,
			Columns: []string{app.PlansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlansIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.PlansTable,
			Columns: []string{app.PlansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.SubscriptionsTable,
			Columns: []string{app.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubscriptionsIDs(); len(nodes) > 0 && !_u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.SubscriptionsTable,
			Columns: []string{app.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.SubscriptionsTable,
			Columns: []string{app.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EmailTemplatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.EmailTemplatesTable,
			Columns: []string{app.EmailTemplatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailtemplate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEmailTemplatesIDs(); len(nodes) > 0 && !_u.mutation.EmailTemplatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.EmailTemplatesTable,
			Columns: []string{app.EmailTemplatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailtemplate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EmailTemplatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.EmailTemplatesTable,
			Columns: []string{app.EmailTemplatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailtemplate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ShenbiProfilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.ShenbiProfilesTable,
			Columns: []string{app.ShenbiProfilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shenbiprofile.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedShenbiProfilesIDs(); len(nodes) > 0 && !_u.mutation.ShenbiProfilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.ShenbiProfilesTable,
			Columns: []string{app.ShenbiProfilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shenbiprofile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShenbiProfilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.ShenbiProfilesTable,
			Columns: []string{app.ShenbiProfilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shenbiprofile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClassroomsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.ClassroomsTable,
			Columns: []string{app.ClassroomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(classroom.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedClassroomsIDs(); len(nodes) > 0 && !_u.mutation.ClassroomsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.ClassroomsTable,
			Columns: []string{app.ClassroomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(classroom.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClassroomsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.ClassroomsTable,
			Columns: []string{app.ClassroomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(classroom.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserProgressCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.UserProgressTable,
			Columns: []string{app.UserProgressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userprogress.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserProgressIDs(); len(nodes) > 0 && !_u.mutation.UserProgressCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.UserProgressTable,
			Columns: []string{app.UserProgressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userprogress.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserProgressIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.UserProgressTable,
			Columns: []string{app.UserProgressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userprogress.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AchievementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.AchievementsTable,
			Columns: []string{app.AchievementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(achievement.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAchievementsIDs(); len(nodes) > 0 && !_u.mutation.AchievementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.AchievementsTable,
			Columns: []string{app.AchievementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(achievement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AchievementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.AchievementsTable,
			Columns: []string{app.AchievementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(achievement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BattleRoomsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.BattleRoomsTable,
			Columns: []string{app.BattleRoomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(battleroom.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBattleRoomsIDs(); len(nodes) > 0 && !_u.mutation.BattleRoomsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.BattleRoomsTable,
			Columns: []string{app.BattleRoomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(battleroom.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BattleRoomsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.BattleRoomsTable,
			Columns: []string{app.BattleRoomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(battleroom.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BattleSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.BattleSessionsTable,
			Columns: []string{app.BattleSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(battlesession.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBattleSessionsIDs(); len(nodes) > 0 && !_u.mutation.BattleSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.BattleSessionsTable,
			Columns: []string{app.BattleSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(battlesession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BattleSessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.BattleSessionsTable,
			Columns: []string{app.BattleSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(battlesession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LiveSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.LiveSessionsTable,
			Columns: []string{app.LiveSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(livesession.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLiveSessionsIDs(); len(nodes) > 0 && !_u.mutation.LiveSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.LiveSessionsTable,
			Columns: []string{app.LiveSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(livesession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LiveSessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.LiveSessionsTable,
			Columns: []string{app.LiveSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(livesession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClassroomSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.ClassroomSessionsTable,
			Columns: []string{app.ClassroomSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(classroomsession.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedClassroomSessionsIDs(); len(nodes) > 0 && !_u.mutation.ClassroomSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.ClassroomSessionsTable,
			Columns: []string{app.ClassroomSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(classroomsession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClassroomSessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.ClassroomSessionsTable,
			Columns: []string{app.ClassroomSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(classroomsession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ShenbiSettingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.ShenbiSettingsTable,
			Columns: []string{app.ShenbiSettingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shenbisettings.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedShenbiSettingsIDs(); len(nodes) > 0 && !_u.mutation.ShenbiSettingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.ShenbiSettingsTable,
			Columns: []string{app.ShenbiSettingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shenbisettings.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShenbiSettingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.ShenbiSettingsTable,
			Columns: []string{app.ShenbiSettingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shenbisettings.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{app.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AppUpdateOne is the builder for updating a single App entity.
type AppUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AppMutation
}

// SetName sets the "name" field.
func (_u *AppUpdateOne) SetName(v string) *AppUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableName(v *string) *AppUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *AppUpdateOne) SetSlug(v string) *AppUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableSlug(v *string) *AppUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetAPIKey sets the "api_key" field.
func (_u *AppUpdateOne) SetAPIKey(v string) *AppUpdateOne {
	_u.mutation.SetAPIKey(v)
	return _u
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableAPIKey(v *string) *AppUpdateOne {
	if v != nil {
		_u.SetAPIKey(*v)
	}
	return _u
}

// SetAPISecret sets the "api_secret" field.
func (_u *AppUpdateOne) SetAPISecret(v string) *AppUpdateOne {
	_u.mutation.SetAPISecret(v)
	return _u
}

// SetNillableAPISecret sets the "api_secret" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableAPISecret(v *string) *AppUpdateOne {
	if v != nil {
		_u.SetAPISecret(*v)
	}
	return _u
}

// ClearAPISecret clears the value of the "api_secret" field.
func (_u *AppUpdateOne) ClearAPISecret() *AppUpdateOne {
	_u.mutation.ClearAPISecret()
	return _u
}

// SetAllowedOrigins sets the "allowed_origins" field.
func (_u *AppUpdateOne) SetAllowedOrigins(v []string) *AppUpdateOne {
	_u.mutation.SetAllowedOrigins(v)
	return _u
}

// AppendAllowedOrigins appends value to the "allowed_origins" field.
func (_u *AppUpdateOne) AppendAllowedOrigins(v []string) *AppUpdateOne {
	_u.mutation.AppendAllowedOrigins(v)
	return _u
}

// ClearAllowedOrigins clears the value of the "allowed_origins" field.
func (_u *AppUpdateOne) ClearAllowedOrigins() *AppUpdateOne {
	_u.mutation.ClearAllowedOrigins()
	return _u
}

// SetWebhookURL sets the "webhook_url" field.
func (_u *AppUpdateOne) SetWebhookURL(v string) *AppUpdateOne {
	_u.mutation.SetWebhookURL(v)
	return _u
}

// SetNillableWebhookURL sets the "webhook_url" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableWebhookURL(v *string) *AppUpdateOne {
	if v != nil {
		_u.SetWebhookURL(*v)
	}
	return _u
}

// ClearWebhookURL clears the value of the "webhook_url" field.
func (_u *AppUpdateOne) ClearWebhookURL() *AppUpdateOne {
	_u.mutation.ClearWebhookURL()
	return _u
}

// SetStripeProductID sets the "stripe_product_id" field.
func (_u *AppUpdateOne) SetStripeProductID(v string) *AppUpdateOne {
	_u.mutation.SetStripeProductID(v)
	return _u
}

// SetNillableStripeProductID sets the "stripe_product_id" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableStripeProductID(v *string) *AppUpdateOne {
	if v != nil {
		_u.SetStripeProductID(*v)
	}
	return _u
}

// ClearStripeProductID clears the value of the "stripe_product_id" field.
func (_u *AppUpdateOne) ClearStripeProductID() *AppUpdateOne {
	_u.mutation.ClearStripeProductID()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *AppUpdateOne) SetIsActive(v bool) *AppUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableIsActive(v *bool) *AppUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AppUpdateOne) SetUpdatedAt(v time.Time) *AppUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUserAppIDs adds the "user_apps" edge to the UserApp entity by IDs.
func (_u *AppUpdateOne) AddUserAppIDs(ids ...int) *AppUpdateOne {
	_u.mutation.AddUserAppIDs(ids...)
	return _u
}

// AddUserApps adds the "user_apps" edges to the UserApp entity.
func (_u *AppUpdateOne) AddUserApps(v ...*UserApp) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserAppIDs(ids...)
}

// AddOrganizationIDs adds the "organizations" edge to the Organization entity by IDs.
func (_u *AppUpdateOne) AddOrganizationIDs(ids ...int) *AppUpdateOne {
	_u.mutation.AddOrganizationIDs(ids...)
	return _u
}

// AddOrganizations adds the "organizations" edges to the Organization entity.
func (_u *AppUpdateOne) AddOrganizations(v ...*Organization) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOrganizationIDs(ids...)
}

// AddPlanIDs adds the "plans" edge to the Plan entity by IDs.
func (_u *AppUpdateOne) AddPlanIDs(ids ...int) *AppUpdateOne {
	_u.mutation.AddPlanIDs(ids...)
	return _u
}

// AddPlans adds the "plans" edges to the Plan entity.
func (_u *AppUpdateOne) AddPlans(v ...*Plan) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPlanIDs(ids...)
}

// AddSubscriptionIDs adds the "subscriptions" edge to the Subscription entity by IDs.
func (_u *AppUpdateOne) AddSubscriptionIDs(ids ...int) *AppUpdateOne {
	_u.mutation.AddSubscriptionIDs(ids...)
	return _u
}

// AddSubscriptions adds the "subscriptions" edges to the Subscription entity.
func (_u *AppUpdateOne) AddSubscriptions(v ...*Subscription) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubscriptionIDs(ids...)
}

// AddEmailTemplateIDs adds the "email_templates" edge to the EmailTemplate entity by IDs.
func (_u *AppUpdateOne) AddEmailTemplateIDs(ids ...int) *AppUpdateOne {
	_u.mutation.AddEmailTemplateIDs(ids...)
	return _u
}

// AddEmailTemplates adds the "email_templates" edges to the EmailTemplate entity.
func (_u *AppUpdateOne) AddEmailTemplates(v ...*EmailTemplate) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEmailTemplateIDs(ids...)
}

// AddShenbiProfileIDs adds the "shenbi_profiles" edge to the ShenbiProfile entity by IDs.
func (_u *AppUpdateOne) AddShenbiProfileIDs(ids ...int) *AppUpdateOne {
	_u.mutation.AddShenbiProfileIDs(ids...)
	return _u
}

// AddShenbiProfiles adds the "shenbi_profiles" edges to the ShenbiProfile entity.
func (_u *AppUpdateOne) AddShenbiProfiles(v ...*ShenbiProfile) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddShenbiProfileIDs(ids...)
}

// AddClassroomIDs adds the "classrooms" edge to the Classroom entity by IDs.
func (_u *AppUpdateOne) AddClassroomIDs(ids ...int) *AppUpdateOne {
	_u.mutation.AddClassroomIDs(ids...)
	return _u
}

// AddClassrooms adds the "classrooms" edges to the Classroom entity.
func (_u *AppUpdateOne) AddClassrooms(v ...*Classroom) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddClassroomIDs(ids...)
}

// AddUserProgresIDs adds the "user_progress" edge to the UserProgress entity by IDs.
func (_u *AppUpdateOne) AddUserProgresIDs(ids ...int) *AppUpdateOne {
	_u.mutation.AddUserProgresIDs(ids...)
	return _u
}

// AddUserProgress adds the "user_progress" edges to the UserProgress entity.
func (_u *AppUpdateOne) AddUserProgress(v ...*UserProgress) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserProgresIDs(ids...)
}

// AddAchievementIDs adds the "achievements" edge to the Achievement entity by IDs.
func (_u *AppUpdateOne) AddAchievementIDs(ids ...int) *AppUpdateOne {
	_u.mutation.AddAchievementIDs(ids...)
	return _u
}

// AddAchievements adds the "achievements" edges to the Achievement entity.
func (_u *AppUpdateOne) AddAchievements(v ...*Achievement) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAchievementIDs(ids...)
}

// AddBattleRoomIDs adds the "battle_rooms" edge to the BattleRoom entity by IDs.
func (_u *AppUpdateOne) AddBattleRoomIDs(ids ...int) *AppUpdateOne {
	_u.mutation.AddBattleRoomIDs(ids...)
	return _u
}

// AddBattleRooms adds the "battle_rooms" edges to the BattleRoom entity.
func (_u *AppUpdateOne) AddBattleRooms(v ...*BattleRoom) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBattleRoomIDs(ids...)
}

// AddBattleSessionIDs adds the "battle_sessions" edge to the BattleSession entity by IDs.
func (_u *AppUpdateOne) AddBattleSessionIDs(ids ...int) *AppUpdateOne {
	_u.mutation.AddBattleSessionIDs(ids...)
	return _u
}

// AddBattleSessions adds the "battle_sessions" edges to the BattleSession entity.
func (_u *AppUpdateOne) AddBattleSessions(v ...*BattleSession) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBattleSessionIDs(ids...)
}

// AddLiveSessionIDs adds the "live_sessions" edge to the LiveSession entity by IDs.
func (_u *AppUpdateOne) AddLiveSessionIDs(ids ...int) *AppUpdateOne {
	_u.mutation.AddLiveSessionIDs(ids...)
	return _u
}

// AddLiveSessions adds the "live_sessions" edges to the LiveSession entity.
func (_u *AppUpdateOne) AddLiveSessions(v ...*LiveSession) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLiveSessionIDs(ids...)
}

// AddClassroomSessionIDs adds the "classroom_sessions" edge to the ClassroomSession entity by IDs.
func (_u *AppUpdateOne) AddClassroomSessionIDs(ids ...int) *AppUpdateOne {
	_u.mutation.AddClassroomSessionIDs(ids...)
	return _u
}

// AddClassroomSessions adds the "classroom_sessions" edges to the ClassroomSession entity.
func (_u *AppUpdateOne) AddClassroomSessions(v ...*ClassroomSession) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddClassroomSessionIDs(ids...)
}

// AddShenbiSettingIDs adds the "shenbi_settings" edge to the ShenbiSettings entity by IDs.
func (_u *AppUpdateOne) AddShenbiSettingIDs(ids ...int) *AppUpdateOne {
	_u.mutation.AddShenbiSettingIDs(ids...)
	return _u
}

// AddShenbiSettings adds the "shenbi_settings" edges to the ShenbiSettings entity.
func (_u *AppUpdateOne) AddShenbiSettings(v ...*ShenbiSettings) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddShenbiSettingIDs(ids...)
}

// Mutation returns the AppMutation object of the builder.
func (_u *AppUpdateOne) Mutation() *AppMutation {
	return _u.mutation
}

// ClearUserApps clears all "user_apps" edges to the UserApp entity.
func (_u *AppUpdateOne) ClearUserApps() *AppUpdateOne {
	_u.mutation.ClearUserApps()
	return _u
}

// RemoveUserAppIDs removes the "user_apps" edge to UserApp entities by IDs.
func (_u *AppUpdateOne) RemoveUserAppIDs(ids ...int) *AppUpdateOne {
	_u.mutation.RemoveUserAppIDs(ids...)
	return _u
}

// RemoveUserApps removes "user_apps" edges to UserApp entities.
func (_u *AppUpdateOne) RemoveUserApps(v ...*UserApp) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserAppIDs(ids...)
}

// ClearOrganizations clears all "organizations" edges to the Organization entity.
func (_u *AppUpdateOne) ClearOrganizations() *AppUpdateOne {
	_u.mutation.ClearOrganizations()
	return _u
}

// RemoveOrganizationIDs removes the "organizations" edge to Organization entities by IDs.
func (_u *AppUpdateOne) RemoveOrganizationIDs(ids ...int) *AppUpdateOne {
	_u.mutation.RemoveOrganizationIDs(ids...)
	return _u
}

// RemoveOrganizations removes "organizations" edges to Organization entities.
func (_u *AppUpdateOne) RemoveOrganizations(v ...*Organization) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOrganizationIDs(ids...)
}

// ClearPlans clears all "plans" edges to the Plan entity.
func (_u *AppUpdateOne) ClearPlans() *AppUpdateOne {
	_u.mutation.ClearPlans()
	return _u
}

// RemovePlanIDs removes the "plans" edge to Plan entities by IDs.
func (_u *AppUpdateOne) RemovePlanIDs(ids ...int) *AppUpdateOne {
	_u.mutation.RemovePlanIDs(ids...)
	return _u
}

// RemovePlans removes "plans" edges to Plan entities.
func (_u *AppUpdateOne) RemovePlans(v ...*Plan) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePlanIDs(ids...)
}

// ClearSubscriptions clears all "subscriptions" edges to the Subscription entity.
func (_u *AppUpdateOne) ClearSubscriptions() *AppUpdateOne {
	_u.mutation.ClearSubscriptions()
	return _u
}

// RemoveSubscriptionIDs removes the "subscriptions" edge to Subscription entities by IDs.
func (_u *AppUpdateOne) RemoveSubscriptionIDs(ids ...int) *AppUpdateOne {
	_u.mutation.RemoveSubscriptionIDs(ids...)
	return _u
}

// RemoveSubscriptions removes "subscriptions" edges to Subscription entities.
func (_u *AppUpdateOne) RemoveSubscriptions(v ...*Subscription) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubscriptionIDs(ids...)
}

// ClearEmailTemplates clears all "email_templates" edges to the EmailTemplate entity.
func (_u *AppUpdateOne) ClearEmailTemplates() *AppUpdateOne {
	_u.mutation.ClearEmailTemplates()
	return _u
}

// RemoveEmailTemplateIDs removes the "email_templates" edge to EmailTemplate entities by IDs.
func (_u *AppUpdateOne) RemoveEmailTemplateIDs(ids ...int) *AppUpdateOne {
	_u.mutation.RemoveEmailTemplateIDs(ids...)
	return _u
}

// RemoveEmailTemplates removes "email_templates" edges to EmailTemplate entities.
func (_u *AppUpdateOne) RemoveEmailTemplates(v ...*EmailTemplate) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEmailTemplateIDs(ids...)
}

// ClearShenbiProfiles clears all "shenbi_profiles" edges to the ShenbiProfile entity.
func (_u *AppUpdateOne) ClearShenbiProfiles() *AppUpdateOne {
	_u.mutation.ClearShenbiProfiles()
	return _u
}

// RemoveShenbiProfileIDs removes the "shenbi_profiles" edge to ShenbiProfile entities by IDs.
func (_u *AppUpdateOne) RemoveShenbiProfileIDs(ids ...int) *AppUpdateOne {
	_u.mutation.RemoveShenbiProfileIDs(ids...)
	return _u
}

// RemoveShenbiProfiles removes "shenbi_profiles" edges to ShenbiProfile entities.
func (_u *AppUpdateOne) RemoveShenbiProfiles(v ...*ShenbiProfile) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveShenbiProfileIDs(ids...)
}

// ClearClassrooms clears all "classrooms" edges to the Classroom entity.
func (_u *AppUpdateOne) ClearClassrooms() *AppUpdateOne {
	_u.mutation.ClearClassrooms()
	return _u
}

// RemoveClassroomIDs removes the "classrooms" edge to Classroom entities by IDs.
func (_u *AppUpdateOne) RemoveClassroomIDs(ids ...int) *AppUpdateOne {
	_u.mutation.RemoveClassroomIDs(ids...)
	return _u
}

// RemoveClassrooms removes "classrooms" edges to Classroom entities.
func (_u *AppUpdateOne) RemoveClassrooms(v ...*Classroom) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveClassroomIDs(ids...)
}

// ClearUserProgress clears all "user_progress" edges to the UserProgress entity.
func (_u *AppUpdateOne) ClearUserProgress() *AppUpdateOne {
	_u.mutation.ClearUserProgress()
	return _u
}

// RemoveUserProgresIDs removes the "user_progress" edge to UserProgress entities by IDs.
func (_u *AppUpdateOne) RemoveUserProgresIDs(ids ...int) *AppUpdateOne {
	_u.mutation.RemoveUserProgresIDs(ids...)
	return _u
}

// RemoveUserProgress removes "user_progress" edges to UserProgress entities.
func (_u *AppUpdateOne) RemoveUserProgress(v ...*UserProgress) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserProgresIDs(ids...)
}

// ClearAchievements clears all "achievements" edges to the Achievement entity.
func (_u *AppUpdateOne) ClearAchievements() *AppUpdateOne {
	_u.mutation.ClearAchievements()
	return _u
}

// RemoveAchievementIDs removes the "achievements" edge to Achievement entities by IDs.
func (_u *AppUpdateOne) RemoveAchievementIDs(ids ...int) *AppUpdateOne {
	_u.mutation.RemoveAchievementIDs(ids...)
	return _u
}

// RemoveAchievements removes "achievements" edges to Achievement entities.
func (_u *AppUpdateOne) RemoveAchievements(v ...*Achievement) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAchievementIDs(ids...)
}

// ClearBattleRooms clears all "battle_rooms" edges to the BattleRoom entity.
func (_u *AppUpdateOne) ClearBattleRooms() *AppUpdateOne {
	_u.mutation.ClearBattleRooms()
	return _u
}

// RemoveBattleRoomIDs removes the "battle_rooms" edge to BattleRoom entities by IDs.
func (_u *AppUpdateOne) RemoveBattleRoomIDs(ids ...int) *AppUpdateOne {
	_u.mutation.RemoveBattleRoomIDs(ids...)
	return _u
}

// RemoveBattleRooms removes "battle_rooms" edges to BattleRoom entities.
func (_u *AppUpdateOne) RemoveBattleRooms(v ...*BattleRoom) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBattleRoomIDs(ids...)
}

// ClearBattleSessions clears all "battle_sessions" edges to the BattleSession entity.
func (_u *AppUpdateOne) ClearBattleSessions() *AppUpdateOne {
	_u.mutation.ClearBattleSessions()
	return _u
}

// RemoveBattleSessionIDs removes the "battle_sessions" edge to BattleSession entities by IDs.
func (_u *AppUpdateOne) RemoveBattleSessionIDs(ids ...int) *AppUpdateOne {
	_u.mutation.RemoveBattleSessionIDs(ids...)
	return _u
}

// RemoveBattleSessions removes "battle_sessions" edges to BattleSession entities.
func (_u *AppUpdateOne) RemoveBattleSessions(v ...*BattleSession) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBattleSessionIDs(ids...)
}

// ClearLiveSessions clears all "live_sessions" edges to the LiveSession entity.
func (_u *AppUpdateOne) ClearLiveSessions() *AppUpdateOne {
	_u.mutation.ClearLiveSessions()
	return _u
}

// RemoveLiveSessionIDs removes the "live_sessions" edge to LiveSession entities by IDs.
func (_u *AppUpdateOne) RemoveLiveSessionIDs(ids ...int) *AppUpdateOne {
	_u.mutation.RemoveLiveSessionIDs(ids...)
	return _u
}

// RemoveLiveSessions removes "live_sessions" edges to LiveSession entities.
func (_u *AppUpdateOne) RemoveLiveSessions(v ...*LiveSession) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLiveSessionIDs(ids...)
}

// ClearClassroomSessions clears all "classroom_sessions" edges to the ClassroomSession entity.
func (_u *AppUpdateOne) ClearClassroomSessions() *AppUpdateOne {
	_u.mutation.ClearClassroomSessions()
	return _u
}

// RemoveClassroomSessionIDs removes the "classroom_sessions" edge to ClassroomSession entities by IDs.
func (_u *AppUpdateOne) RemoveClassroomSessionIDs(ids ...int) *AppUpdateOne {
	_u.mutation.RemoveClassroomSessionIDs(ids...)
	return _u
}

// RemoveClassroomSessions removes "classroom_sessions" edges to ClassroomSession entities.
func (_u *AppUpdateOne) RemoveClassroomSessions(v ...*ClassroomSession) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveClassroomSessionIDs(ids...)
}

// ClearShenbiSettings clears all "shenbi_settings" edges to the ShenbiSettings entity.
func (_u *AppUpdateOne) ClearShenbiSettings() *AppUpdateOne {
	_u.mutation.ClearShenbiSettings()
	return _u
}

// RemoveShenbiSettingIDs removes the "shenbi_settings" edge to ShenbiSettings entities by IDs.
func (_u *AppUpdateOne) RemoveShenbiSettingIDs(ids ...int) *AppUpdateOne {
	_u.mutation.RemoveShenbiSettingIDs(ids...)
	return _u
}

// RemoveShenbiSettings removes "shenbi_settings" edges to ShenbiSettings entities.
func (_u *AppUpdateOne) RemoveShenbiSettings(v ...*ShenbiSettings) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveShenbiSettingIDs(ids...)
}

// Where appends a list predicates to the AppUpdate builder.
func (_u *AppUpdateOne) Where(ps ...predicate.App) *AppUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AppUpdateOne) Select(field string, fields ...string) *AppUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated App entity.
func (_u *AppUpdateOne) Save(ctx context.Context) (*App, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AppUpdateOne) SaveX(ctx context.Context) *App {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AppUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AppUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AppUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := app.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AppUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := app.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "App.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := app.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "App.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIKey(); ok {
		if err := app.APIKeyValidator(v); err != nil {
			return &ValidationError{Name: "api_key", err: fmt.Errorf(`ent: validator failed for field "App.api_key": %w`, err)}
		}
	}
	return nil
}

func (_u *AppUpdateOne) sqlSave(ctx context.Context) (_node *App, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(app.Table, app.Columns, sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "App.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, app.FieldID)
		for _, f := range fields {
			if !app.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != app.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(app.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(app.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKey(); ok {
		_spec.SetField(app.FieldAPIKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.APISecret(); ok {
		_spec.SetField(app.FieldAPISecret, field.TypeString, value)
	}
	if _u.mutation.APISecretCleared() {
		_spec.ClearField(app.FieldAPISecret, field.TypeString)
	}
	if value, ok := _u.mutation.AllowedOrigins(); ok {
		_spec.SetField(app.FieldAllowedOrigins, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedOrigins(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, app.FieldAllowedOrigins, value)
		})
	}
	if _u.mutation.AllowedOriginsCleared() {
		_spec.ClearField(app.FieldAllowedOrigins, field.TypeJSON)
	}
	if value, ok := _u.mutation.WebhookURL(); ok {
		_spec.SetField(app.FieldWebhookURL, field.TypeString, value)
	}
	if _u.mutation.WebhookURLCleared() {
		_spec.ClearField(app.FieldWebhookURL, field.TypeString)
	}
	if value, ok := _u.mutation.StripeProductID(); ok {
		_spec.SetField(app.FieldStripeProductID, field.TypeString, value)
	}
	if _u.mutation.StripeProductIDCleared() {
		_spec.ClearField(app.FieldStripeProductID, field.TypeString)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(app.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(app.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserAppsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.UserAppsTable,
			Columns: []string{app.UserAppsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userapp.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserAppsIDs(); len(nodes) > 0 && !_u.mutation.UserAppsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.UserAppsTable,
			Columns: []string{app.UserAppsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userapp.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserAppsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.UserAppsTable,
			Columns: []string{app.UserAppsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userapp.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrganizationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.OrganizationsTable,
			Columns: []string{app.OrganizationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOrganizationsIDs(); len(nodes) > 0 && !_u.mutation.OrganizationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.OrganizationsTable,
			Columns: []string{app.OrganizationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.OrganizationsTable,
			Columns: []string{app.OrganizationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.PlansTable,
			Columns: []string{app.PlansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPlansIDs(); len(nodes) > 0 && !_u.mutation.PlansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.PlansTable,
			Columns: []string{app.PlansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlansIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.PlansTable,
			Columns: []string{app.PlansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.SubscriptionsTable,
			Columns: []string{app.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubscriptionsIDs(); len(nodes) > 0 && !_u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.SubscriptionsTable,
			Columns: []string{app.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.SubscriptionsTable,
			Columns: []string{app.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EmailTemplatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.EmailTemplatesTable,
			Columns: []string{app.EmailTemplatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailtemplate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEmailTemplatesIDs(); len(nodes) > 0 && !_u.mutation.EmailTemplatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.EmailTemplatesTable,
			Columns: []string{app.EmailTemplatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailtemplate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EmailTemplatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.EmailTemplatesTable,
			Columns: []string{app.EmailTemplatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailtemplate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ShenbiProfilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.ShenbiProfilesTable,
			Columns: []string{app.ShenbiProfilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shenbiprofile.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedShenbiProfilesIDs(); len(nodes) > 0 && !_u.mutation.ShenbiProfilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.ShenbiProfilesTable,
			Columns: []string{app.ShenbiProfilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shenbiprofile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShenbiProfilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.ShenbiProfilesTable,
			Columns: []string{app.ShenbiProfilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shenbiprofile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClassroomsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.ClassroomsTable,
			Columns: []string{app.ClassroomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(classroom.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedClassroomsIDs(); len(nodes) > 0 && !_u.mutation.ClassroomsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.ClassroomsTable,
			Columns: []string{app.ClassroomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(classroom.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClassroomsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.ClassroomsTable,
			Columns: []string{app.ClassroomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(classroom.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserProgressCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.UserProgressTable,
			Columns: []string{app.UserProgressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userprogress.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserProgressIDs(); len(nodes) > 0 && !_u.mutation.UserProgressCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.UserProgressTable,
			Columns: []string{app.UserProgressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userprogress.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserProgressIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.UserProgressTable,
			Columns: []string{app.UserProgressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userprogress.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AchievementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.AchievementsTable,
			Columns: []string{app.AchievementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(achievement.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAchievementsIDs(); len(nodes) > 0 && !_u.mutation.AchievementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.AchievementsTable,
			Columns: []string{app.AchievementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(achievement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AchievementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.AchievementsTable,
			Columns: []string{app.AchievementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(achievement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BattleRoomsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.BattleRoomsTable,
			Columns: []string{app.BattleRoomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(battleroom.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBattleRoomsIDs(); len(nodes) > 0 && !_u.mutation.BattleRoomsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.BattleRoomsTable,
			Columns: []string{app.BattleRoomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(battleroom.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BattleRoomsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.BattleRoomsTable,
			Columns: []string{app.BattleRoomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(battleroom.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BattleSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.BattleSessionsTable,
			Columns: []string{app.BattleSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(battlesession.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBattleSessionsIDs(); len(nodes) > 0 && !_u.mutation.BattleSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.BattleSessionsTable,
			Columns: []string{app.BattleSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(battlesession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BattleSessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.BattleSessionsTable,
			Columns: []string{app.BattleSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(battlesession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LiveSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.LiveSessionsTable,
			Columns: []string{app.LiveSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(livesession.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLiveSessionsIDs(); len(nodes) > 0 && !_u.mutation.LiveSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.LiveSessionsTable,
			Columns: []string{app.LiveSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(livesession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LiveSessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.LiveSessionsTable,
			Columns: []string{app.LiveSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(livesession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClassroomSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.ClassroomSessionsTable,
			Columns: []string{app.ClassroomSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(classroomsession.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedClassroomSessionsIDs(); len(nodes) > 0 && !_u.mutation.ClassroomSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.ClassroomSessionsTable,
			Columns: []string{app.ClassroomSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(classroomsession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClassroomSessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.ClassroomSessionsTable,
			Columns: []string{app.ClassroomSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(classroomsession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ShenbiSettingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.ShenbiSettingsTable,
			Columns: []string{app.ShenbiSettingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shenbisettings.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedShenbiSettingsIDs(); len(nodes) > 0 && !_u.mutation.ShenbiSettingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.ShenbiSettingsTable,
			Columns: []string{app.ShenbiSettingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shenbisettings.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShenbiSettingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.ShenbiSettingsTable,
			Columns: []string{app.ShenbiSettingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shenbisettings.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &App{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{app.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
