// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gigaboo.io/lem/internal/ent/assignment"
	"gigaboo.io/lem/internal/ent/assignmentsubmission"
	"gigaboo.io/lem/internal/ent/predicate"
	"gigaboo.io/lem/internal/ent/user"
)

// AssignmentSubmissionUpdate is the builder for updating AssignmentSubmission entities.
type AssignmentSubmissionUpdate struct {
	config
	hooks    []Hook
	mutation *AssignmentSubmissionMutation
}

// Where appends a list predicates to the AssignmentSubmissionUpdate builder.
func (_u *AssignmentSubmissionUpdate) Where(ps ...predicate.AssignmentSubmission) *AssignmentSubmissionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLevelsCompleted sets the "levels_completed" field.
func (_u *AssignmentSubmissionUpdate) SetLevelsCompleted(v int) *AssignmentSubmissionUpdate {
	_u.mutation.ResetLevelsCompleted()
	_u.mutation.SetLevelsCompleted(v)
	return _u
}

// SetNillableLevelsCompleted sets the "levels_completed" field if the given value is not nil.
func (_u *AssignmentSubmissionUpdate) SetNillableLevelsCompleted(v *int) *AssignmentSubmissionUpdate {
	if v != nil {
		_u.SetLevelsCompleted(*v)
	}
	return _u
}

// AddLevelsCompleted adds value to the "levels_completed" field.
func (_u *AssignmentSubmissionUpdate) AddLevelsCompleted(v int) *AssignmentSubmissionUpdate {
	_u.mutation.AddLevelsCompleted(v)
	return _u
}

// SetTotalLevels sets the "total_levels" field.
func (_u *AssignmentSubmissionUpdate) SetTotalLevels(v int) *AssignmentSubmissionUpdate {
	_u.mutation.ResetTotalLevels()
	_u.mutation.SetTotalLevels(v)
	return _u
}

// SetNillableTotalLevels sets the "total_levels" field if the given value is not nil.
func (_u *AssignmentSubmissionUpdate) SetNillableTotalLevels(v *int) *AssignmentSubmissionUpdate {
	if v != nil {
		_u.SetTotalLevels(*v)
	}
	return _u
}

// AddTotalLevels adds value to the "total_levels" field.
func (_u *AssignmentSubmissionUpdate) AddTotalLevels(v int) *AssignmentSubmissionUpdate {
	_u.mutation.AddTotalLevels(v)
	return _u
}

// SetTotalStars sets the "total_stars" field.
func (_u *AssignmentSubmissionUpdate) SetTotalStars(v int) *AssignmentSubmissionUpdate {
	_u.mutation.ResetTotalStars()
	_u.mutation.SetTotalStars(v)
	return _u
}

// SetNillableTotalStars sets the "total_stars" field if the given value is not nil.
func (_u *AssignmentSubmissionUpdate) SetNillableTotalStars(v *int) *AssignmentSubmissionUpdate {
	if v != nil {
		_u.SetTotalStars(*v)
	}
	return _u
}

// AddTotalStars adds value to the "total_stars" field.
func (_u *AssignmentSubmissionUpdate) AddTotalStars(v int) *AssignmentSubmissionUpdate {
	_u.mutation.AddTotalStars(v)
	return _u
}

// SetGradePercentage sets the "grade_percentage" field.
func (_u *AssignmentSubmissionUpdate) SetGradePercentage(v float64) *AssignmentSubmissionUpdate {
	_u.mutation.ResetGradePercentage()
	_u.mutation.SetGradePercentage(v)
	return _u
}

// SetNillableGradePercentage sets the "grade_percentage" field if the given value is not nil.
func (_u *AssignmentSubmissionUpdate) SetNillableGradePercentage(v *float64) *AssignmentSubmissionUpdate {
	if v != nil {
		_u.SetGradePercentage(*v)
	}
	return _u
}

// AddGradePercentage adds value to the "grade_percentage" field.
func (_u *AssignmentSubmissionUpdate) AddGradePercentage(v float64) *AssignmentSubmissionUpdate {
	_u.mutation.AddGradePercentage(v)
	return _u
}

// ClearGradePercentage clears the value of the "grade_percentage" field.
func (_u *AssignmentSubmissionUpdate) ClearGradePercentage() *AssignmentSubmissionUpdate {
	_u.mutation.ClearGradePercentage()
	return _u
}

// SetManualGrade sets the "manual_grade" field.
func (_u *AssignmentSubmissionUpdate) SetManualGrade(v float64) *AssignmentSubmissionUpdate {
	_u.mutation.ResetManualGrade()
	_u.mutation.SetManualGrade(v)
	return _u
}

// SetNillableManualGrade sets the "manual_grade" field if the given value is not nil.
func (_u *AssignmentSubmissionUpdate) SetNillableManualGrade(v *float64) *AssignmentSubmissionUpdate {
	if v != nil {
		_u.SetManualGrade(*v)
	}
	return _u
}

// AddManualGrade adds value to the "manual_grade" field.
func (_u *AssignmentSubmissionUpdate) AddManualGrade(v float64) *AssignmentSubmissionUpdate {
	_u.mutation.AddManualGrade(v)
	return _u
}

// ClearManualGrade clears the value of the "manual_grade" field.
func (_u *AssignmentSubmissionUpdate) ClearManualGrade() *AssignmentSubmissionUpdate {
	_u.mutation.ClearManualGrade()
	return _u
}

// SetTeacherNotes sets the "teacher_notes" field.
func (_u *AssignmentSubmissionUpdate) SetTeacherNotes(v string) *AssignmentSubmissionUpdate {
	_u.mutation.SetTeacherNotes(v)
	return _u
}

// SetNillableTeacherNotes sets the "teacher_notes" field if the given value is not nil.
func (_u *AssignmentSubmissionUpdate) SetNillableTeacherNotes(v *string) *AssignmentSubmissionUpdate {
	if v != nil {
		_u.SetTeacherNotes(*v)
	}
	return _u
}

// ClearTeacherNotes clears the value of the "teacher_notes" field.
func (_u *AssignmentSubmissionUpdate) ClearTeacherNotes() *AssignmentSubmissionUpdate {
	_u.mutation.ClearTeacherNotes()
	return _u
}

// SetSubmittedAt sets the "submitted_at" field.
func (_u *AssignmentSubmissionUpdate) SetSubmittedAt(v time.Time) *AssignmentSubmissionUpdate {
	_u.mutation.SetSubmittedAt(v)
	return _u
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (_u *AssignmentSubmissionUpdate) SetNillableSubmittedAt(v *time.Time) *AssignmentSubmissionUpdate {
	if v != nil {
		_u.SetSubmittedAt(*v)
	}
	return _u
}

// ClearSubmittedAt clears the value of the "submitted_at" field.
func (_u *AssignmentSubmissionUpdate) ClearSubmittedAt() *AssignmentSubmissionUpdate {
	_u.mutation.ClearSubmittedAt()
	return _u
}

// SetGradedAt sets the "graded_at" field.
func (_u *AssignmentSubmissionUpdate) SetGradedAt(v time.Time) *AssignmentSubmissionUpdate {
	_u.mutation.SetGradedAt(v)
	return _u
}

// SetNillableGradedAt sets the "graded_at" field if the given value is not nil.
func (_u *AssignmentSubmissionUpdate) SetNillableGradedAt(v *time.Time) *AssignmentSubmissionUpdate {
	if v != nil {
		_u.SetGradedAt(*v)
	}
	return _u
}

// ClearGradedAt clears the value of the "graded_at" field.
func (_u *AssignmentSubmissionUpdate) ClearGradedAt() *AssignmentSubmissionUpdate {
	_u.mutation.ClearGradedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AssignmentSubmissionUpdate) SetUpdatedAt(v time.Time) *AssignmentSubmissionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAssignmentID sets the "assignment" edge to the Assignment entity by ID.
func (_u *AssignmentSubmissionUpdate) SetAssignmentID(id int) *AssignmentSubmissionUpdate {
	_u.mutation.SetAssignmentID(id)
	return _u
}

// SetAssignment sets the "assignment" edge to the Assignment entity.
func (_u *AssignmentSubmissionUpdate) SetAssignment(v *Assignment) *AssignmentSubmissionUpdate {
	return _u.SetAssignmentID(v.ID)
}

// SetStudentID sets the "student" edge to the User entity by ID.
func (_u *AssignmentSubmissionUpdate) SetStudentID(id int) *AssignmentSubmissionUpdate {
	_u.mutation.SetStudentID(id)
	return _u
}

// SetStudent sets the "student" edge to the User entity.
func (_u *AssignmentSubmissionUpdate) SetStudent(v *User) *AssignmentSubmissionUpdate {
	return _u.SetStudentID(v.ID)
}

// Mutation returns the AssignmentSubmissionMutation object of the builder.
func (_u *AssignmentSubmissionUpdate) Mutation() *AssignmentSubmissionMutation {
	return _u.mutation
}

// ClearAssignment clears the "assignment" edge to the Assignment entity.
func (_u *AssignmentSubmissionUpdate) ClearAssignment() *AssignmentSubmissionUpdate {
	_u.mutation.ClearAssignment()
	return _u
}

// ClearStudent clears the "student" edge to the User entity.
func (_u *AssignmentSubmissionUpdate) ClearStudent() *AssignmentSubmissionUpdate {
	_u.mutation.ClearStudent()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AssignmentSubmissionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AssignmentSubmissionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AssignmentSubmissionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AssignmentSubmissionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AssignmentSubmissionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := assignmentsubmission.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AssignmentSubmissionUpdate) check() error {
	if _u.mutation.AssignmentCleared() && len(_u.mutation.AssignmentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AssignmentSubmission.assignment"`)
	}
	if _u.mutation.StudentCleared() && len(_u.mutation.StudentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AssignmentSubmission.student"`)
	}
	return nil
}

func (_u *AssignmentSubmissionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(assignmentsubmission.Table, assignmentsubmission.Columns, sqlgraph.NewFieldSpec(assignmentsubmission.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.LevelsCompleted(); ok {
		_spec.SetField(assignmentsubmission.FieldLevelsCompleted, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLevelsCompleted(); ok {
		_spec.AddField(assignmentsubmission.FieldLevelsCompleted, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalLevels(); ok {
		_spec.SetField(assignmentsubmission.FieldTotalLevels, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalLevels(); ok {
		_spec.AddField(assignmentsubmission.FieldTotalLevels, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalStars(); ok {
		_spec.SetField(assignmentsubmission.FieldTotalStars, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalStars(); ok {
		_spec.AddField(assignmentsubmission.FieldTotalStars, field.TypeInt, value)
	}
	if value, ok := _u.mutation.GradePercentage(); ok {
		_spec.SetField(assignmentsubmission.FieldGradePercentage, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedGradePercentage(); ok {
		_spec.AddField(assignmentsubmission.FieldGradePercentage, field.TypeFloat64, value)
	}
	if _u.mutation.GradePercentageCleared() {
		_spec.ClearField(assignmentsubmission.FieldGradePercentage, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ManualGrade(); ok {
		_spec.SetField(assignmentsubmission.FieldManualGrade, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedManualGrade(); ok {
		_spec.AddField(assignmentsubmission.FieldManualGrade, field.TypeFloat64, value)
	}
	if _u.mutation.ManualGradeCleared() {
		_spec.ClearField(assignmentsubmission.FieldManualGrade, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TeacherNotes(); ok {
		_spec.SetField(assignmentsubmission.FieldTeacherNotes, field.TypeString, value)
	}
	if _u.mutation.TeacherNotesCleared() {
		_spec.ClearField(assignmentsubmission.FieldTeacherNotes, field.TypeString)
	}
	if value, ok := _u.mutation.SubmittedAt(); ok {
		_spec.SetField(assignmentsubmission.FieldSubmittedAt, field.TypeTime, value)
	}
	if _u.mutation.SubmittedAtCleared() {
		_spec.ClearField(assignmentsubmission.FieldSubmittedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.GradedAt(); ok {
		_spec.SetField(assignmentsubmission.FieldGradedAt, field.TypeTime, value)
	}
	if _u.mutation.GradedAtCleared() {
		_spec.ClearField(assignmentsubmission.FieldGradedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(assignmentsubmission.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AssignmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignmentsubmission.AssignmentTable,
			Columns: []string{assignmentsubmission.AssignmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assignment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssignmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignmentsubmission.AssignmentTable,
			Columns: []string{assignmentsubmission.AssignmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assignment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StudentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignmentsubmission.StudentTable,
			Columns: []string{assignmentsubmission.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StudentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignmentsubmission.StudentTable,
			Columns: []string{assignmentsubmission.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{assignmentsubmission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AssignmentSubmissionUpdateOne is the builder for updating a single AssignmentSubmission entity.
type AssignmentSubmissionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AssignmentSubmissionMutation
}

// SetLevelsCompleted sets the "levels_completed" field.
func (_u *AssignmentSubmissionUpdateOne) SetLevelsCompleted(v int) *AssignmentSubmissionUpdateOne {
	_u.mutation.ResetLevelsCompleted()
	_u.mutation.SetLevelsCompleted(v)
	return _u
}

// SetNillableLevelsCompleted sets the "levels_completed" field if the given value is not nil.
func (_u *AssignmentSubmissionUpdateOne) SetNillableLevelsCompleted(v *int) *AssignmentSubmissionUpdateOne {
	if v != nil {
		_u.SetLevelsCompleted(*v)
	}
	return _u
}

// AddLevelsCompleted adds value to the "levels_completed" field.
func (_u *AssignmentSubmissionUpdateOne) AddLevelsCompleted(v int) *AssignmentSubmissionUpdateOne {
	_u.mutation.AddLevelsCompleted(v)
	return _u
}

// SetTotalLevels sets the "total_levels" field.
func (_u *AssignmentSubmissionUpdateOne) SetTotalLevels(v int) *AssignmentSubmissionUpdateOne {
	_u.mutation.ResetTotalLevels()
	_u.mutation.SetTotalLevels(v)
	return _u
}

// SetNillableTotalLevels sets the "total_levels" field if the given value is not nil.
func (_u *AssignmentSubmissionUpdateOne) SetNillableTotalLevels(v *int) *AssignmentSubmissionUpdateOne {
	if v != nil {
		_u.SetTotalLevels(*v)
	}
	return _u
}

// AddTotalLevels adds value to the "total_levels" field.
func (_u *AssignmentSubmissionUpdateOne) AddTotalLevels(v int) *AssignmentSubmissionUpdateOne {
	_u.mutation.AddTotalLevels(v)
	return _u
}

// SetTotalStars sets the "total_stars" field.
func (_u *AssignmentSubmissionUpdateOne) SetTotalStars(v int) *AssignmentSubmissionUpdateOne {
	_u.mutation.ResetTotalStars()
	_u.mutation.SetTotalStars(v)
	return _u
}

// SetNillableTotalStars sets the "total_stars" field if the given value is not nil.
func (_u *AssignmentSubmissionUpdateOne) SetNillableTotalStars(v *int) *AssignmentSubmissionUpdateOne {
	if v != nil {
		_u.SetTotalStars(*v)
	}
	return _u
}

// AddTotalStars adds value to the "total_stars" field.
func (_u *AssignmentSubmissionUpdateOne) AddTotalStars(v int) *AssignmentSubmissionUpdateOne {
	_u.mutation.AddTotalStars(v)
	return _u
}

// SetGradePercentage sets the "grade_percentage" field.
func (_u *AssignmentSubmissionUpdateOne) SetGradePercentage(v float64) *AssignmentSubmissionUpdateOne {
	_u.mutation.ResetGradePercentage()
	_u.mutation.SetGradePercentage(v)
	return _u
}

// SetNillableGradePercentage sets the "grade_percentage" field if the given value is not nil.
func (_u *AssignmentSubmissionUpdateOne) SetNillableGradePercentage(v *float64) *AssignmentSubmissionUpdateOne {
	if v != nil {
		_u.SetGradePercentage(*v)
	}
	return _u
}

// AddGradePercentage adds value to the "grade_percentage" field.
func (_u *AssignmentSubmissionUpdateOne) AddGradePercentage(v float64) *AssignmentSubmissionUpdateOne {
	_u.mutation.AddGradePercentage(v)
	return _u
}

// ClearGradePercentage clears the value of the "grade_percentage" field.
func (_u *AssignmentSubmissionUpdateOne) ClearGradePercentage() *AssignmentSubmissionUpdateOne {
	_u.mutation.ClearGradePercentage()
	return _u
}

// SetManualGrade sets the "manual_grade" field.
func (_u *AssignmentSubmissionUpdateOne) SetManualGrade(v float64) *AssignmentSubmissionUpdateOne {
	_u.mutation.ResetManualGrade()
	_u.mutation.SetManualGrade(v)
	return _u
}

// SetNillableManualGrade sets the "manual_grade" field if the given value is not nil.
func (_u *AssignmentSubmissionUpdateOne) SetNillableManualGrade(v *float64) *AssignmentSubmissionUpdateOne {
	if v != nil {
		_u.SetManualGrade(*v)
	}
	return _u
}

// AddManualGrade adds value to the "manual_grade" field.
func (_u *AssignmentSubmissionUpdateOne) AddManualGrade(v float64) *AssignmentSubmissionUpdateOne {
	_u.mutation.AddManualGrade(v)
	return _u
}

// ClearManualGrade clears the value of the "manual_grade" field.
func (_u *AssignmentSubmissionUpdateOne) ClearManualGrade() *AssignmentSubmissionUpdateOne {
	_u.mutation.ClearManualGrade()
	return _u
}

// SetTeacherNotes sets the "teacher_notes" field.
func (_u *AssignmentSubmissionUpdateOne) SetTeacherNotes(v string) *AssignmentSubmissionUpdateOne {
	_u.mutation.SetTeacherNotes(v)
	return _u
}

// SetNillableTeacherNotes sets the "teacher_notes" field if the given value is not nil.
func (_u *AssignmentSubmissionUpdateOne) SetNillableTeacherNotes(v *string) *AssignmentSubmissionUpdateOne {
	if v != nil {
		_u.SetTeacherNotes(*v)
	}
	return _u
}

// ClearTeacherNotes clears the value of the "teacher_notes" field.
func (_u *AssignmentSubmissionUpdateOne) ClearTeacherNotes() *AssignmentSubmissionUpdateOne {
	_u.mutation.ClearTeacherNotes()
	return _u
}

// SetSubmittedAt sets the "submitted_at" field.
func (_u *AssignmentSubmissionUpdateOne) SetSubmittedAt(v time.Time) *AssignmentSubmissionUpdateOne {
	_u.mutation.SetSubmittedAt(v)
	return _u
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (_u *AssignmentSubmissionUpdateOne) SetNillableSubmittedAt(v *time.Time) *AssignmentSubmissionUpdateOne {
	if v != nil {
		_u.SetSubmittedAt(*v)
	}
	return _u
}

// ClearSubmittedAt clears the value of the "submitted_at" field.
func (_u *AssignmentSubmissionUpdateOne) ClearSubmittedAt() *AssignmentSubmissionUpdateOne {
	_u.mutation.ClearSubmittedAt()
	return _u
}

// SetGradedAt sets the "graded_at" field.
func (_u *AssignmentSubmissionUpdateOne) SetGradedAt(v time.Time) *AssignmentSubmissionUpdateOne {
	_u.mutation.SetGradedAt(v)
	return _u
}

// SetNillableGradedAt sets the "graded_at" field if the given value is not nil.
func (_u *AssignmentSubmissionUpdateOne) SetNillableGradedAt(v *time.Time) *AssignmentSubmissionUpdateOne {
	if v != nil {
		_u.SetGradedAt(*v)
	}
	return _u
}

// ClearGradedAt clears the value of the "graded_at" field.
func (_u *AssignmentSubmissionUpdateOne) ClearGradedAt() *AssignmentSubmissionUpdateOne {
	_u.mutation.ClearGradedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AssignmentSubmissionUpdateOne) SetUpdatedAt(v time.Time) *AssignmentSubmissionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAssignmentID sets the "assignment" edge to the Assignment entity by ID.
func (_u *AssignmentSubmissionUpdateOne) SetAssignmentID(id int) *AssignmentSubmissionUpdateOne {
	_u.mutation.SetAssignmentID(id)
	return _u
}

// SetAssignment sets the "assignment" edge to the Assignment entity.
func (_u *AssignmentSubmissionUpdateOne) SetAssignment(v *Assignment) *AssignmentSubmissionUpdateOne {
	return _u.SetAssignmentID(v.ID)
}

// SetStudentID sets the "student" edge to the User entity by ID.
func (_u *AssignmentSubmissionUpdateOne) SetStudentID(id int) *AssignmentSubmissionUpdateOne {
	_u.mutation.SetStudentID(id)
	return _u
}

// SetStudent sets the "student" edge to the User entity.
func (_u *AssignmentSubmissionUpdateOne) SetStudent(v *User) *AssignmentSubmissionUpdateOne {
	return _u.SetStudentID(v.ID)
}

// Mutation returns the AssignmentSubmissionMutation object of the builder.
func (_u *AssignmentSubmissionUpdateOne) Mutation() *AssignmentSubmissionMutation {
	return _u.mutation
}

// ClearAssignment clears the "assignment" edge to the Assignment entity.
func (_u *AssignmentSubmissionUpdateOne) ClearAssignment() *AssignmentSubmissionUpdateOne {
	_u.mutation.ClearAssignment()
	return _u
}

// ClearStudent clears the "student" edge to the User entity.
func (_u *AssignmentSubmissionUpdateOne) ClearStudent() *AssignmentSubmissionUpdateOne {
	_u.mutation.ClearStudent()
	return _u
}

// Where appends a list predicates to the AssignmentSubmissionUpdate builder.
func (_u *AssignmentSubmissionUpdateOne) Where(ps ...predicate.AssignmentSubmission) *AssignmentSubmissionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AssignmentSubmissionUpdateOne) Select(field string, fields ...string) *AssignmentSubmissionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AssignmentSubmission entity.
func (_u *AssignmentSubmissionUpdateOne) Save(ctx context.Context) (*AssignmentSubmission, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AssignmentSubmissionUpdateOne) SaveX(ctx context.Context) *AssignmentSubmission {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AssignmentSubmissionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AssignmentSubmissionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AssignmentSubmissionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := assignmentsubmission.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AssignmentSubmissionUpdateOne) check() error {
	if _u.mutation.AssignmentCleared() && len(_u.mutation.AssignmentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AssignmentSubmission.assignment"`)
	}
	if _u.mutation.StudentCleared() && len(_u.mutation.StudentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AssignmentSubmission.student"`)
	}
	return nil
}

func (_u *AssignmentSubmissionUpdateOne) sqlSave(ctx context.Context) (_node *AssignmentSubmission, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(assignmentsubmission.Table, assignmentsubmission.Columns, sqlgraph.NewFieldSpec(assignmentsubmission.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AssignmentSubmission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, assignmentsubmission.FieldID)
		for _, f := range fields {
			if !assignmentsubmission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != assignmentsubmission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.LevelsCompleted(); ok {
		_spec.SetField(assignmentsubmission.FieldLevelsCompleted, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLevelsCompleted(); ok {
		_spec.AddField(assignmentsubmission.FieldLevelsCompleted, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalLevels(); ok {
		_spec.SetField(assignmentsubmission.FieldTotalLevels, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalLevels(); ok {
		_spec.AddField(assignmentsubmission.FieldTotalLevels, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalStars(); ok {
		_spec.SetField(assignmentsubmission.FieldTotalStars, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalStars(); ok {
		_spec.AddField(assignmentsubmission.FieldTotalStars, field.TypeInt, value)
	}
	if value, ok := _u.mutation.GradePercentage(); ok {
		_spec.SetField(assignmentsubmission.FieldGradePercentage, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedGradePercentage(); ok {
		_spec.AddField(assignmentsubmission.FieldGradePercentage, field.TypeFloat64, value)
	}
	if _u.mutation.GradePercentageCleared() {
		_spec.ClearField(assignmentsubmission.FieldGradePercentage, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ManualGrade(); ok {
		_spec.SetField(assignmentsubmission.FieldManualGrade, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedManualGrade(); ok {
		_spec.AddField(assignmentsubmission.FieldManualGrade, field.TypeFloat64, value)
	}
	if _u.mutation.ManualGradeCleared() {
		_spec.ClearField(assignmentsubmission.FieldManualGrade, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TeacherNotes(); ok {
		_spec.SetField(assignmentsubmission.FieldTeacherNotes, field.TypeString, value)
	}
	if _u.mutation.TeacherNotesCleared() {
		_spec.ClearField(assignmentsubmission.FieldTeacherNotes, field.TypeString)
	}
	if value, ok := _u.mutation.SubmittedAt(); ok {
		_spec.SetField(assignmentsubmission.FieldSubmittedAt, field.TypeTime, value)
	}
	if _u.mutation.SubmittedAtCleared() {
		_spec.ClearField(assignmentsubmission.FieldSubmittedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.GradedAt(); ok {
		_spec.SetField(assignmentsubmission.FieldGradedAt, field.TypeTime, value)
	}
	if _u.mutation.GradedAtCleared() {
		_spec.ClearField(assignmentsubmission.FieldGradedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(assignmentsubmission.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AssignmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignmentsubmission.AssignmentTable,
			Columns: []string{assignmentsubmission.AssignmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assignment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssignmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignmentsubmission.AssignmentTable,
			Columns: []string{assignmentsubmission.AssignmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assignment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StudentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignmentsubmission.StudentTable,
			Columns: []string{assignmentsubmission.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StudentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignmentsubmission.StudentTable,
			Columns: []string{assignmentsubmission.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AssignmentSubmission{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{assignmentsubmission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
