// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"gigaboo.io/lem/internal/ent/app"
	"gigaboo.io/lem/internal/ent/battleroom"
	"gigaboo.io/lem/internal/ent/user"
)

// BattleRoom is the model entity for the BattleRoom schema.
type BattleRoom struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// RoomCode holds the value of the "room_code" field.
	RoomCode string `json:"room_code,omitempty"`
	// HostName holds the value of the "host_name" field.
	HostName string `json:"host_name,omitempty"`
	// GuestID holds the value of the "guest_id" field.
	GuestID *int `json:"guest_id,omitempty"`
	// GuestName holds the value of the "guest_name" field.
	GuestName string `json:"guest_name,omitempty"`
	// Status holds the value of the "status" field.
	Status battleroom.Status `json:"status,omitempty"`
	// Level holds the value of the "level" field.
	Level map[string]interface{} `json:"level,omitempty"`
	// HostCompleted holds the value of the "host_completed" field.
	HostCompleted bool `json:"host_completed,omitempty"`
	// HostCompletedAt holds the value of the "host_completed_at" field.
	HostCompletedAt *time.Time `json:"host_completed_at,omitempty"`
	// HostCode holds the value of the "host_code" field.
	HostCode string `json:"host_code,omitempty"`
	// GuestCompleted holds the value of the "guest_completed" field.
	GuestCompleted bool `json:"guest_completed,omitempty"`
	// GuestCompletedAt holds the value of the "guest_completed_at" field.
	GuestCompletedAt *time.Time `json:"guest_completed_at,omitempty"`
	// GuestCode holds the value of the "guest_code" field.
	GuestCode string `json:"guest_code,omitempty"`
	// WinnerID holds the value of the "winner_id" field.
	WinnerID *int `json:"winner_id,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BattleRoomQuery when eager-loading is set.
	Edges                    BattleRoomEdges `json:"edges"`
	app_battle_rooms         *int
	user_battle_rooms_hosted *int
	selectValues             sql.SelectValues
}

// BattleRoomEdges holds the relations/edges for other nodes in the graph.
type BattleRoomEdges struct {
	// App holds the value of the app edge.
	App *App `json:"app,omitempty"`
	// Host holds the value of the host edge.
	Host *User `json:"host,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AppOrErr returns the App value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BattleRoomEdges) AppOrErr() (*App, error) {
	if e.App != nil {
		return e.App, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: app.Label}
	}
	return nil, &NotLoadedError{edge: "app"}
}

// HostOrErr returns the Host value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BattleRoomEdges) HostOrErr() (*User, error) {
	if e.Host != nil {
		return e.Host, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "host"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BattleRoom) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case battleroom.FieldLevel:
			values[i] = new([]byte)
		case battleroom.FieldHostCompleted, battleroom.FieldGuestCompleted:
			values[i] = new(sql.NullBool)
		case battleroom.FieldID, battleroom.FieldGuestID, battleroom.FieldWinnerID:
			values[i] = new(sql.NullInt64)
		case battleroom.FieldRoomCode, battleroom.FieldHostName, battleroom.FieldGuestName, battleroom.FieldStatus, battleroom.FieldHostCode, battleroom.FieldGuestCode:
			values[i] = new(sql.NullString)
		case battleroom.FieldHostCompletedAt, battleroom.FieldGuestCompletedAt, battleroom.FieldStartedAt, battleroom.FieldExpiresAt, battleroom.FieldCreatedAt, battleroom.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case battleroom.ForeignKeys[0]: // app_battle_rooms
			values[i] = new(sql.NullInt64)
		case battleroom.ForeignKeys[1]: // user_battle_rooms_hosted
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BattleRoom fields.
func (_m *BattleRoom) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case battleroom.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case battleroom.FieldRoomCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field room_code", values[i])
			} else if value.Valid {
				_m.RoomCode = value.String
			}
		case battleroom.FieldHostName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field host_name", values[i])
			} else if value.Valid {
				_m.HostName = value.String
			}
		case battleroom.FieldGuestID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field guest_id", values[i])
			} else if value.Valid {
				_m.GuestID = new(int)
				*_m.GuestID = int(value.Int64)
			}
		case battleroom.FieldGuestName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field guest_name", values[i])
			} else if value.Valid {
				_m.GuestName = value.String
			}
		case battleroom.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = battleroom.Status(value.String)
			}
		case battleroom.FieldLevel:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field level", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Level); err != nil {
					return fmt.Errorf("unmarshal field level: %w", err)
				}
			}
		case battleroom.FieldHostCompleted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field host_completed", values[i])
			} else if value.Valid {
				_m.HostCompleted = value.Bool
			}
		case battleroom.FieldHostCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field host_completed_at", values[i])
			} else if value.Valid {
				_m.HostCompletedAt = new(time.Time)
				*_m.HostCompletedAt = value.Time
			}
		case battleroom.FieldHostCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field host_code", values[i])
			} else if value.Valid {
				_m.HostCode = value.String
			}
		case battleroom.FieldGuestCompleted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field guest_completed", values[i])
			} else if value.Valid {
				_m.GuestCompleted = value.Bool
			}
		case battleroom.FieldGuestCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field guest_completed_at", values[i])
			} else if value.Valid {
				_m.GuestCompletedAt = new(time.Time)
				*_m.GuestCompletedAt = value.Time
			}
		case battleroom.FieldGuestCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field guest_code", values[i])
			} else if value.Valid {
				_m.GuestCode = value.String
			}
		case battleroom.FieldWinnerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field winner_id", values[i])
			} else if value.Valid {
				_m.WinnerID = new(int)
				*_m.WinnerID = int(value.Int64)
			}
		case battleroom.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case battleroom.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case battleroom.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case battleroom.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case battleroom.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field app_battle_rooms", value)
			} else if value.Valid {
				_m.app_battle_rooms = new(int)
				*_m.app_battle_rooms = int(value.Int64)
			}
		case battleroom.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_battle_rooms_hosted", value)
			} else if value.Valid {
				_m.user_battle_rooms_hosted = new(int)
				*_m.user_battle_rooms_hosted = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BattleRoom.
// This includes values selected through modifiers, order, etc.
func (_m *BattleRoom) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryApp queries the "app" edge of the BattleRoom entity.
func (_m *BattleRoom) QueryApp() *AppQuery {
	return NewBattleRoomClient(_m.config).QueryApp(_m)
}

// QueryHost queries the "host" edge of the BattleRoom entity.
func (_m *BattleRoom) QueryHost() *UserQuery {
	return NewBattleRoomClient(_m.config).QueryHost(_m)
}

// Update returns a builder for updating this BattleRoom.
// Note that you need to call BattleRoom.Unwrap() before calling this method if this BattleRoom
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BattleRoom) Update() *BattleRoomUpdateOne {
	return NewBattleRoomClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BattleRoom entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BattleRoom) Unwrap() *BattleRoom {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BattleRoom is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BattleRoom) String() string {
	var builder strings.Builder
	builder.WriteString("BattleRoom(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("room_code=")
	builder.WriteString(_m.RoomCode)
	builder.WriteString(", ")
	builder.WriteString("host_name=")
	builder.WriteString(_m.HostName)
	builder.WriteString(", ")
	if v := _m.GuestID; v != nil {
		builder.WriteString("guest_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("guest_name=")
	builder.WriteString(_m.GuestName)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("level=")
	builder.WriteString(fmt.Sprintf("%v", _m.Level))
	builder.WriteString(", ")
	builder.WriteString("host_completed=")
	builder.WriteString(fmt.Sprintf("%v", _m.HostCompleted))
	builder.WriteString(", ")
	if v := _m.HostCompletedAt; v != nil {
		builder.WriteString("host_completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("host_code=")
	builder.WriteString(_m.HostCode)
	builder.WriteString(", ")
	builder.WriteString("guest_completed=")
	builder.WriteString(fmt.Sprintf("%v", _m.GuestCompleted))
	builder.WriteString(", ")
	if v := _m.GuestCompletedAt; v != nil {
		builder.WriteString("guest_completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("guest_code=")
	builder.WriteString(_m.GuestCode)
	builder.WriteString(", ")
	if v := _m.WinnerID; v != nil {
		builder.WriteString("winner_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BattleRooms is a parsable slice of BattleRoom.
type BattleRooms []*BattleRoom
