// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gigaboo.io/lem/internal/ent/app"
	"gigaboo.io/lem/internal/ent/assignment"
	"gigaboo.io/lem/internal/ent/classroom"
	"gigaboo.io/lem/internal/ent/classroommembership"
	"gigaboo.io/lem/internal/ent/classroomsession"
	"gigaboo.io/lem/internal/ent/livesession"
	"gigaboo.io/lem/internal/ent/user"
)

// ClassroomCreate is the builder for creating a Classroom entity.
type ClassroomCreate struct {
	config
	mutation *ClassroomMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *ClassroomCreate) SetName(v string) *ClassroomCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ClassroomCreate) SetDescription(v string) *ClassroomCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ClassroomCreate) SetNillableDescription(v *string) *ClassroomCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetJoinCode sets the "join_code" field.
func (_c *ClassroomCreate) SetJoinCode(v string) *ClassroomCreate {
	_c.mutation.SetJoinCode(v)
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *ClassroomCreate) SetIsActive(v bool) *ClassroomCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *ClassroomCreate) SetNillableIsActive(v *bool) *ClassroomCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetAllowJoin sets the "allow_join" field.
func (_c *ClassroomCreate) SetAllowJoin(v bool) *ClassroomCreate {
	_c.mutation.SetAllowJoin(v)
	return _c
}

// SetNillableAllowJoin sets the "allow_join" field if the given value is not nil.
func (_c *ClassroomCreate) SetNillableAllowJoin(v *bool) *ClassroomCreate {
	if v != nil {
		_c.SetAllowJoin(*v)
	}
	return _c
}

// SetActiveRoomCode sets the "active_room_code" field.
func (_c *ClassroomCreate) SetActiveRoomCode(v string) *ClassroomCreate {
	_c.mutation.SetActiveRoomCode(v)
	return _c
}

// SetNillableActiveRoomCode sets the "active_room_code" field if the given value is not nil.
func (_c *ClassroomCreate) SetNillableActiveRoomCode(v *string) *ClassroomCreate {
	if v != nil {
		_c.SetActiveRoomCode(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ClassroomCreate) SetCreatedAt(v time.Time) *ClassroomCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ClassroomCreate) SetNillableCreatedAt(v *time.Time) *ClassroomCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ClassroomCreate) SetUpdatedAt(v time.Time) *ClassroomCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ClassroomCreate) SetNillableUpdatedAt(v *time.Time) *ClassroomCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAppID sets the "app" edge to the App entity by ID.
func (_c *ClassroomCreate) SetAppID(id int) *ClassroomCreate {
	_c.mutation.SetAppID(id)
	return _c
}

// SetApp sets the "app" edge to the App entity.
func (_c *ClassroomCreate) SetApp(v *App) *ClassroomCreate {
	return _c.SetAppID(v.ID)
}

// SetTeacherID sets the "teacher" edge to the User entity by ID.
func (_c *ClassroomCreate) SetTeacherID(id int) *ClassroomCreate {
	_c.mutation.SetTeacherID(id)
	return _c
}

// SetTeacher sets the "teacher" edge to the User entity.
func (_c *ClassroomCreate) SetTeacher(v *User) *ClassroomCreate {
	return _c.SetTeacherID(v.ID)
}

// AddMembershipIDs adds the "memberships" edge to the ClassroomMembership entity by IDs.
func (_c *ClassroomCreate) AddMembershipIDs(ids ...int) *ClassroomCreate {
	_c.mutation.AddMembershipIDs(ids...)
	return _c
}

// AddMemberships adds the "memberships" edges to the ClassroomMembership entity.
func (_c *ClassroomCreate) AddMemberships(v ...*ClassroomMembership) *ClassroomCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMembershipIDs(ids...)
}

// AddAssignmentIDs adds the "assignments" edge to the Assignment entity by IDs.
func (_c *ClassroomCreate) AddAssignmentIDs(ids ...int) *ClassroomCreate {
	_c.mutation.AddAssignmentIDs(ids...)
	return _c
}

// AddAssignments adds the "assignments" edges to the Assignment entity.
func (_c *ClassroomCreate) AddAssignments(v ...*Assignment) *ClassroomCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAssignmentIDs(ids...)
}

// AddLiveSessionIDs adds the "live_sessions" edge to the LiveSession entity by IDs.
func (_c *ClassroomCreate) AddLiveSessionIDs(ids ...int) *ClassroomCreate {
	_c.mutation.AddLiveSessionIDs(ids...)
	return _c
}

// AddLiveSessions adds the "live_sessions" edges to the LiveSession entity.
func (_c *ClassroomCreate) AddLiveSessions(v ...*LiveSession) *ClassroomCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLiveSessionIDs(ids...)
}

// AddClassroomSessionIDs adds the "classroom_sessions" edge to the ClassroomSession entity by IDs.
func (_c *ClassroomCreate) AddClassroomSessionIDs(ids ...int) *ClassroomCreate {
	_c.mutation.AddClassroomSessionIDs(ids...)
	return _c
}

// AddClassroomSessions adds the "classroom_sessions" edges to the ClassroomSession entity.
func (_c *ClassroomCreate) AddClassroomSessions(v ...*ClassroomSession) *ClassroomCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddClassroomSessionIDs(ids...)
}

// Mutation returns the ClassroomMutation object of the builder.
func (_c *ClassroomCreate) Mutation() *ClassroomMutation {
	return _c.mutation
}

// Save creates the Classroom in the database.
func (_c *ClassroomCreate) Save(ctx context.Context) (*Classroom, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ClassroomCreate) SaveX(ctx context.Context) *Classroom {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ClassroomCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ClassroomCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ClassroomCreate) defaults() {
	if _, ok := _c.mutation.IsActive(); !ok {
		v := classroom.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.AllowJoin(); !ok {
		v := classroom.DefaultAllowJoin
		_c.mutation.SetAllowJoin(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := classroom.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := classroom.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ClassroomCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Classroom.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := classroom.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Classroom.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.JoinCode(); !ok {
		return &ValidationError{Name: "join_code", err: errors.New(`ent: missing required field "Classroom.join_code"`)}
	}
	if v, ok := _c.mutation.JoinCode(); ok {
		if err := classroom.JoinCodeValidator(v); err != nil {
			return &ValidationError{Name: "join_code", err: fmt.Errorf(`ent: validator failed for field "Classroom.join_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "Classroom.is_active"`)}
	}
	if _, ok := _c.mutation.AllowJoin(); !ok {
		return &ValidationError{Name: "allow_join", err: errors.New(`ent: missing required field "Classroom.allow_join"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Classroom.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Classroom.updated_at"`)}
	}
	if len(_c.mutation.AppIDs()) == 0 {
		return &ValidationError{Name: "app", err: errors.New(`ent: missing required edge "Classroom.app"`)}
	}
	if len(_c.mutation.TeacherIDs()) == 0 {
		return &ValidationError{Name: "teacher", err: errors.New(`ent: missing required edge "Classroom.teacher"`)}
	}
	return nil
}

func (_c *ClassroomCreate) sqlSave(ctx context.Context) (*Classroom, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ClassroomCreate) createSpec() (*Classroom, *sqlgraph.CreateSpec) {
	var (
		_node = &Classroom{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(classroom.Table, sqlgraph.NewFieldSpec(classroom.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(classroom.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(classroom.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.JoinCode(); ok {
		_spec.SetField(classroom.FieldJoinCode, field.TypeString, value)
		_node.JoinCode = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(classroom.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.AllowJoin(); ok {
		_spec.SetField(classroom.FieldAllowJoin, field.TypeBool, value)
		_node.AllowJoin = value
	}
	if value, ok := _c.mutation.ActiveRoomCode(); ok {
		_spec.SetField(classroom.FieldActiveRoomCode, field.TypeString, value)
		_node.ActiveRoomCode = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(classroom.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(classroom.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.AppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   classroom.AppTable,
			Columns: []string{classroom.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.app_classrooms = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TeacherIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   classroom.TeacherTable,
			Columns: []string{classroom.TeacherColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_classrooms_teaching = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   classroom.MembershipsTable,
			Columns: []string{classroom.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(classroommembership.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AssignmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   classroom.AssignmentsTable,
			Columns: []string{classroom.AssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assignment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LiveSessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   classroom.LiveSessionsTable,
			Columns: []string{classroom.LiveSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(livesession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ClassroomSessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   classroom.ClassroomSessionsTable,
			Columns: []string{classroom.ClassroomSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(classroomsession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ClassroomCreateBulk is the builder for creating many Classroom entities in bulk.
type ClassroomCreateBulk struct {
	config
	err      error
	builders []*ClassroomCreate
}

// Save creates the Classroom entities in the database.
func (_c *ClassroomCreateBulk) Save(ctx context.Context) ([]*Classroom, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Classroom, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ClassroomMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ClassroomCreateBulk) SaveX(ctx context.Context) []*Classroom {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ClassroomCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ClassroomCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
