// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gigaboo.io/lem/internal/ent/classroom"
	"gigaboo.io/lem/internal/ent/classroommembership"
	"gigaboo.io/lem/internal/ent/predicate"
	"gigaboo.io/lem/internal/ent/user"
)

// ClassroomMembershipUpdate is the builder for updating ClassroomMembership entities.
type ClassroomMembershipUpdate struct {
	config
	hooks    []Hook
	mutation *ClassroomMembershipMutation
}

// Where appends a list predicates to the ClassroomMembershipUpdate builder.
func (_u *ClassroomMembershipUpdate) Where(ps ...predicate.ClassroomMembership) *ClassroomMembershipUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ClassroomMembershipUpdate) SetStatus(v classroommembership.Status) *ClassroomMembershipUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ClassroomMembershipUpdate) SetNillableStatus(v *classroommembership.Status) *ClassroomMembershipUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetJoinedAt sets the "joined_at" field.
func (_u *ClassroomMembershipUpdate) SetJoinedAt(v time.Time) *ClassroomMembershipUpdate {
	_u.mutation.SetJoinedAt(v)
	return _u
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_u *ClassroomMembershipUpdate) SetNillableJoinedAt(v *time.Time) *ClassroomMembershipUpdate {
	if v != nil {
		_u.SetJoinedAt(*v)
	}
	return _u
}

// SetLeftAt sets the "left_at" field.
func (_u *ClassroomMembershipUpdate) SetLeftAt(v time.Time) *ClassroomMembershipUpdate {
	_u.mutation.SetLeftAt(v)
	return _u
}

// SetNillableLeftAt sets the "left_at" field if the given value is not nil.
func (_u *ClassroomMembershipUpdate) SetNillableLeftAt(v *time.Time) *ClassroomMembershipUpdate {
	if v != nil {
		_u.SetLeftAt(*v)
	}
	return _u
}

// ClearLeftAt clears the value of the "left_at" field.
func (_u *ClassroomMembershipUpdate) ClearLeftAt() *ClassroomMembershipUpdate {
	_u.mutation.ClearLeftAt()
	return _u
}

// SetClassroomID sets the "classroom" edge to the Classroom entity by ID.
func (_u *ClassroomMembershipUpdate) SetClassroomID(id int) *ClassroomMembershipUpdate {
	_u.mutation.SetClassroomID(id)
	return _u
}

// SetClassroom sets the "classroom" edge to the Classroom entity.
func (_u *ClassroomMembershipUpdate) SetClassroom(v *Classroom) *ClassroomMembershipUpdate {
	return _u.SetClassroomID(v.ID)
}

// SetStudentID sets the "student" edge to the User entity by ID.
func (_u *ClassroomMembershipUpdate) SetStudentID(id int) *ClassroomMembershipUpdate {
	_u.mutation.SetStudentID(id)
	return _u
}

// SetStudent sets the "student" edge to the User entity.
func (_u *ClassroomMembershipUpdate) SetStudent(v *User) *ClassroomMembershipUpdate {
	return _u.SetStudentID(v.ID)
}

// Mutation returns the ClassroomMembershipMutation object of the builder.
func (_u *ClassroomMembershipUpdate) Mutation() *ClassroomMembershipMutation {
	return _u.mutation
}

// ClearClassroom clears the "classroom" edge to the Classroom entity.
func (_u *ClassroomMembershipUpdate) ClearClassroom() *ClassroomMembershipUpdate {
	_u.mutation.ClearClassroom()
	return _u
}

// ClearStudent clears the "student" edge to the User entity.
func (_u *ClassroomMembershipUpdate) ClearStudent() *ClassroomMembershipUpdate {
	_u.mutation.ClearStudent()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ClassroomMembershipUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ClassroomMembershipUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ClassroomMembershipUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ClassroomMembershipUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ClassroomMembershipUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := classroommembership.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ClassroomMembership.status": %w`, err)}
		}
	}
	if _u.mutation.ClassroomCleared() && len(_u.mutation.ClassroomIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ClassroomMembership.classroom"`)
	}
	if _u.mutation.StudentCleared() && len(_u.mutation.StudentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ClassroomMembership.student"`)
	}
	return nil
}

func (_u *ClassroomMembershipUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(classroommembership.Table, classroommembership.Columns, sqlgraph.NewFieldSpec(classroommembership.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(classroommembership.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.JoinedAt(); ok {
		_spec.SetField(classroommembership.FieldJoinedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LeftAt(); ok {
		_spec.SetField(classroommembership.FieldLeftAt, field.TypeTime, value)
	}
	if _u.mutation.LeftAtCleared() {
		_spec.ClearField(classroommembership.FieldLeftAt, field.TypeTime)
	}
	if _u.mutation.ClassroomCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   classroommembership.ClassroomTable,
			Columns: []string{classroommembership.ClassroomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(classroom.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClassroomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   classroommembership.ClassroomTable,
			Columns: []string{classroommembership.ClassroomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(classroom.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StudentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   classroommembership.StudentTable,
			Columns: []string{classroommembership.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StudentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   classroommembership.StudentTable,
			Columns: []string{classroommembership.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{classroommembership.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ClassroomMembershipUpdateOne is the builder for updating a single ClassroomMembership entity.
type ClassroomMembershipUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ClassroomMembershipMutation
}

// SetStatus sets the "status" field.
func (_u *ClassroomMembershipUpdateOne) SetStatus(v classroommembership.Status) *ClassroomMembershipUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ClassroomMembershipUpdateOne) SetNillableStatus(v *classroommembership.Status) *ClassroomMembershipUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetJoinedAt sets the "joined_at" field.
func (_u *ClassroomMembershipUpdateOne) SetJoinedAt(v time.Time) *ClassroomMembershipUpdateOne {
	_u.mutation.SetJoinedAt(v)
	return _u
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_u *ClassroomMembershipUpdateOne) SetNillableJoinedAt(v *time.Time) *ClassroomMembershipUpdateOne {
	if v != nil {
		_u.SetJoinedAt(*v)
	}
	return _u
}

// SetLeftAt sets the "left_at" field.
func (_u *ClassroomMembershipUpdateOne) SetLeftAt(v time.Time) *ClassroomMembershipUpdateOne {
	_u.mutation.SetLeftAt(v)
	return _u
}

// SetNillableLeftAt sets the "left_at" field if the given value is not nil.
func (_u *ClassroomMembershipUpdateOne) SetNillableLeftAt(v *time.Time) *ClassroomMembershipUpdateOne {
	if v != nil {
		_u.SetLeftAt(*v)
	}
	return _u
}

// ClearLeftAt clears the value of the "left_at" field.
func (_u *ClassroomMembershipUpdateOne) ClearLeftAt() *ClassroomMembershipUpdateOne {
	_u.mutation.ClearLeftAt()
	return _u
}

// SetClassroomID sets the "classroom" edge to the Classroom entity by ID.
func (_u *ClassroomMembershipUpdateOne) SetClassroomID(id int) *ClassroomMembershipUpdateOne {
	_u.mutation.SetClassroomID(id)
	return _u
}

// SetClassroom sets the "classroom" edge to the Classroom entity.
func (_u *ClassroomMembershipUpdateOne) SetClassroom(v *Classroom) *ClassroomMembershipUpdateOne {
	return _u.SetClassroomID(v.ID)
}

// SetStudentID sets the "student" edge to the User entity by ID.
func (_u *ClassroomMembershipUpdateOne) SetStudentID(id int) *ClassroomMembershipUpdateOne {
	_u.mutation.SetStudentID(id)
	return _u
}

// SetStudent sets the "student" edge to the User entity.
func (_u *ClassroomMembershipUpdateOne) SetStudent(v *User) *ClassroomMembershipUpdateOne {
	return _u.SetStudentID(v.ID)
}

// Mutation returns the ClassroomMembershipMutation object of the builder.
func (_u *ClassroomMembershipUpdateOne) Mutation() *ClassroomMembershipMutation {
	return _u.mutation
}

// ClearClassroom clears the "classroom" edge to the Classroom entity.
func (_u *ClassroomMembershipUpdateOne) ClearClassroom() *ClassroomMembershipUpdateOne {
	_u.mutation.ClearClassroom()
	return _u
}

// ClearStudent clears the "student" edge to the User entity.
func (_u *ClassroomMembershipUpdateOne) ClearStudent() *ClassroomMembershipUpdateOne {
	_u.mutation.ClearStudent()
	return _u
}

// Where appends a list predicates to the ClassroomMembershipUpdate builder.
func (_u *ClassroomMembershipUpdateOne) Where(ps ...predicate.ClassroomMembership) *ClassroomMembershipUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ClassroomMembershipUpdateOne) Select(field string, fields ...string) *ClassroomMembershipUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ClassroomMembership entity.
func (_u *ClassroomMembershipUpdateOne) Save(ctx context.Context) (*ClassroomMembership, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ClassroomMembershipUpdateOne) SaveX(ctx context.Context) *ClassroomMembership {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ClassroomMembershipUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ClassroomMembershipUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ClassroomMembershipUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := classroommembership.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ClassroomMembership.status": %w`, err)}
		}
	}
	if _u.mutation.ClassroomCleared() && len(_u.mutation.ClassroomIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ClassroomMembership.classroom"`)
	}
	if _u.mutation.StudentCleared() && len(_u.mutation.StudentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ClassroomMembership.student"`)
	}
	return nil
}

func (_u *ClassroomMembershipUpdateOne) sqlSave(ctx context.Context) (_node *ClassroomMembership, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(classroommembership.Table, classroommembership.Columns, sqlgraph.NewFieldSpec(classroommembership.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ClassroomMembership.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, classroommembership.FieldID)
		for _, f := range fields {
			if !classroommembership.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != classroommembership.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(classroommembership.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.JoinedAt(); ok {
		_spec.SetField(classroommembership.FieldJoinedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LeftAt(); ok {
		_spec.SetField(classroommembership.FieldLeftAt, field.TypeTime, value)
	}
	if _u.mutation.LeftAtCleared() {
		_spec.ClearField(classroommembership.FieldLeftAt, field.TypeTime)
	}
	if _u.mutation.ClassroomCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   classroommembership.ClassroomTable,
			Columns: []string{classroommembership.ClassroomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(classroom.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClassroomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   classroommembership.ClassroomTable,
			Columns: []string{classroommembership.ClassroomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(classroom.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StudentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   classroommembership.StudentTable,
			Columns: []string{classroommembership.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StudentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   classroommembership.StudentTable,
			Columns: []string{classroommembership.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ClassroomMembership{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{classroommembership.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
