// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gigaboo.io/lem/internal/ent/app"
	"gigaboo.io/lem/internal/ent/emailtemplate"
)

// EmailTemplateCreate is the builder for creating a EmailTemplate entity.
type EmailTemplateCreate struct {
	config
	mutation *EmailTemplateMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *EmailTemplateCreate) SetName(v string) *EmailTemplateCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *EmailTemplateCreate) SetDescription(v string) *EmailTemplateCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *EmailTemplateCreate) SetNillableDescription(v *string) *EmailTemplateCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetSubject sets the "subject" field.
func (_c *EmailTemplateCreate) SetSubject(v string) *EmailTemplateCreate {
	_c.mutation.SetSubject(v)
	return _c
}

// SetBodyHTML sets the "body_html" field.
func (_c *EmailTemplateCreate) SetBodyHTML(v string) *EmailTemplateCreate {
	_c.mutation.SetBodyHTML(v)
	return _c
}

// SetNillableBodyHTML sets the "body_html" field if the given value is not nil.
func (_c *EmailTemplateCreate) SetNillableBodyHTML(v *string) *EmailTemplateCreate {
	if v != nil {
		_c.SetBodyHTML(*v)
	}
	return _c
}

// SetBodyText sets the "body_text" field.
func (_c *EmailTemplateCreate) SetBodyText(v string) *EmailTemplateCreate {
	_c.mutation.SetBodyText(v)
	return _c
}

// SetNillableBodyText sets the "body_text" field if the given value is not nil.
func (_c *EmailTemplateCreate) SetNillableBodyText(v *string) *EmailTemplateCreate {
	if v != nil {
		_c.SetBodyText(*v)
	}
	return _c
}

// SetVariables sets the "variables" field.
func (_c *EmailTemplateCreate) SetVariables(v []string) *EmailTemplateCreate {
	_c.mutation.SetVariables(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EmailTemplateCreate) SetCreatedAt(v time.Time) *EmailTemplateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EmailTemplateCreate) SetNillableCreatedAt(v *time.Time) *EmailTemplateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EmailTemplateCreate) SetUpdatedAt(v time.Time) *EmailTemplateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EmailTemplateCreate) SetNillableUpdatedAt(v *time.Time) *EmailTemplateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAppID sets the "app" edge to the App entity by ID.
func (_c *EmailTemplateCreate) SetAppID(id int) *EmailTemplateCreate {
	_c.mutation.SetAppID(id)
	return _c
}

// SetApp sets the "app" edge to the App entity.
func (_c *EmailTemplateCreate) SetApp(v *App) *EmailTemplateCreate {
	return _c.SetAppID(v.ID)
}

// Mutation returns the EmailTemplateMutation object of the builder.
func (_c *EmailTemplateCreate) Mutation() *EmailTemplateMutation {
	return _c.mutation
}

// Save creates the EmailTemplate in the database.
func (_c *EmailTemplateCreate) Save(ctx context.Context) (*EmailTemplate, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EmailTemplateCreate) SaveX(ctx context.Context) *EmailTemplate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmailTemplateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmailTemplateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EmailTemplateCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := emailtemplate.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := emailtemplate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EmailTemplateCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "EmailTemplate.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := emailtemplate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "EmailTemplate.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "EmailTemplate.subject"`)}
	}
	if v, ok := _c.mutation.Subject(); ok {
		if err := emailtemplate.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "EmailTemplate.subject": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EmailTemplate.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EmailTemplate.updated_at"`)}
	}
	if len(_c.mutation.AppIDs()) == 0 {
		return &ValidationError{Name: "app", err: errors.New(`ent: missing required edge "EmailTemplate.app"`)}
	}
	return nil
}

func (_c *EmailTemplateCreate) sqlSave(ctx context.Context) (*EmailTemplate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EmailTemplateCreate) createSpec() (*EmailTemplate, *sqlgraph.CreateSpec) {
	var (
		_node = &EmailTemplate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(emailtemplate.Table, sqlgraph.NewFieldSpec(emailtemplate.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(emailtemplate.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(emailtemplate.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Subject(); ok {
		_spec.SetField(emailtemplate.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := _c.mutation.BodyHTML(); ok {
		_spec.SetField(emailtemplate.FieldBodyHTML, field.TypeString, value)
		_node.BodyHTML = value
	}
	if value, ok := _c.mutation.BodyText(); ok {
		_spec.SetField(emailtemplate.FieldBodyText, field.TypeString, value)
		_node.BodyText = value
	}
	if value, ok := _c.mutation.Variables(); ok {
		_spec.SetField(emailtemplate.FieldVariables, field.TypeJSON, value)
		_node.Variables = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(emailtemplate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(emailtemplate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.AppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   emailtemplate.AppTable,
			Columns: []string{emailtemplate.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.app_email_templates = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EmailTemplateCreateBulk is the builder for creating many EmailTemplate entities in bulk.
type EmailTemplateCreateBulk struct {
	config
	err      error
	builders []*EmailTemplateCreate
}

// Save creates the EmailTemplate entities in the database.
func (_c *EmailTemplateCreateBulk) Save(ctx context.Context) ([]*EmailTemplate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EmailTemplate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EmailTemplateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EmailTemplateCreateBulk) SaveX(ctx context.Context) []*EmailTemplate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmailTemplateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmailTemplateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
