// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gigaboo.io/lem/internal/ent/app"
	"gigaboo.io/lem/internal/ent/classroom"
	"gigaboo.io/lem/internal/ent/livesession"
	"gigaboo.io/lem/internal/ent/livesessionstudent"
	"gigaboo.io/lem/internal/ent/predicate"
	"gigaboo.io/lem/internal/ent/user"
)

// LiveSessionUpdate is the builder for updating LiveSession entities.
type LiveSessionUpdate struct {
	config
	hooks    []Hook
	mutation *LiveSessionMutation
}

// Where appends a list predicates to the LiveSessionUpdate builder.
func (_u *LiveSessionUpdate) Where(ps ...predicate.LiveSession) *LiveSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRoomCode sets the "room_code" field.
func (_u *LiveSessionUpdate) SetRoomCode(v string) *LiveSessionUpdate {
	_u.mutation.SetRoomCode(v)
	return _u
}

// SetNillableRoomCode sets the "room_code" field if the given value is not nil.
func (_u *LiveSessionUpdate) SetNillableRoomCode(v *string) *LiveSessionUpdate {
	if v != nil {
		_u.SetRoomCode(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *LiveSessionUpdate) SetStatus(v livesession.Status) *LiveSessionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *LiveSessionUpdate) SetNillableStatus(v *livesession.Status) *LiveSessionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLevel sets the "level" field.
func (_u *LiveSessionUpdate) SetLevel(v map[string]interface{}) *LiveSessionUpdate {
	_u.mutation.SetLevel(v)
	return _u
}

// ClearLevel clears the value of the "level" field.
func (_u *LiveSessionUpdate) ClearLevel() *LiveSessionUpdate {
	_u.mutation.ClearLevel()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *LiveSessionUpdate) SetStartedAt(v time.Time) *LiveSessionUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *LiveSessionUpdate) SetNillableStartedAt(v *time.Time) *LiveSessionUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *LiveSessionUpdate) ClearStartedAt() *LiveSessionUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *LiveSessionUpdate) SetEndedAt(v time.Time) *LiveSessionUpdate {
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *LiveSessionUpdate) SetNillableEndedAt(v *time.Time) *LiveSessionUpdate {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (_u *LiveSessionUpdate) ClearEndedAt() *LiveSessionUpdate {
	_u.mutation.ClearEndedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *LiveSessionUpdate) SetExpiresAt(v time.Time) *LiveSessionUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *LiveSessionUpdate) SetNillableExpiresAt(v *time.Time) *LiveSessionUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LiveSessionUpdate) SetUpdatedAt(v time.Time) *LiveSessionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAppID sets the "app" edge to the App entity by ID.
func (_u *LiveSessionUpdate) SetAppID(id int) *LiveSessionUpdate {
	_u.mutation.SetAppID(id)
	return _u
}

// SetApp sets the "app" edge to the App entity.
func (_u *LiveSessionUpdate) SetApp(v *App) *LiveSessionUpdate {
	return _u.SetAppID(v.ID)
}

// SetClassroomID sets the "classroom" edge to the Classroom entity by ID.
func (_u *LiveSessionUpdate) SetClassroomID(id int) *LiveSessionUpdate {
	_u.mutation.SetClassroomID(id)
	return _u
}

// SetClassroom sets the "classroom" edge to the Classroom entity.
func (_u *LiveSessionUpdate) SetClassroom(v *Classroom) *LiveSessionUpdate {
	return _u.SetClassroomID(v.ID)
}

// SetTeacherID sets the "teacher" edge to the User entity by ID.
func (_u *LiveSessionUpdate) SetTeacherID(id int) *LiveSessionUpdate {
	_u.mutation.SetTeacherID(id)
	return _u
}

// SetTeacher sets the "teacher" edge to the User entity.
func (_u *LiveSessionUpdate) SetTeacher(v *User) *LiveSessionUpdate {
	return _u.SetTeacherID(v.ID)
}

// AddStudentIDs adds the "students" edge to the LiveSessionStudent entity by IDs.
func (_u *LiveSessionUpdate) AddStudentIDs(ids ...int) *LiveSessionUpdate {
	_u.mutation.AddStudentIDs(ids...)
	return _u
}

// AddStudents adds the "students" edges to the LiveSessionStudent entity.
func (_u *LiveSessionUpdate) AddStudents(v ...*LiveSessionStudent) *LiveSessionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStudentIDs(ids...)
}

// Mutation returns the LiveSessionMutation object of the builder.
func (_u *LiveSessionUpdate) Mutation() *LiveSessionMutation {
	return _u.mutation
}

// ClearApp clears the "app" edge to the App entity.
func (_u *LiveSessionUpdate) ClearApp() *LiveSessionUpdate {
	_u.mutation.ClearApp()
	return _u
}

// ClearClassroom clears the "classroom" edge to the Classroom entity.
func (_u *LiveSessionUpdate) ClearClassroom() *LiveSessionUpdate {
	_u.mutation.ClearClassroom()
	return _u
}

// ClearTeacher clears the "teacher" edge to the User entity.
func (_u *LiveSessionUpdate) ClearTeacher() *LiveSessionUpdate {
	_u.mutation.ClearTeacher()
	return _u
}

// ClearStudents clears all "students" edges to the LiveSessionStudent entity.
func (_u *LiveSessionUpdate) ClearStudents() *LiveSessionUpdate {
	_u.mutation.ClearStudents()
	return _u
}

// RemoveStudentIDs removes the "students" edge to LiveSessionStudent entities by IDs.
func (_u *LiveSessionUpdate) RemoveStudentIDs(ids ...int) *LiveSessionUpdate {
	_u.mutation.RemoveStudentIDs(ids...)
	return _u
}

// RemoveStudents removes "students" edges to LiveSessionStudent entities.
func (_u *LiveSessionUpdate) RemoveStudents(v ...*LiveSessionStudent) *LiveSessionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStudentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LiveSessionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LiveSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LiveSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LiveSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LiveSessionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := livesession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LiveSessionUpdate) check() error {
	if v, ok := _u.mutation.RoomCode(); ok {
		if err := livesession.RoomCodeValidator(v); err != nil {
			return &ValidationError{Name: "room_code", err: fmt.Errorf(`ent: validator failed for field "LiveSession.room_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := livesession.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "LiveSession.status": %w`, err)}
		}
	}
	if _u.mutation.AppCleared() && len(_u.mutation.AppIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LiveSession.app"`)
	}
	if _u.mutation.ClassroomCleared() && len(_u.mutation.ClassroomIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LiveSession.classroom"`)
	}
	if _u.mutation.TeacherCleared() && len(_u.mutation.TeacherIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LiveSession.teacher"`)
	}
	return nil
}

func (_u *LiveSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(livesession.Table, livesession.Columns, sqlgraph.NewFieldSpec(livesession.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RoomCode(); ok {
		_spec.SetField(livesession.FieldRoomCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(livesession.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(livesession.FieldLevel, field.TypeJSON, value)
	}
	if _u.mutation.LevelCleared() {
		_spec.ClearField(livesession.FieldLevel, field.TypeJSON)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(livesession.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(livesession.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(livesession.FieldEndedAt, field.TypeTime, value)
	}
	if _u.mutation.EndedAtCleared() {
		_spec.ClearField(livesession.FieldEndedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(livesession.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(livesession.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AppCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   livesession.AppTable,
			Columns: []string{livesession.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   livesession.AppTable,
			Columns: []string{livesession.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClassroomCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   livesession.ClassroomTable,
			Columns: []string{livesession.ClassroomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(classroom.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClassroomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   livesession.ClassroomTable,
			Columns: []string{livesession.ClassroomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(classroom.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeacherCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   livesession.TeacherTable,
			Columns: []string{livesession.TeacherColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeacherIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   livesession.TeacherTable,
			Columns: []string{livesession.TeacherColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StudentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   livesession.StudentsTable,
			Columns: []string{livesession.StudentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(livesessionstudent.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStudentsIDs(); len(nodes) > 0 && !_u.mutation.StudentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   livesession.StudentsTable,
			Columns: []string{livesession.StudentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(livesessionstudent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StudentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   livesession.StudentsTable,
			Columns: []string{livesession.StudentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(livesessionstudent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{livesession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LiveSessionUpdateOne is the builder for updating a single LiveSession entity.
type LiveSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LiveSessionMutation
}

// SetRoomCode sets the "room_code" field.
func (_u *LiveSessionUpdateOne) SetRoomCode(v string) *LiveSessionUpdateOne {
	_u.mutation.SetRoomCode(v)
	return _u
}

// SetNillableRoomCode sets the "room_code" field if the given value is not nil.
func (_u *LiveSessionUpdateOne) SetNillableRoomCode(v *string) *LiveSessionUpdateOne {
	if v != nil {
		_u.SetRoomCode(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *LiveSessionUpdateOne) SetStatus(v livesession.Status) *LiveSessionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *LiveSessionUpdateOne) SetNillableStatus(v *livesession.Status) *LiveSessionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLevel sets the "level" field.
func (_u *LiveSessionUpdateOne) SetLevel(v map[string]interface{}) *LiveSessionUpdateOne {
	_u.mutation.SetLevel(v)
	return _u
}

// ClearLevel clears the value of the "level" field.
func (_u *LiveSessionUpdateOne) ClearLevel() *LiveSessionUpdateOne {
	_u.mutation.ClearLevel()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *LiveSessionUpdateOne) SetStartedAt(v time.Time) *LiveSessionUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *LiveSessionUpdateOne) SetNillableStartedAt(v *time.Time) *LiveSessionUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *LiveSessionUpdateOne) ClearStartedAt() *LiveSessionUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *LiveSessionUpdateOne) SetEndedAt(v time.Time) *LiveSessionUpdateOne {
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *LiveSessionUpdateOne) SetNillableEndedAt(v *time.Time) *LiveSessionUpdateOne {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (_u *LiveSessionUpdateOne) ClearEndedAt() *LiveSessionUpdateOne {
	_u.mutation.ClearEndedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *LiveSessionUpdateOne) SetExpiresAt(v time.Time) *LiveSessionUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *LiveSessionUpdateOne) SetNillableExpiresAt(v *time.Time) *LiveSessionUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LiveSessionUpdateOne) SetUpdatedAt(v time.Time) *LiveSessionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAppID sets the "app" edge to the App entity by ID.
func (_u *LiveSessionUpdateOne) SetAppID(id int) *LiveSessionUpdateOne {
	_u.mutation.SetAppID(id)
	return _u
}

// SetApp sets the "app" edge to the App entity.
func (_u *LiveSessionUpdateOne) SetApp(v *App) *LiveSessionUpdateOne {
	return _u.SetAppID(v.ID)
}

// SetClassroomID sets the "classroom" edge to the Classroom entity by ID.
func (_u *LiveSessionUpdateOne) SetClassroomID(id int) *LiveSessionUpdateOne {
	_u.mutation.SetClassroomID(id)
	return _u
}

// SetClassroom sets the "classroom" edge to the Classroom entity.
func (_u *LiveSessionUpdateOne) SetClassroom(v *Classroom) *LiveSessionUpdateOne {
	return _u.SetClassroomID(v.ID)
}

// SetTeacherID sets the "teacher" edge to the User entity by ID.
func (_u *LiveSessionUpdateOne) SetTeacherID(id int) *LiveSessionUpdateOne {
	_u.mutation.SetTeacherID(id)
	return _u
}

// SetTeacher sets the "teacher" edge to the User entity.
func (_u *LiveSessionUpdateOne) SetTeacher(v *User) *LiveSessionUpdateOne {
	return _u.SetTeacherID(v.ID)
}

// AddStudentIDs adds the "students" edge to the LiveSessionStudent entity by IDs.
func (_u *LiveSessionUpdateOne) AddStudentIDs(ids ...int) *LiveSessionUpdateOne {
	_u.mutation.AddStudentIDs(ids...)
	return _u
}

// AddStudents adds the "students" edges to the LiveSessionStudent entity.
func (_u *LiveSessionUpdateOne) AddStudents(v ...*LiveSessionStudent) *LiveSessionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStudentIDs(ids...)
}

// Mutation returns the LiveSessionMutation object of the builder.
func (_u *LiveSessionUpdateOne) Mutation() *LiveSessionMutation {
	return _u.mutation
}

// ClearApp clears the "app" edge to the App entity.
func (_u *LiveSessionUpdateOne) ClearApp() *LiveSessionUpdateOne {
	_u.mutation.ClearApp()
	return _u
}

// ClearClassroom clears the "classroom" edge to the Classroom entity.
func (_u *LiveSessionUpdateOne) ClearClassroom() *LiveSessionUpdateOne {
	_u.mutation.ClearClassroom()
	return _u
}

// ClearTeacher clears the "teacher" edge to the User entity.
func (_u *LiveSessionUpdateOne) ClearTeacher() *LiveSessionUpdateOne {
	_u.mutation.ClearTeacher()
	return _u
}

// ClearStudents clears all "students" edges to the LiveSessionStudent entity.
func (_u *LiveSessionUpdateOne) ClearStudents() *LiveSessionUpdateOne {
	_u.mutation.ClearStudents()
	return _u
}

// RemoveStudentIDs removes the "students" edge to LiveSessionStudent entities by IDs.
func (_u *LiveSessionUpdateOne) RemoveStudentIDs(ids ...int) *LiveSessionUpdateOne {
	_u.mutation.RemoveStudentIDs(ids...)
	return _u
}

// RemoveStudents removes "students" edges to LiveSessionStudent entities.
func (_u *LiveSessionUpdateOne) RemoveStudents(v ...*LiveSessionStudent) *LiveSessionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStudentIDs(ids...)
}

// Where appends a list predicates to the LiveSessionUpdate builder.
func (_u *LiveSessionUpdateOne) Where(ps ...predicate.LiveSession) *LiveSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LiveSessionUpdateOne) Select(field string, fields ...string) *LiveSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LiveSession entity.
func (_u *LiveSessionUpdateOne) Save(ctx context.Context) (*LiveSession, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LiveSessionUpdateOne) SaveX(ctx context.Context) *LiveSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LiveSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LiveSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LiveSessionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := livesession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LiveSessionUpdateOne) check() error {
	if v, ok := _u.mutation.RoomCode(); ok {
		if err := livesession.RoomCodeValidator(v); err != nil {
			return &ValidationError{Name: "room_code", err: fmt.Errorf(`ent: validator failed for field "LiveSession.room_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := livesession.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "LiveSession.status": %w`, err)}
		}
	}
	if _u.mutation.AppCleared() && len(_u.mutation.AppIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LiveSession.app"`)
	}
	if _u.mutation.ClassroomCleared() && len(_u.mutation.ClassroomIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LiveSession.classroom"`)
	}
	if _u.mutation.TeacherCleared() && len(_u.mutation.TeacherIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LiveSession.teacher"`)
	}
	return nil
}

func (_u *LiveSessionUpdateOne) sqlSave(ctx context.Context) (_node *LiveSession, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(livesession.Table, livesession.Columns, sqlgraph.NewFieldSpec(livesession.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LiveSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, livesession.FieldID)
		for _, f := range fields {
			if !livesession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != livesession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RoomCode(); ok {
		_spec.SetField(livesession.FieldRoomCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(livesession.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(livesession.FieldLevel, field.TypeJSON, value)
	}
	if _u.mutation.LevelCleared() {
		_spec.ClearField(livesession.FieldLevel, field.TypeJSON)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(livesession.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(livesession.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(livesession.FieldEndedAt, field.TypeTime, value)
	}
	if _u.mutation.EndedAtCleared() {
		_spec.ClearField(livesession.FieldEndedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(livesession.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(livesession.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AppCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   livesession.AppTable,
			Columns: []string{livesession.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   livesession.AppTable,
			Columns: []string{livesession.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClassroomCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   livesession.ClassroomTable,
			Columns: []string{livesession.ClassroomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(classroom.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClassroomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   livesession.ClassroomTable,
			Columns: []string{livesession.ClassroomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(classroom.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeacherCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   livesession.TeacherTable,
			Columns: []string{livesession.TeacherColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeacherIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   livesession.TeacherTable,
			Columns: []string{livesession.TeacherColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StudentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   livesession.StudentsTable,
			Columns: []string{livesession.StudentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(livesessionstudent.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStudentsIDs(); len(nodes) > 0 && !_u.mutation.StudentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   livesession.StudentsTable,
			Columns: []string{livesession.StudentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(livesessionstudent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StudentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   livesession.StudentsTable,
			Columns: []string{livesession.StudentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(livesessionstudent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &LiveSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{livesession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
