// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gigaboo.io/lem/internal/ent/livesession"
	"gigaboo.io/lem/internal/ent/livesessionstudent"
	"gigaboo.io/lem/internal/ent/user"
)

// LiveSessionStudentCreate is the builder for creating a LiveSessionStudent entity.
type LiveSessionStudentCreate struct {
	config
	mutation *LiveSessionStudentMutation
	hooks    []Hook
}

// SetStudentName sets the "student_name" field.
func (_c *LiveSessionStudentCreate) SetStudentName(v string) *LiveSessionStudentCreate {
	_c.mutation.SetStudentName(v)
	return _c
}

// SetNillableStudentName sets the "student_name" field if the given value is not nil.
func (_c *LiveSessionStudentCreate) SetNillableStudentName(v *string) *LiveSessionStudentCreate {
	if v != nil {
		_c.SetStudentName(*v)
	}
	return _c
}

// SetStarsCollected sets the "stars_collected" field.
func (_c *LiveSessionStudentCreate) SetStarsCollected(v int) *LiveSessionStudentCreate {
	_c.mutation.SetStarsCollected(v)
	return _c
}

// SetNillableStarsCollected sets the "stars_collected" field if the given value is not nil.
func (_c *LiveSessionStudentCreate) SetNillableStarsCollected(v *int) *LiveSessionStudentCreate {
	if v != nil {
		_c.SetStarsCollected(*v)
	}
	return _c
}

// SetCompleted sets the "completed" field.
func (_c *LiveSessionStudentCreate) SetCompleted(v bool) *LiveSessionStudentCreate {
	_c.mutation.SetCompleted(v)
	return _c
}

// SetNillableCompleted sets the "completed" field if the given value is not nil.
func (_c *LiveSessionStudentCreate) SetNillableCompleted(v *bool) *LiveSessionStudentCreate {
	if v != nil {
		_c.SetCompleted(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *LiveSessionStudentCreate) SetCompletedAt(v time.Time) *LiveSessionStudentCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *LiveSessionStudentCreate) SetNillableCompletedAt(v *time.Time) *LiveSessionStudentCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetCode sets the "code" field.
func (_c *LiveSessionStudentCreate) SetCode(v string) *LiveSessionStudentCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_c *LiveSessionStudentCreate) SetNillableCode(v *string) *LiveSessionStudentCreate {
	if v != nil {
		_c.SetCode(*v)
	}
	return _c
}

// SetJoinedAt sets the "joined_at" field.
func (_c *LiveSessionStudentCreate) SetJoinedAt(v time.Time) *LiveSessionStudentCreate {
	_c.mutation.SetJoinedAt(v)
	return _c
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_c *LiveSessionStudentCreate) SetNillableJoinedAt(v *time.Time) *LiveSessionStudentCreate {
	if v != nil {
		_c.SetJoinedAt(*v)
	}
	return _c
}

// SetLeftAt sets the "left_at" field.
func (_c *LiveSessionStudentCreate) SetLeftAt(v time.Time) *LiveSessionStudentCreate {
	_c.mutation.SetLeftAt(v)
	return _c
}

// SetNillableLeftAt sets the "left_at" field if the given value is not nil.
func (_c *LiveSessionStudentCreate) SetNillableLeftAt(v *time.Time) *LiveSessionStudentCreate {
	if v != nil {
		_c.SetLeftAt(*v)
	}
	return _c
}

// SetLastUpdatedAt sets the "last_updated_at" field.
func (_c *LiveSessionStudentCreate) SetLastUpdatedAt(v time.Time) *LiveSessionStudentCreate {
	_c.mutation.SetLastUpdatedAt(v)
	return _c
}

// SetNillableLastUpdatedAt sets the "last_updated_at" field if the given value is not nil.
func (_c *LiveSessionStudentCreate) SetNillableLastUpdatedAt(v *time.Time) *LiveSessionStudentCreate {
	if v != nil {
		_c.SetLastUpdatedAt(*v)
	}
	return _c
}

// SetSessionID sets the "session" edge to the LiveSession entity by ID.
func (_c *LiveSessionStudentCreate) SetSessionID(id int) *LiveSessionStudentCreate {
	_c.mutation.SetSessionID(id)
	return _c
}

// SetSession sets the "session" edge to the LiveSession entity.
func (_c *LiveSessionStudentCreate) SetSession(v *LiveSession) *LiveSessionStudentCreate {
	return _c.SetSessionID(v.ID)
}

// SetStudentID sets the "student" edge to the User entity by ID.
func (_c *LiveSessionStudentCreate) SetStudentID(id int) *LiveSessionStudentCreate {
	_c.mutation.SetStudentID(id)
	return _c
}

// SetStudent sets the "student" edge to the User entity.
func (_c *LiveSessionStudentCreate) SetStudent(v *User) *LiveSessionStudentCreate {
	return _c.SetStudentID(v.ID)
}

// Mutation returns the LiveSessionStudentMutation object of the builder.
func (_c *LiveSessionStudentCreate) Mutation() *LiveSessionStudentMutation {
	return _c.mutation
}

// Save creates the LiveSessionStudent in the database.
func (_c *LiveSessionStudentCreate) Save(ctx context.Context) (*LiveSessionStudent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LiveSessionStudentCreate) SaveX(ctx context.Context) *LiveSessionStudent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LiveSessionStudentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LiveSessionStudentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LiveSessionStudentCreate) defaults() {
	if _, ok := _c.mutation.StarsCollected(); !ok {
		v := livesessionstudent.DefaultStarsCollected
		_c.mutation.SetStarsCollected(v)
	}
	if _, ok := _c.mutation.Completed(); !ok {
		v := livesessionstudent.DefaultCompleted
		_c.mutation.SetCompleted(v)
	}
	if _, ok := _c.mutation.JoinedAt(); !ok {
		v := livesessionstudent.DefaultJoinedAt()
		_c.mutation.SetJoinedAt(v)
	}
	if _, ok := _c.mutation.LastUpdatedAt(); !ok {
		v := livesessionstudent.DefaultLastUpdatedAt()
		_c.mutation.SetLastUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LiveSessionStudentCreate) check() error {
	if _, ok := _c.mutation.StarsCollected(); !ok {
		return &ValidationError{Name: "stars_collected", err: errors.New(`ent: missing required field "LiveSessionStudent.stars_collected"`)}
	}
	if _, ok := _c.mutation.Completed(); !ok {
		return &ValidationError{Name: "completed", err: errors.New(`ent: missing required field "LiveSessionStudent.completed"`)}
	}
	if _, ok := _c.mutation.JoinedAt(); !ok {
		return &ValidationError{Name: "joined_at", err: errors.New(`ent: missing required field "LiveSessionStudent.joined_at"`)}
	}
	if _, ok := _c.mutation.LastUpdatedAt(); !ok {
		return &ValidationError{Name: "last_updated_at", err: errors.New(`ent: missing required field "LiveSessionStudent.last_updated_at"`)}
	}
	if len(_c.mutation.SessionIDs()) == 0 {
		return &ValidationError{Name: "session", err: errors.New(`ent: missing required edge "LiveSessionStudent.session"`)}
	}
	if len(_c.mutation.StudentIDs()) == 0 {
		return &ValidationError{Name: "student", err: errors.New(`ent: missing required edge "LiveSessionStudent.student"`)}
	}
	return nil
}

func (_c *LiveSessionStudentCreate) sqlSave(ctx context.Context) (*LiveSessionStudent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LiveSessionStudentCreate) createSpec() (*LiveSessionStudent, *sqlgraph.CreateSpec) {
	var (
		_node = &LiveSessionStudent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(livesessionstudent.Table, sqlgraph.NewFieldSpec(livesessionstudent.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.StudentName(); ok {
		_spec.SetField(livesessionstudent.FieldStudentName, field.TypeString, value)
		_node.StudentName = value
	}
	if value, ok := _c.mutation.StarsCollected(); ok {
		_spec.SetField(livesessionstudent.FieldStarsCollected, field.TypeInt, value)
		_node.StarsCollected = value
	}
	if value, ok := _c.mutation.Completed(); ok {
		_spec.SetField(livesessionstudent.FieldCompleted, field.TypeBool, value)
		_node.Completed = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(livesessionstudent.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(livesessionstudent.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.JoinedAt(); ok {
		_spec.SetField(livesessionstudent.FieldJoinedAt, field.TypeTime, value)
		_node.JoinedAt = value
	}
	if value, ok := _c.mutation.LeftAt(); ok {
		_spec.SetField(livesessionstudent.FieldLeftAt, field.TypeTime, value)
		_node.LeftAt = &value
	}
	if value, ok := _c.mutation.LastUpdatedAt(); ok {
		_spec.SetField(livesessionstudent.FieldLastUpdatedAt, field.TypeTime, value)
		_node.LastUpdatedAt = value
	}
	if nodes := _c.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   livesessionstudent.SessionTable,
			Columns: []string{livesessionstudent.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(livesession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.live_session_students = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.StudentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   livesessionstudent.StudentTable,
			Columns: []string{livesessionstudent.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_live_session_participations = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LiveSessionStudentCreateBulk is the builder for creating many LiveSessionStudent entities in bulk.
type LiveSessionStudentCreateBulk struct {
	config
	err      error
	builders []*LiveSessionStudentCreate
}

// Save creates the LiveSessionStudent entities in the database.
func (_c *LiveSessionStudentCreateBulk) Save(ctx context.Context) ([]*LiveSessionStudent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LiveSessionStudent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LiveSessionStudentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LiveSessionStudentCreateBulk) SaveX(ctx context.Context) []*LiveSessionStudent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LiveSessionStudentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LiveSessionStudentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
