// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"gigaboo.io/lem/internal/ent/app"
	"gigaboo.io/lem/internal/ent/shenbisettings"
	"gigaboo.io/lem/internal/ent/user"
)

// ShenbiSettings is the model entity for the ShenbiSettings schema.
type ShenbiSettings struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// SoundEnabled holds the value of the "sound_enabled" field.
	SoundEnabled bool `json:"sound_enabled,omitempty"`
	// PreferredTheme holds the value of the "preferred_theme" field.
	PreferredTheme string `json:"preferred_theme,omitempty"`
	// TourCompleted holds the value of the "tour_completed" field.
	TourCompleted map[string]bool `json:"tour_completed,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ShenbiSettingsQuery when eager-loading is set.
	Edges                ShenbiSettingsEdges `json:"edges"`
	app_shenbi_settings  *int
	user_shenbi_settings *int
	selectValues         sql.SelectValues
}

// ShenbiSettingsEdges holds the relations/edges for other nodes in the graph.
type ShenbiSettingsEdges struct {
	// App holds the value of the app edge.
	App *App `json:"app,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AppOrErr returns the App value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ShenbiSettingsEdges) AppOrErr() (*App, error) {
	if e.App != nil {
		return e.App, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: app.Label}
	}
	return nil, &NotLoadedError{edge: "app"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ShenbiSettingsEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ShenbiSettings) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case shenbisettings.FieldTourCompleted:
			values[i] = new([]byte)
		case shenbisettings.FieldSoundEnabled:
			values[i] = new(sql.NullBool)
		case shenbisettings.FieldID:
			values[i] = new(sql.NullInt64)
		case shenbisettings.FieldPreferredTheme:
			values[i] = new(sql.NullString)
		case shenbisettings.FieldCreatedAt, shenbisettings.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case shenbisettings.ForeignKeys[0]: // app_shenbi_settings
			values[i] = new(sql.NullInt64)
		case shenbisettings.ForeignKeys[1]: // user_shenbi_settings
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ShenbiSettings fields.
func (_m *ShenbiSettings) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case shenbisettings.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case shenbisettings.FieldSoundEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field sound_enabled", values[i])
			} else if value.Valid {
				_m.SoundEnabled = value.Bool
			}
		case shenbisettings.FieldPreferredTheme:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field preferred_theme", values[i])
			} else if value.Valid {
				_m.PreferredTheme = value.String
			}
		case shenbisettings.FieldTourCompleted:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tour_completed", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.TourCompleted); err != nil {
					return fmt.Errorf("unmarshal field tour_completed: %w", err)
				}
			}
		case shenbisettings.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case shenbisettings.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case shenbisettings.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field app_shenbi_settings", value)
			} else if value.Valid {
				_m.app_shenbi_settings = new(int)
				*_m.app_shenbi_settings = int(value.Int64)
			}
		case shenbisettings.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_shenbi_settings", value)
			} else if value.Valid {
				_m.user_shenbi_settings = new(int)
				*_m.user_shenbi_settings = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ShenbiSettings.
// This includes values selected through modifiers, order, etc.
func (_m *ShenbiSettings) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryApp queries the "app" edge of the ShenbiSettings entity.
func (_m *ShenbiSettings) QueryApp() *AppQuery {
	return NewShenbiSettingsClient(_m.config).QueryApp(_m)
}

// QueryUser queries the "user" edge of the ShenbiSettings entity.
func (_m *ShenbiSettings) QueryUser() *UserQuery {
	return NewShenbiSettingsClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this ShenbiSettings.
// Note that you need to call ShenbiSettings.Unwrap() before calling this method if this ShenbiSettings
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ShenbiSettings) Update() *ShenbiSettingsUpdateOne {
	return NewShenbiSettingsClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ShenbiSettings entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ShenbiSettings) Unwrap() *ShenbiSettings {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ShenbiSettings is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ShenbiSettings) String() string {
	var builder strings.Builder
	builder.WriteString("ShenbiSettings(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("sound_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.SoundEnabled))
	builder.WriteString(", ")
	builder.WriteString("preferred_theme=")
	builder.WriteString(_m.PreferredTheme)
	builder.WriteString(", ")
	builder.WriteString("tour_completed=")
	builder.WriteString(fmt.Sprintf("%v", _m.TourCompleted))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ShenbiSettingsSlice is a parsable slice of ShenbiSettings.
type ShenbiSettingsSlice []*ShenbiSettings
