// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gigaboo.io/lem/internal/ent/app"
	"gigaboo.io/lem/internal/ent/shenbiprofile"
	"gigaboo.io/lem/internal/ent/user"
)

// ShenbiProfileCreate is the builder for creating a ShenbiProfile entity.
type ShenbiProfileCreate struct {
	config
	mutation *ShenbiProfileMutation
	hooks    []Hook
}

// SetRole sets the "role" field.
func (_c *ShenbiProfileCreate) SetRole(v shenbiprofile.Role) *ShenbiProfileCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *ShenbiProfileCreate) SetNillableRole(v *shenbiprofile.Role) *ShenbiProfileCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *ShenbiProfileCreate) SetDisplayName(v string) *ShenbiProfileCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_c *ShenbiProfileCreate) SetNillableDisplayName(v *string) *ShenbiProfileCreate {
	if v != nil {
		_c.SetDisplayName(*v)
	}
	return _c
}

// SetAvatarURL sets the "avatar_url" field.
func (_c *ShenbiProfileCreate) SetAvatarURL(v string) *ShenbiProfileCreate {
	_c.mutation.SetAvatarURL(v)
	return _c
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_c *ShenbiProfileCreate) SetNillableAvatarURL(v *string) *ShenbiProfileCreate {
	if v != nil {
		_c.SetAvatarURL(*v)
	}
	return _c
}

// SetGrade sets the "grade" field.
func (_c *ShenbiProfileCreate) SetGrade(v int) *ShenbiProfileCreate {
	_c.mutation.SetGrade(v)
	return _c
}

// SetNillableGrade sets the "grade" field if the given value is not nil.
func (_c *ShenbiProfileCreate) SetNillableGrade(v *int) *ShenbiProfileCreate {
	if v != nil {
		_c.SetGrade(*v)
	}
	return _c
}

// SetAge sets the "age" field.
func (_c *ShenbiProfileCreate) SetAge(v int) *ShenbiProfileCreate {
	_c.mutation.SetAge(v)
	return _c
}

// SetNillableAge sets the "age" field if the given value is not nil.
func (_c *ShenbiProfileCreate) SetNillableAge(v *int) *ShenbiProfileCreate {
	if v != nil {
		_c.SetAge(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ShenbiProfileCreate) SetCreatedAt(v time.Time) *ShenbiProfileCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ShenbiProfileCreate) SetNillableCreatedAt(v *time.Time) *ShenbiProfileCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ShenbiProfileCreate) SetUpdatedAt(v time.Time) *ShenbiProfileCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ShenbiProfileCreate) SetNillableUpdatedAt(v *time.Time) *ShenbiProfileCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAppID sets the "app" edge to the App entity by ID.
func (_c *ShenbiProfileCreate) SetAppID(id int) *ShenbiProfileCreate {
	_c.mutation.SetAppID(id)
	return _c
}

// SetApp sets the "app" edge to the App entity.
func (_c *ShenbiProfileCreate) SetApp(v *App) *ShenbiProfileCreate {
	return _c.SetAppID(v.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *ShenbiProfileCreate) SetUserID(id int) *ShenbiProfileCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ShenbiProfileCreate) SetUser(v *User) *ShenbiProfileCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the ShenbiProfileMutation object of the builder.
func (_c *ShenbiProfileCreate) Mutation() *ShenbiProfileMutation {
	return _c.mutation
}

// Save creates the ShenbiProfile in the database.
func (_c *ShenbiProfileCreate) Save(ctx context.Context) (*ShenbiProfile, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ShenbiProfileCreate) SaveX(ctx context.Context) *ShenbiProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShenbiProfileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShenbiProfileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ShenbiProfileCreate) defaults() {
	if _, ok := _c.mutation.Role(); !ok {
		v := shenbiprofile.DefaultRole
		_c.mutation.SetRole(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := shenbiprofile.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := shenbiprofile.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ShenbiProfileCreate) check() error {
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "ShenbiProfile.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := shenbiprofile.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "ShenbiProfile.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ShenbiProfile.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ShenbiProfile.updated_at"`)}
	}
	if len(_c.mutation.AppIDs()) == 0 {
		return &ValidationError{Name: "app", err: errors.New(`ent: missing required edge "ShenbiProfile.app"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "ShenbiProfile.user"`)}
	}
	return nil
}

func (_c *ShenbiProfileCreate) sqlSave(ctx context.Context) (*ShenbiProfile, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ShenbiProfileCreate) createSpec() (*ShenbiProfile, *sqlgraph.CreateSpec) {
	var (
		_node = &ShenbiProfile{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(shenbiprofile.Table, sqlgraph.NewFieldSpec(shenbiprofile.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(shenbiprofile.FieldRole, field.TypeEnum, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(shenbiprofile.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.AvatarURL(); ok {
		_spec.SetField(shenbiprofile.FieldAvatarURL, field.TypeString, value)
		_node.AvatarURL = value
	}
	if value, ok := _c.mutation.Grade(); ok {
		_spec.SetField(shenbiprofile.FieldGrade, field.TypeInt, value)
		_node.Grade = &value
	}
	if value, ok := _c.mutation.Age(); ok {
		_spec.SetField(shenbiprofile.FieldAge, field.TypeInt, value)
		_node.Age = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(shenbiprofile.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(shenbiprofile.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.AppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shenbiprofile.AppTable,
			Columns: []string{shenbiprofile.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.app_shenbi_profiles = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   shenbiprofile.UserTable,
			Columns: []string{shenbiprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_shenbi_profile = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ShenbiProfileCreateBulk is the builder for creating many ShenbiProfile entities in bulk.
type ShenbiProfileCreateBulk struct {
	config
	err      error
	builders []*ShenbiProfileCreate
}

// Save creates the ShenbiProfile entities in the database.
func (_c *ShenbiProfileCreateBulk) Save(ctx context.Context) ([]*ShenbiProfile, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ShenbiProfile, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ShenbiProfileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ShenbiProfileCreateBulk) SaveX(ctx context.Context) []*ShenbiProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShenbiProfileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShenbiProfileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
