// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gigaboo.io/lem/internal/ent/app"
	"gigaboo.io/lem/internal/ent/organization"
	"gigaboo.io/lem/internal/ent/plan"
	"gigaboo.io/lem/internal/ent/predicate"
	"gigaboo.io/lem/internal/ent/subscription"
	"gigaboo.io/lem/internal/ent/user"
)

// SubscriptionUpdate is the builder for updating Subscription entities.
type SubscriptionUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionMutation
}

// Where appends a list predicates to the SubscriptionUpdate builder.
func (_u *SubscriptionUpdate) Where(ps ...predicate.Subscription) *SubscriptionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionUpdate) SetStatus(v subscription.Status) *SubscriptionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableStatus(v *subscription.Status) *SubscriptionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStripeSubscriptionID sets the "stripe_subscription_id" field.
func (_u *SubscriptionUpdate) SetStripeSubscriptionID(v string) *SubscriptionUpdate {
	_u.mutation.SetStripeSubscriptionID(v)
	return _u
}

// SetNillableStripeSubscriptionID sets the "stripe_subscription_id" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableStripeSubscriptionID(v *string) *SubscriptionUpdate {
	if v != nil {
		_u.SetStripeSubscriptionID(*v)
	}
	return _u
}

// ClearStripeSubscriptionID clears the value of the "stripe_subscription_id" field.
func (_u *SubscriptionUpdate) ClearStripeSubscriptionID() *SubscriptionUpdate {
	_u.mutation.ClearStripeSubscriptionID()
	return _u
}

// SetCurrentPeriodStart sets the "current_period_start" field.
func (_u *SubscriptionUpdate) SetCurrentPeriodStart(v time.Time) *SubscriptionUpdate {
	_u.mutation.SetCurrentPeriodStart(v)
	return _u
}

// SetNillableCurrentPeriodStart sets the "current_period_start" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableCurrentPeriodStart(v *time.Time) *SubscriptionUpdate {
	if v != nil {
		_u.SetCurrentPeriodStart(*v)
	}
	return _u
}

// ClearCurrentPeriodStart clears the value of the "current_period_start" field.
func (_u *SubscriptionUpdate) ClearCurrentPeriodStart() *SubscriptionUpdate {
	_u.mutation.ClearCurrentPeriodStart()
	return _u
}

// SetCurrentPeriodEnd sets the "current_period_end" field.
func (_u *SubscriptionUpdate) SetCurrentPeriodEnd(v time.Time) *SubscriptionUpdate {
	_u.mutation.SetCurrentPeriodEnd(v)
	return _u
}

// SetNillableCurrentPeriodEnd sets the "current_period_end" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableCurrentPeriodEnd(v *time.Time) *SubscriptionUpdate {
	if v != nil {
		_u.SetCurrentPeriodEnd(*v)
	}
	return _u
}

// ClearCurrentPeriodEnd clears the value of the "current_period_end" field.
func (_u *SubscriptionUpdate) ClearCurrentPeriodEnd() *SubscriptionUpdate {
	_u.mutation.ClearCurrentPeriodEnd()
	return _u
}

// SetCanceledAt sets the "canceled_at" field.
func (_u *SubscriptionUpdate) SetCanceledAt(v time.Time) *SubscriptionUpdate {
	_u.mutation.SetCanceledAt(v)
	return _u
}

// SetNillableCanceledAt sets the "canceled_at" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableCanceledAt(v *time.Time) *SubscriptionUpdate {
	if v != nil {
		_u.SetCanceledAt(*v)
	}
	return _u
}

// ClearCanceledAt clears the value of the "canceled_at" field.
func (_u *SubscriptionUpdate) ClearCanceledAt() *SubscriptionUpdate {
	_u.mutation.ClearCanceledAt()
	return _u
}

// SetTrialEnd sets the "trial_end" field.
func (_u *SubscriptionUpdate) SetTrialEnd(v time.Time) *SubscriptionUpdate {
	_u.mutation.SetTrialEnd(v)
	return _u
}

// SetNillableTrialEnd sets the "trial_end" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableTrialEnd(v *time.Time) *SubscriptionUpdate {
	if v != nil {
		_u.SetTrialEnd(*v)
	}
	return _u
}

// ClearTrialEnd clears the value of the "trial_end" field.
func (_u *SubscriptionUpdate) ClearTrialEnd() *SubscriptionUpdate {
	_u.mutation.ClearTrialEnd()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionUpdate) SetUpdatedAt(v time.Time) *SubscriptionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *SubscriptionUpdate) SetUserID(id int) *SubscriptionUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableUserID(id *int) *SubscriptionUpdate {
	if id != nil {
		_u = _u.SetUserID(*id)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SubscriptionUpdate) SetUser(v *User) *SubscriptionUpdate {
	return _u.SetUserID(v.ID)
}

// SetOrganizationID sets the "organization" edge to the Organization entity by ID.
func (_u *SubscriptionUpdate) SetOrganizationID(id int) *SubscriptionUpdate {
	_u.mutation.SetOrganizationID(id)
	return _u
}

// SetNillableOrganizationID sets the "organization" edge to the Organization entity by ID if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableOrganizationID(id *int) *SubscriptionUpdate {
	if id != nil {
		_u = _u.SetOrganizationID(*id)
	}
	return _u
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_u *SubscriptionUpdate) SetOrganization(v *Organization) *SubscriptionUpdate {
	return _u.SetOrganizationID(v.ID)
}

// SetAppID sets the "app" edge to the App entity by ID.
func (_u *SubscriptionUpdate) SetAppID(id int) *SubscriptionUpdate {
	_u.mutation.SetAppID(id)
	return _u
}

// SetApp sets the "app" edge to the App entity.
func (_u *SubscriptionUpdate) SetApp(v *App) *SubscriptionUpdate {
	return _u.SetAppID(v.ID)
}

// SetPlanID sets the "plan" edge to the Plan entity by ID.
func (_u *SubscriptionUpdate) SetPlanID(id int) *SubscriptionUpdate {
	_u.mutation.SetPlanID(id)
	return _u
}

// SetPlan sets the "plan" edge to the Plan entity.
func (_u *SubscriptionUpdate) SetPlan(v *Plan) *SubscriptionUpdate {
	return _u.SetPlanID(v.ID)
}

// Mutation returns the SubscriptionMutation object of the builder.
func (_u *SubscriptionUpdate) Mutation() *SubscriptionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SubscriptionUpdate) ClearUser() *SubscriptionUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (_u *SubscriptionUpdate) ClearOrganization() *SubscriptionUpdate {
	_u.mutation.ClearOrganization()
	return _u
}

// ClearApp clears the "app" edge to the App entity.
func (_u *SubscriptionUpdate) ClearApp() *SubscriptionUpdate {
	_u.mutation.ClearApp()
	return _u
}

// ClearPlan clears the "plan" edge to the Plan entity.
func (_u *SubscriptionUpdate) ClearPlan() *SubscriptionUpdate {
	_u.mutation.ClearPlan()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := subscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Subscription.status": %w`, err)}
		}
	}
	if _u.mutation.AppCleared() && len(_u.mutation.AppIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Subscription.app"`)
	}
	if _u.mutation.PlanCleared() && len(_u.mutation.PlanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Subscription.plan"`)
	}
	return nil
}

func (_u *SubscriptionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscription.Table, subscription.Columns, sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscription.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StripeSubscriptionID(); ok {
		_spec.SetField(subscription.FieldStripeSubscriptionID, field.TypeString, value)
	}
	if _u.mutation.StripeSubscriptionIDCleared() {
		_spec.ClearField(subscription.FieldStripeSubscriptionID, field.TypeString)
	}
	if value, ok := _u.mutation.CurrentPeriodStart(); ok {
		_spec.SetField(subscription.FieldCurrentPeriodStart, field.TypeTime, value)
	}
	if _u.mutation.CurrentPeriodStartCleared() {
		_spec.ClearField(subscription.FieldCurrentPeriodStart, field.TypeTime)
	}
	if value, ok := _u.mutation.CurrentPeriodEnd(); ok {
		_spec.SetField(subscription.FieldCurrentPeriodEnd, field.TypeTime, value)
	}
	if _u.mutation.CurrentPeriodEndCleared() {
		_spec.ClearField(subscription.FieldCurrentPeriodEnd, field.TypeTime)
	}
	if value, ok := _u.mutation.CanceledAt(); ok {
		_spec.SetField(subscription.FieldCanceledAt, field.TypeTime, value)
	}
	if _u.mutation.CanceledAtCleared() {
		_spec.ClearField(subscription.FieldCanceledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.TrialEnd(); ok {
		_spec.SetField(subscription.FieldTrialEnd, field.TypeTime, value)
	}
	if _u.mutation.TrialEndCleared() {
		_spec.ClearField(subscription.FieldTrialEnd, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.UserTable,
			Columns: []string{subscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.UserTable,
			Columns: []string{subscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.OrganizationTable,
			Columns: []string{subscription.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.OrganizationTable,
			Columns: []string{subscription.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AppCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.AppTable,
			Columns: []string{subscription.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.AppTable,
			Columns: []string{subscription.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.PlanTable,
			Columns: []string{subscription.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.PlanTable,
			Columns: []string{subscription.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionUpdateOne is the builder for updating a single Subscription entity.
type SubscriptionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionMutation
}

// SetStatus sets the "status" field.
func (_u *SubscriptionUpdateOne) SetStatus(v subscription.Status) *SubscriptionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableStatus(v *subscription.Status) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStripeSubscriptionID sets the "stripe_subscription_id" field.
func (_u *SubscriptionUpdateOne) SetStripeSubscriptionID(v string) *SubscriptionUpdateOne {
	_u.mutation.SetStripeSubscriptionID(v)
	return _u
}

// SetNillableStripeSubscriptionID sets the "stripe_subscription_id" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableStripeSubscriptionID(v *string) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetStripeSubscriptionID(*v)
	}
	return _u
}

// ClearStripeSubscriptionID clears the value of the "stripe_subscription_id" field.
func (_u *SubscriptionUpdateOne) ClearStripeSubscriptionID() *SubscriptionUpdateOne {
	_u.mutation.ClearStripeSubscriptionID()
	return _u
}

// SetCurrentPeriodStart sets the "current_period_start" field.
func (_u *SubscriptionUpdateOne) SetCurrentPeriodStart(v time.Time) *SubscriptionUpdateOne {
	_u.mutation.SetCurrentPeriodStart(v)
	return _u
}

// SetNillableCurrentPeriodStart sets the "current_period_start" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableCurrentPeriodStart(v *time.Time) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetCurrentPeriodStart(*v)
	}
	return _u
}

// ClearCurrentPeriodStart clears the value of the "current_period_start" field.
func (_u *SubscriptionUpdateOne) ClearCurrentPeriodStart() *SubscriptionUpdateOne {
	_u.mutation.ClearCurrentPeriodStart()
	return _u
}

// SetCurrentPeriodEnd sets the "current_period_end" field.
func (_u *SubscriptionUpdateOne) SetCurrentPeriodEnd(v time.Time) *SubscriptionUpdateOne {
	_u.mutation.SetCurrentPeriodEnd(v)
	return _u
}

// SetNillableCurrentPeriodEnd sets the "current_period_end" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableCurrentPeriodEnd(v *time.Time) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetCurrentPeriodEnd(*v)
	}
	return _u
}

// ClearCurrentPeriodEnd clears the value of the "current_period_end" field.
func (_u *SubscriptionUpdateOne) ClearCurrentPeriodEnd() *SubscriptionUpdateOne {
	_u.mutation.ClearCurrentPeriodEnd()
	return _u
}

// SetCanceledAt sets the "canceled_at" field.
func (_u *SubscriptionUpdateOne) SetCanceledAt(v time.Time) *SubscriptionUpdateOne {
	_u.mutation.SetCanceledAt(v)
	return _u
}

// SetNillableCanceledAt sets the "canceled_at" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableCanceledAt(v *time.Time) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetCanceledAt(*v)
	}
	return _u
}

// ClearCanceledAt clears the value of the "canceled_at" field.
func (_u *SubscriptionUpdateOne) ClearCanceledAt() *SubscriptionUpdateOne {
	_u.mutation.ClearCanceledAt()
	return _u
}

// SetTrialEnd sets the "trial_end" field.
func (_u *SubscriptionUpdateOne) SetTrialEnd(v time.Time) *SubscriptionUpdateOne {
	_u.mutation.SetTrialEnd(v)
	return _u
}

// SetNillableTrialEnd sets the "trial_end" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableTrialEnd(v *time.Time) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetTrialEnd(*v)
	}
	return _u
}

// ClearTrialEnd clears the value of the "trial_end" field.
func (_u *SubscriptionUpdateOne) ClearTrialEnd() *SubscriptionUpdateOne {
	_u.mutation.ClearTrialEnd()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionUpdateOne) SetUpdatedAt(v time.Time) *SubscriptionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *SubscriptionUpdateOne) SetUserID(id int) *SubscriptionUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableUserID(id *int) *SubscriptionUpdateOne {
	if id != nil {
		_u = _u.SetUserID(*id)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SubscriptionUpdateOne) SetUser(v *User) *SubscriptionUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetOrganizationID sets the "organization" edge to the Organization entity by ID.
func (_u *SubscriptionUpdateOne) SetOrganizationID(id int) *SubscriptionUpdateOne {
	_u.mutation.SetOrganizationID(id)
	return _u
}

// SetNillableOrganizationID sets the "organization" edge to the Organization entity by ID if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableOrganizationID(id *int) *SubscriptionUpdateOne {
	if id != nil {
		_u = _u.SetOrganizationID(*id)
	}
	return _u
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_u *SubscriptionUpdateOne) SetOrganization(v *Organization) *SubscriptionUpdateOne {
	return _u.SetOrganizationID(v.ID)
}

// SetAppID sets the "app" edge to the App entity by ID.
func (_u *SubscriptionUpdateOne) SetAppID(id int) *SubscriptionUpdateOne {
	_u.mutation.SetAppID(id)
	return _u
}

// SetApp sets the "app" edge to the App entity.
func (_u *SubscriptionUpdateOne) SetApp(v *App) *SubscriptionUpdateOne {
	return _u.SetAppID(v.ID)
}

// SetPlanID sets the "plan" edge to the Plan entity by ID.
func (_u *SubscriptionUpdateOne) SetPlanID(id int) *SubscriptionUpdateOne {
	_u.mutation.SetPlanID(id)
	return _u
}

// SetPlan sets the "plan" edge to the Plan entity.
func (_u *SubscriptionUpdateOne) SetPlan(v *Plan) *SubscriptionUpdateOne {
	return _u.SetPlanID(v.ID)
}

// Mutation returns the SubscriptionMutation object of the builder.
func (_u *SubscriptionUpdateOne) Mutation() *SubscriptionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SubscriptionUpdateOne) ClearUser() *SubscriptionUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (_u *SubscriptionUpdateOne) ClearOrganization() *SubscriptionUpdateOne {
	_u.mutation.ClearOrganization()
	return _u
}

// ClearApp clears the "app" edge to the App entity.
func (_u *SubscriptionUpdateOne) ClearApp() *SubscriptionUpdateOne {
	_u.mutation.ClearApp()
	return _u
}

// ClearPlan clears the "plan" edge to the Plan entity.
func (_u *SubscriptionUpdateOne) ClearPlan() *SubscriptionUpdateOne {
	_u.mutation.ClearPlan()
	return _u
}

// Where appends a list predicates to the SubscriptionUpdate builder.
func (_u *SubscriptionUpdateOne) Where(ps ...predicate.Subscription) *SubscriptionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionUpdateOne) Select(field string, fields ...string) *SubscriptionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Subscription entity.
func (_u *SubscriptionUpdateOne) Save(ctx context.Context) (*Subscription, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionUpdateOne) SaveX(ctx context.Context) *Subscription {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := subscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Subscription.status": %w`, err)}
		}
	}
	if _u.mutation.AppCleared() && len(_u.mutation.AppIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Subscription.app"`)
	}
	if _u.mutation.PlanCleared() && len(_u.mutation.PlanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Subscription.plan"`)
	}
	return nil
}

func (_u *SubscriptionUpdateOne) sqlSave(ctx context.Context) (_node *Subscription, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscription.Table, subscription.Columns, sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Subscription.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscription.FieldID)
		for _, f := range fields {
			if !subscription.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscription.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscription.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StripeSubscriptionID(); ok {
		_spec.SetField(subscription.FieldStripeSubscriptionID, field.TypeString, value)
	}
	if _u.mutation.StripeSubscriptionIDCleared() {
		_spec.ClearField(subscription.FieldStripeSubscriptionID, field.TypeString)
	}
	if value, ok := _u.mutation.CurrentPeriodStart(); ok {
		_spec.SetField(subscription.FieldCurrentPeriodStart, field.TypeTime, value)
	}
	if _u.mutation.CurrentPeriodStartCleared() {
		_spec.ClearField(subscription.FieldCurrentPeriodStart, field.TypeTime)
	}
	if value, ok := _u.mutation.CurrentPeriodEnd(); ok {
		_spec.SetField(subscription.FieldCurrentPeriodEnd, field.TypeTime, value)
	}
	if _u.mutation.CurrentPeriodEndCleared() {
		_spec.ClearField(subscription.FieldCurrentPeriodEnd, field.TypeTime)
	}
	if value, ok := _u.mutation.CanceledAt(); ok {
		_spec.SetField(subscription.FieldCanceledAt, field.TypeTime, value)
	}
	if _u.mutation.CanceledAtCleared() {
		_spec.ClearField(subscription.FieldCanceledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.TrialEnd(); ok {
		_spec.SetField(subscription.FieldTrialEnd, field.TypeTime, value)
	}
	if _u.mutation.TrialEndCleared() {
		_spec.ClearField(subscription.FieldTrialEnd, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.UserTable,
			Columns: []string{subscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.UserTable,
			Columns: []string{subscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.OrganizationTable,
			Columns: []string{subscription.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.OrganizationTable,
			Columns: []string{subscription.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AppCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.AppTable,
			Columns: []string{subscription.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.AppTable,
			Columns: []string{subscription.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.PlanTable,
			Columns: []string{subscription.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.PlanTable,
			Columns: []string{subscription.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Subscription{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
