// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gigaboo.io/lem/internal/ent/achievement"
	"gigaboo.io/lem/internal/ent/assignmentsubmission"
	"gigaboo.io/lem/internal/ent/battleroom"
	"gigaboo.io/lem/internal/ent/battlesession"
	"gigaboo.io/lem/internal/ent/classroom"
	"gigaboo.io/lem/internal/ent/classroommembership"
	"gigaboo.io/lem/internal/ent/classroomsession"
	"gigaboo.io/lem/internal/ent/livesession"
	"gigaboo.io/lem/internal/ent/livesessionstudent"
	"gigaboo.io/lem/internal/ent/organizationinvitation"
	"gigaboo.io/lem/internal/ent/organizationmember"
	"gigaboo.io/lem/internal/ent/shenbiprofile"
	"gigaboo.io/lem/internal/ent/shenbisettings"
	"gigaboo.io/lem/internal/ent/subscription"
	"gigaboo.io/lem/internal/ent/user"
	"gigaboo.io/lem/internal/ent/userapp"
	"gigaboo.io/lem/internal/ent/userprogress"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	mutation *UserMutation
	hooks    []Hook
}

// SetEmail sets the "email" field.
func (_c *UserCreate) SetEmail(v string) *UserCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetPasswordHash sets the "password_hash" field.
func (_c *UserCreate) SetPasswordHash(v string) *UserCreate {
	_c.mutation.SetPasswordHash(v)
	return _c
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_c *UserCreate) SetNillablePasswordHash(v *string) *UserCreate {
	if v != nil {
		_c.SetPasswordHash(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *UserCreate) SetName(v string) *UserCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *UserCreate) SetNillableName(v *string) *UserCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetAvatarURL sets the "avatar_url" field.
func (_c *UserCreate) SetAvatarURL(v string) *UserCreate {
	_c.mutation.SetAvatarURL(v)
	return _c
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_c *UserCreate) SetNillableAvatarURL(v *string) *UserCreate {
	if v != nil {
		_c.SetAvatarURL(*v)
	}
	return _c
}

// SetDeviceID sets the "device_id" field.
func (_c *UserCreate) SetDeviceID(v string) *UserCreate {
	_c.mutation.SetDeviceID(v)
	return _c
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_c *UserCreate) SetNillableDeviceID(v *string) *UserCreate {
	if v != nil {
		_c.SetDeviceID(*v)
	}
	return _c
}

// SetGoogleID sets the "google_id" field.
func (_c *UserCreate) SetGoogleID(v string) *UserCreate {
	_c.mutation.SetGoogleID(v)
	return _c
}

// SetNillableGoogleID sets the "google_id" field if the given value is not nil.
func (_c *UserCreate) SetNillableGoogleID(v *string) *UserCreate {
	if v != nil {
		_c.SetGoogleID(*v)
	}
	return _c
}

// SetAppleID sets the "apple_id" field.
func (_c *UserCreate) SetAppleID(v string) *UserCreate {
	_c.mutation.SetAppleID(v)
	return _c
}

// SetNillableAppleID sets the "apple_id" field if the given value is not nil.
func (_c *UserCreate) SetNillableAppleID(v *string) *UserCreate {
	if v != nil {
		_c.SetAppleID(*v)
	}
	return _c
}

// SetGoogleAccessToken sets the "google_access_token" field.
func (_c *UserCreate) SetGoogleAccessToken(v string) *UserCreate {
	_c.mutation.SetGoogleAccessToken(v)
	return _c
}

// SetNillableGoogleAccessToken sets the "google_access_token" field if the given value is not nil.
func (_c *UserCreate) SetNillableGoogleAccessToken(v *string) *UserCreate {
	if v != nil {
		_c.SetGoogleAccessToken(*v)
	}
	return _c
}

// SetGoogleRefreshToken sets the "google_refresh_token" field.
func (_c *UserCreate) SetGoogleRefreshToken(v string) *UserCreate {
	_c.mutation.SetGoogleRefreshToken(v)
	return _c
}

// SetNillableGoogleRefreshToken sets the "google_refresh_token" field if the given value is not nil.
func (_c *UserCreate) SetNillableGoogleRefreshToken(v *string) *UserCreate {
	if v != nil {
		_c.SetGoogleRefreshToken(*v)
	}
	return _c
}

// SetGoogleTokenExpiresAt sets the "google_token_expires_at" field.
func (_c *UserCreate) SetGoogleTokenExpiresAt(v time.Time) *UserCreate {
	_c.mutation.SetGoogleTokenExpiresAt(v)
	return _c
}

// SetNillableGoogleTokenExpiresAt sets the "google_token_expires_at" field if the given value is not nil.
func (_c *UserCreate) SetNillableGoogleTokenExpiresAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetGoogleTokenExpiresAt(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *UserCreate) SetIsActive(v bool) *UserCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *UserCreate) SetNillableIsActive(v *bool) *UserCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetIsVerified sets the "is_verified" field.
func (_c *UserCreate) SetIsVerified(v bool) *UserCreate {
	_c.mutation.SetIsVerified(v)
	return _c
}

// SetNillableIsVerified sets the "is_verified" field if the given value is not nil.
func (_c *UserCreate) SetNillableIsVerified(v *bool) *UserCreate {
	if v != nil {
		_c.SetIsVerified(*v)
	}
	return _c
}

// SetExtraData sets the "extra_data" field.
func (_c *UserCreate) SetExtraData(v map[string]interface{}) *UserCreate {
	_c.mutation.SetExtraData(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserCreate) SetCreatedAt(v time.Time) *UserCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserCreate) SetNillableCreatedAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserCreate) SetUpdatedAt(v time.Time) *UserCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserCreate) SetNillableUpdatedAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetLastLoginAt sets the "last_login_at" field.
func (_c *UserCreate) SetLastLoginAt(v time.Time) *UserCreate {
	_c.mutation.SetLastLoginAt(v)
	return _c
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_c *UserCreate) SetNillableLastLoginAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetLastLoginAt(*v)
	}
	return _c
}

// AddUserAppIDs adds the "user_apps" edge to the UserApp entity by IDs.
func (_c *UserCreate) AddUserAppIDs(ids ...int) *UserCreate {
	_c.mutation.AddUserAppIDs(ids...)
	return _c
}

// AddUserApps adds the "user_apps" edges to the UserApp entity.
func (_c *UserCreate) AddUserApps(v ...*UserApp) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUserAppIDs(ids...)
}

// AddOrganizationMembershipIDs adds the "organization_memberships" edge to the OrganizationMember entity by IDs.
func (_c *UserCreate) AddOrganizationMembershipIDs(ids ...int) *UserCreate {
	_c.mutation.AddOrganizationMembershipIDs(ids...)
	return _c
}

// AddOrganizationMemberships adds the "organization_memberships" edges to the OrganizationMember entity.
func (_c *UserCreate) AddOrganizationMemberships(v ...*OrganizationMember) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOrganizationMembershipIDs(ids...)
}

// AddSubscriptionIDs adds the "subscriptions" edge to the Subscription entity by IDs.
func (_c *UserCreate) AddSubscriptionIDs(ids ...int) *UserCreate {
	_c.mutation.AddSubscriptionIDs(ids...)
	return _c
}

// AddSubscriptions adds the "subscriptions" edges to the Subscription entity.
func (_c *UserCreate) AddSubscriptions(v ...*Subscription) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSubscriptionIDs(ids...)
}

// SetShenbiProfileID sets the "shenbi_profile" edge to the ShenbiProfile entity by ID.
func (_c *UserCreate) SetShenbiProfileID(id int) *UserCreate {
	_c.mutation.SetShenbiProfileID(id)
	return _c
}

// SetNillableShenbiProfileID sets the "shenbi_profile" edge to the ShenbiProfile entity by ID if the given value is not nil.
func (_c *UserCreate) SetNillableShenbiProfileID(id *int) *UserCreate {
	if id != nil {
		_c = _c.SetShenbiProfileID(*id)
	}
	return _c
}

// SetShenbiProfile sets the "shenbi_profile" edge to the ShenbiProfile entity.
func (_c *UserCreate) SetShenbiProfile(v *ShenbiProfile) *UserCreate {
	return _c.SetShenbiProfileID(v.ID)
}

// AddClassroomsTeachingIDs adds the "classrooms_teaching" edge to the Classroom entity by IDs.
func (_c *UserCreate) AddClassroomsTeachingIDs(ids ...int) *UserCreate {
	_c.mutation.AddClassroomsTeachingIDs(ids...)
	return _c
}

// AddClassroomsTeaching adds the "classrooms_teaching" edges to the Classroom entity.
func (_c *UserCreate) AddClassroomsTeaching(v ...*Classroom) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddClassroomsTeachingIDs(ids...)
}

// AddClassroomMembershipIDs adds the "classroom_memberships" edge to the ClassroomMembership entity by IDs.
func (_c *UserCreate) AddClassroomMembershipIDs(ids ...int) *UserCreate {
	_c.mutation.AddClassroomMembershipIDs(ids...)
	return _c
}

// AddClassroomMemberships adds the "classroom_memberships" edges to the ClassroomMembership entity.
func (_c *UserCreate) AddClassroomMemberships(v ...*ClassroomMembership) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddClassroomMembershipIDs(ids...)
}

// AddAssignmentSubmissionIDs adds the "assignment_submissions" edge to the AssignmentSubmission entity by IDs.
func (_c *UserCreate) AddAssignmentSubmissionIDs(ids ...int) *UserCreate {
	_c.mutation.AddAssignmentSubmissionIDs(ids...)
	return _c
}

// AddAssignmentSubmissions adds the "assignment_submissions" edges to the AssignmentSubmission entity.
func (_c *UserCreate) AddAssignmentSubmissions(v ...*AssignmentSubmission) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAssignmentSubmissionIDs(ids...)
}

// AddUserProgresIDs adds the "user_progress" edge to the UserProgress entity by IDs.
func (_c *UserCreate) AddUserProgresIDs(ids ...int) *UserCreate {
	_c.mutation.AddUserProgresIDs(ids...)
	return _c
}

// AddUserProgress adds the "user_progress" edges to the UserProgress entity.
func (_c *UserCreate) AddUserProgress(v ...*UserProgress) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUserProgresIDs(ids...)
}

// AddAchievementIDs adds the "achievements" edge to the Achievement entity by IDs.
func (_c *UserCreate) AddAchievementIDs(ids ...int) *UserCreate {
	_c.mutation.AddAchievementIDs(ids...)
	return _c
}

// AddAchievements adds the "achievements" edges to the Achievement entity.
func (_c *UserCreate) AddAchievements(v ...*Achievement) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAchievementIDs(ids...)
}

// AddBattleRoomsHostedIDs adds the "battle_rooms_hosted" edge to the BattleRoom entity by IDs.
func (_c *UserCreate) AddBattleRoomsHostedIDs(ids ...int) *UserCreate {
	_c.mutation.AddBattleRoomsHostedIDs(ids...)
	return _c
}

// AddBattleRoomsHosted adds the "battle_rooms_hosted" edges to the BattleRoom entity.
func (_c *UserCreate) AddBattleRoomsHosted(v ...*BattleRoom) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBattleRoomsHostedIDs(ids...)
}

// AddBattleSessionIDs adds the "battle_sessions" edge to the BattleSession entity by IDs.
func (_c *UserCreate) AddBattleSessionIDs(ids ...int) *UserCreate {
	_c.mutation.AddBattleSessionIDs(ids...)
	return _c
}

// AddBattleSessions adds the "battle_sessions" edges to the BattleSession entity.
func (_c *UserCreate) AddBattleSessions(v ...*BattleSession) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBattleSessionIDs(ids...)
}

// AddLiveSessionsTeachingIDs adds the "live_sessions_teaching" edge to the LiveSession entity by IDs.
func (_c *UserCreate) AddLiveSessionsTeachingIDs(ids ...int) *UserCreate {
	_c.mutation.AddLiveSessionsTeachingIDs(ids...)
	return _c
}

// AddLiveSessionsTeaching adds the "live_sessions_teaching" edges to the LiveSession entity.
func (_c *UserCreate) AddLiveSessionsTeaching(v ...*LiveSession) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLiveSessionsTeachingIDs(ids...)
}

// AddLiveSessionParticipationIDs adds the "live_session_participations" edge to the LiveSessionStudent entity by IDs.
func (_c *UserCreate) AddLiveSessionParticipationIDs(ids ...int) *UserCreate {
	_c.mutation.AddLiveSessionParticipationIDs(ids...)
	return _c
}

// AddLiveSessionParticipations adds the "live_session_participations" edges to the LiveSessionStudent entity.
func (_c *UserCreate) AddLiveSessionParticipations(v ...*LiveSessionStudent) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLiveSessionParticipationIDs(ids...)
}

// AddClassroomSessionIDs adds the "classroom_sessions" edge to the ClassroomSession entity by IDs.
func (_c *UserCreate) AddClassroomSessionIDs(ids ...int) *UserCreate {
	_c.mutation.AddClassroomSessionIDs(ids...)
	return _c
}

// AddClassroomSessions adds the "classroom_sessions" edges to the ClassroomSession entity.
func (_c *UserCreate) AddClassroomSessions(v ...*ClassroomSession) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddClassroomSessionIDs(ids...)
}

// SetShenbiSettingsID sets the "shenbi_settings" edge to the ShenbiSettings entity by ID.
func (_c *UserCreate) SetShenbiSettingsID(id int) *UserCreate {
	_c.mutation.SetShenbiSettingsID(id)
	return _c
}

// SetNillableShenbiSettingsID sets the "shenbi_settings" edge to the ShenbiSettings entity by ID if the given value is not nil.
func (_c *UserCreate) SetNillableShenbiSettingsID(id *int) *UserCreate {
	if id != nil {
		_c = _c.SetShenbiSettingsID(*id)
	}
	return _c
}

// SetShenbiSettings sets the "shenbi_settings" edge to the ShenbiSettings entity.
func (_c *UserCreate) SetShenbiSettings(v *ShenbiSettings) *UserCreate {
	return _c.SetShenbiSettingsID(v.ID)
}

// AddSentInvitationIDs adds the "sent_invitations" edge to the OrganizationInvitation entity by IDs.
func (_c *UserCreate) AddSentInvitationIDs(ids ...int) *UserCreate {
	_c.mutation.AddSentInvitationIDs(ids...)
	return _c
}

// AddSentInvitations adds the "sent_invitations" edges to the OrganizationInvitation entity.
func (_c *UserCreate) AddSentInvitations(v ...*OrganizationInvitation) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSentInvitationIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_c *UserCreate) Mutation() *UserMutation {
	return _c.mutation
}

// Save creates the User in the database.
func (_c *UserCreate) Save(ctx context.Context) (*User, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserCreate) SaveX(ctx context.Context) *User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserCreate) defaults() {
	if _, ok := _c.mutation.IsActive(); !ok {
		v := user.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.IsVerified(); !ok {
		v := user.DefaultIsVerified
		_c.mutation.SetIsVerified(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := user.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := user.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserCreate) check() error {
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "User.email"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "User.is_active"`)}
	}
	if _, ok := _c.mutation.IsVerified(); !ok {
		return &ValidationError{Name: "is_verified", err: errors.New(`ent: missing required field "User.is_verified"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "User.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "User.updated_at"`)}
	}
	return nil
}

func (_c *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserCreate) createSpec() (*User, *sqlgraph.CreateSpec) {
	var (
		_node = &User{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(user.Table, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
		_node.PasswordHash = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.AvatarURL(); ok {
		_spec.SetField(user.FieldAvatarURL, field.TypeString, value)
		_node.AvatarURL = value
	}
	if value, ok := _c.mutation.DeviceID(); ok {
		_spec.SetField(user.FieldDeviceID, field.TypeString, value)
		_node.DeviceID = &value
	}
	if value, ok := _c.mutation.GoogleID(); ok {
		_spec.SetField(user.FieldGoogleID, field.TypeString, value)
		_node.GoogleID = &value
	}
	if value, ok := _c.mutation.AppleID(); ok {
		_spec.SetField(user.FieldAppleID, field.TypeString, value)
		_node.AppleID = &value
	}
	if value, ok := _c.mutation.GoogleAccessToken(); ok {
		_spec.SetField(user.FieldGoogleAccessToken, field.TypeString, value)
		_node.GoogleAccessToken = value
	}
	if value, ok := _c.mutation.GoogleRefreshToken(); ok {
		_spec.SetField(user.FieldGoogleRefreshToken, field.TypeString, value)
		_node.GoogleRefreshToken = value
	}
	if value, ok := _c.mutation.GoogleTokenExpiresAt(); ok {
		_spec.SetField(user.FieldGoogleTokenExpiresAt, field.TypeTime, value)
		_node.GoogleTokenExpiresAt = &value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(user.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.IsVerified(); ok {
		_spec.SetField(user.FieldIsVerified, field.TypeBool, value)
		_node.IsVerified = value
	}
	if value, ok := _c.mutation.ExtraData(); ok {
		_spec.SetField(user.FieldExtraData, field.TypeJSON, value)
		_node.ExtraData = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.LastLoginAt(); ok {
		_spec.SetField(user.FieldLastLoginAt, field.TypeTime, value)
		_node.LastLoginAt = &value
	}
	if nodes := _c.mutation.UserAppsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserAppsTable,
			Columns: []string{user.UserAppsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userapp.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OrganizationMembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.OrganizationMembershipsTable,
			Columns: []string{user.OrganizationMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationmember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SubscriptionsTable,
			Columns: []string{user.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ShenbiProfileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.ShenbiProfileTable,
			Columns: []string{user.ShenbiProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shenbiprofile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ClassroomsTeachingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ClassroomsTeachingTable,
			Columns: []string{user.ClassroomsTeachingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(classroom.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ClassroomMembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ClassroomMembershipsTable,
			Columns: []string{user.ClassroomMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(classroommembership.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AssignmentSubmissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AssignmentSubmissionsTable,
			Columns: []string{user.AssignmentSubmissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assignmentsubmission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserProgressIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserProgressTable,
			Columns: []string{user.UserProgressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userprogress.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AchievementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AchievementsTable,
			Columns: []string{user.AchievementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(achievement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BattleRoomsHostedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BattleRoomsHostedTable,
			Columns: []string{user.BattleRoomsHostedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(battleroom.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BattleSessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BattleSessionsTable,
			Columns: []string{user.BattleSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(battlesession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LiveSessionsTeachingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.LiveSessionsTeachingTable,
			Columns: []string{user.LiveSessionsTeachingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(livesession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LiveSessionParticipationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.LiveSessionParticipationsTable,
			Columns: []string{user.LiveSessionParticipationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(livesessionstudent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ClassroomSessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ClassroomSessionsTable,
			Columns: []string{user.ClassroomSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(classroomsession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ShenbiSettingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.ShenbiSettingsTable,
			Columns: []string{user.ShenbiSettingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shenbisettings.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SentInvitationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SentInvitationsTable,
			Columns: []string{user.SentInvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationinvitation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserCreateBulk is the builder for creating many User entities in bulk.
type UserCreateBulk struct {
	config
	err      error
	builders []*UserCreate
}

// Save creates the User entities in the database.
func (_c *UserCreateBulk) Save(ctx context.Context) ([]*User, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*User, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserCreateBulk) SaveX(ctx context.Context) []*User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
