// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"gigaboo.io/lem/internal/ent/shenbiprofile"
	"gigaboo.io/lem/internal/ent/shenbisettings"
	"gigaboo.io/lem/internal/ent/user"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// PasswordHash holds the value of the "password_hash" field.
	PasswordHash string `json:"password_hash,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// AvatarURL holds the value of the "avatar_url" field.
	AvatarURL string `json:"avatar_url,omitempty"`
	// DeviceID holds the value of the "device_id" field.
	DeviceID *string `json:"device_id,omitempty"`
	// GoogleID holds the value of the "google_id" field.
	GoogleID *string `json:"google_id,omitempty"`
	// AppleID holds the value of the "apple_id" field.
	AppleID *string `json:"apple_id,omitempty"`
	// GoogleAccessToken holds the value of the "google_access_token" field.
	GoogleAccessToken string `json:"-"`
	// GoogleRefreshToken holds the value of the "google_refresh_token" field.
	GoogleRefreshToken string `json:"-"`
	// GoogleTokenExpiresAt holds the value of the "google_token_expires_at" field.
	GoogleTokenExpiresAt *time.Time `json:"google_token_expires_at,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// IsVerified holds the value of the "is_verified" field.
	IsVerified bool `json:"is_verified,omitempty"`
	// ExtraData holds the value of the "extra_data" field.
	ExtraData map[string]interface{} `json:"extra_data,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// LastLoginAt holds the value of the "last_login_at" field.
	LastLoginAt *time.Time `json:"last_login_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// UserApps holds the value of the user_apps edge.
	UserApps []*UserApp `json:"user_apps,omitempty"`
	// OrganizationMemberships holds the value of the organization_memberships edge.
	OrganizationMemberships []*OrganizationMember `json:"organization_memberships,omitempty"`
	// Subscriptions holds the value of the subscriptions edge.
	Subscriptions []*Subscription `json:"subscriptions,omitempty"`
	// ShenbiProfile holds the value of the shenbi_profile edge.
	ShenbiProfile *ShenbiProfile `json:"shenbi_profile,omitempty"`
	// ClassroomsTeaching holds the value of the classrooms_teaching edge.
	ClassroomsTeaching []*Classroom `json:"classrooms_teaching,omitempty"`
	// ClassroomMemberships holds the value of the classroom_memberships edge.
	ClassroomMemberships []*ClassroomMembership `json:"classroom_memberships,omitempty"`
	// AssignmentSubmissions holds the value of the assignment_submissions edge.
	AssignmentSubmissions []*AssignmentSubmission `json:"assignment_submissions,omitempty"`
	// UserProgress holds the value of the user_progress edge.
	UserProgress []*UserProgress `json:"user_progress,omitempty"`
	// Achievements holds the value of the achievements edge.
	Achievements []*Achievement `json:"achievements,omitempty"`
	// BattleRoomsHosted holds the value of the battle_rooms_hosted edge.
	BattleRoomsHosted []*BattleRoom `json:"battle_rooms_hosted,omitempty"`
	// BattleSessions holds the value of the battle_sessions edge.
	BattleSessions []*BattleSession `json:"battle_sessions,omitempty"`
	// LiveSessionsTeaching holds the value of the live_sessions_teaching edge.
	LiveSessionsTeaching []*LiveSession `json:"live_sessions_teaching,omitempty"`
	// LiveSessionParticipations holds the value of the live_session_participations edge.
	LiveSessionParticipations []*LiveSessionStudent `json:"live_session_participations,omitempty"`
	// ClassroomSessions holds the value of the classroom_sessions edge.
	ClassroomSessions []*ClassroomSession `json:"classroom_sessions,omitempty"`
	// ShenbiSettings holds the value of the shenbi_settings edge.
	ShenbiSettings *ShenbiSettings `json:"shenbi_settings,omitempty"`
	// SentInvitations holds the value of the sent_invitations edge.
	SentInvitations []*OrganizationInvitation `json:"sent_invitations,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [16]bool
}

// UserAppsOrErr returns the UserApps value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) UserAppsOrErr() ([]*UserApp, error) {
	if e.loadedTypes[0] {
		return e.UserApps, nil
	}
	return nil, &NotLoadedError{edge: "user_apps"}
}

// OrganizationMembershipsOrErr returns the OrganizationMemberships value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) OrganizationMembershipsOrErr() ([]*OrganizationMember, error) {
	if e.loadedTypes[1] {
		return e.OrganizationMemberships, nil
	}
	return nil, &NotLoadedError{edge: "organization_memberships"}
}

// SubscriptionsOrErr returns the Subscriptions value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) SubscriptionsOrErr() ([]*Subscription, error) {
	if e.loadedTypes[2] {
		return e.Subscriptions, nil
	}
	return nil, &NotLoadedError{edge: "subscriptions"}
}

// ShenbiProfileOrErr returns the ShenbiProfile value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserEdges) ShenbiProfileOrErr() (*ShenbiProfile, error) {
	if e.ShenbiProfile != nil {
		return e.ShenbiProfile, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: shenbiprofile.Label}
	}
	return nil, &NotLoadedError{edge: "shenbi_profile"}
}

// ClassroomsTeachingOrErr returns the ClassroomsTeaching value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ClassroomsTeachingOrErr() ([]*Classroom, error) {
	if e.loadedTypes[4] {
		return e.ClassroomsTeaching, nil
	}
	return nil, &NotLoadedError{edge: "classrooms_teaching"}
}

// ClassroomMembershipsOrErr returns the ClassroomMemberships value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ClassroomMembershipsOrErr() ([]*ClassroomMembership, error) {
	if e.loadedTypes[5] {
		return e.ClassroomMemberships, nil
	}
	return nil, &NotLoadedError{edge: "classroom_memberships"}
}

// AssignmentSubmissionsOrErr returns the AssignmentSubmissions value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) AssignmentSubmissionsOrErr() ([]*AssignmentSubmission, error) {
	if e.loadedTypes[6] {
		return e.AssignmentSubmissions, nil
	}
	return nil, &NotLoadedError{edge: "assignment_submissions"}
}

// UserProgressOrErr returns the UserProgress value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) UserProgressOrErr() ([]*UserProgress, error) {
	if e.loadedTypes[7] {
		return e.UserProgress, nil
	}
	return nil, &NotLoadedError{edge: "user_progress"}
}

// AchievementsOrErr returns the Achievements value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) AchievementsOrErr() ([]*Achievement, error) {
	if e.loadedTypes[8] {
		return e.Achievements, nil
	}
	return nil, &NotLoadedError{edge: "achievements"}
}

// BattleRoomsHostedOrErr returns the BattleRoomsHosted value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) BattleRoomsHostedOrErr() ([]*BattleRoom, error) {
	if e.loadedTypes[9] {
		return e.BattleRoomsHosted, nil
	}
	return nil, &NotLoadedError{edge: "battle_rooms_hosted"}
}

// BattleSessionsOrErr returns the BattleSessions value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) BattleSessionsOrErr() ([]*BattleSession, error) {
	if e.loadedTypes[10] {
		return e.BattleSessions, nil
	}
	return nil, &NotLoadedError{edge: "battle_sessions"}
}

// LiveSessionsTeachingOrErr returns the LiveSessionsTeaching value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) LiveSessionsTeachingOrErr() ([]*LiveSession, error) {
	if e.loadedTypes[11] {
		return e.LiveSessionsTeaching, nil
	}
	return nil, &NotLoadedError{edge: "live_sessions_teaching"}
}

// LiveSessionParticipationsOrErr returns the LiveSessionParticipations value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) LiveSessionParticipationsOrErr() ([]*LiveSessionStudent, error) {
	if e.loadedTypes[12] {
		return e.LiveSessionParticipations, nil
	}
	return nil, &NotLoadedError{edge: "live_session_participations"}
}

// ClassroomSessionsOrErr returns the ClassroomSessions value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ClassroomSessionsOrErr() ([]*ClassroomSession, error) {
	if e.loadedTypes[13] {
		return e.ClassroomSessions, nil
	}
	return nil, &NotLoadedError{edge: "classroom_sessions"}
}

// ShenbiSettingsOrErr returns the ShenbiSettings value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserEdges) ShenbiSettingsOrErr() (*ShenbiSettings, error) {
	if e.ShenbiSettings != nil {
		return e.ShenbiSettings, nil
	} else if e.loadedTypes[14] {
		return nil, &NotFoundError{label: shenbisettings.Label}
	}
	return nil, &NotLoadedError{edge: "shenbi_settings"}
}

// SentInvitationsOrErr returns the SentInvitations value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) SentInvitationsOrErr() ([]*OrganizationInvitation, error) {
	if e.loadedTypes[15] {
		return e.SentInvitations, nil
	}
	return nil, &NotLoadedError{edge: "sent_invitations"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldExtraData:
			values[i] = new([]byte)
		case user.FieldIsActive, user.FieldIsVerified:
			values[i] = new(sql.NullBool)
		case user.FieldID:
			values[i] = new(sql.NullInt64)
		case user.FieldEmail, user.FieldPasswordHash, user.FieldName, user.FieldAvatarURL, user.FieldDeviceID, user.FieldGoogleID, user.FieldAppleID, user.FieldGoogleAccessToken, user.FieldGoogleRefreshToken:
			values[i] = new(sql.NullString)
		case user.FieldGoogleTokenExpiresAt, user.FieldCreatedAt, user.FieldUpdatedAt, user.FieldLastLoginAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case user.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case user.FieldPasswordHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password_hash", values[i])
			} else if value.Valid {
				_m.PasswordHash = value.String
			}
		case user.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case user.FieldAvatarURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field avatar_url", values[i])
			} else if value.Valid {
				_m.AvatarURL = value.String
			}
		case user.FieldDeviceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field device_id", values[i])
			} else if value.Valid {
				_m.DeviceID = new(string)
				*_m.DeviceID = value.String
			}
		case user.FieldGoogleID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field google_id", values[i])
			} else if value.Valid {
				_m.GoogleID = new(string)
				*_m.GoogleID = value.String
			}
		case user.FieldAppleID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field apple_id", values[i])
			} else if value.Valid {
				_m.AppleID = new(string)
				*_m.AppleID = value.String
			}
		case user.FieldGoogleAccessToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field google_access_token", values[i])
			} else if value.Valid {
				_m.GoogleAccessToken = value.String
			}
		case user.FieldGoogleRefreshToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field google_refresh_token", values[i])
			} else if value.Valid {
				_m.GoogleRefreshToken = value.String
			}
		case user.FieldGoogleTokenExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field google_token_expires_at", values[i])
			} else if value.Valid {
				_m.GoogleTokenExpiresAt = new(time.Time)
				*_m.GoogleTokenExpiresAt = value.Time
			}
		case user.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case user.FieldIsVerified:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_verified", values[i])
			} else if value.Valid {
				_m.IsVerified = value.Bool
			}
		case user.FieldExtraData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field extra_data", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ExtraData); err != nil {
					return fmt.Errorf("unmarshal field extra_data: %w", err)
				}
			}
		case user.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case user.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case user.FieldLastLoginAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_login_at", values[i])
			} else if value.Valid {
				_m.LastLoginAt = new(time.Time)
				*_m.LastLoginAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUserApps queries the "user_apps" edge of the User entity.
func (_m *User) QueryUserApps() *UserAppQuery {
	return NewUserClient(_m.config).QueryUserApps(_m)
}

// QueryOrganizationMemberships queries the "organization_memberships" edge of the User entity.
func (_m *User) QueryOrganizationMemberships() *OrganizationMemberQuery {
	return NewUserClient(_m.config).QueryOrganizationMemberships(_m)
}

// QuerySubscriptions queries the "subscriptions" edge of the User entity.
func (_m *User) QuerySubscriptions() *SubscriptionQuery {
	return NewUserClient(_m.config).QuerySubscriptions(_m)
}

// QueryShenbiProfile queries the "shenbi_profile" edge of the User entity.
func (_m *User) QueryShenbiProfile() *ShenbiProfileQuery {
	return NewUserClient(_m.config).QueryShenbiProfile(_m)
}

// QueryClassroomsTeaching queries the "classrooms_teaching" edge of the User entity.
func (_m *User) QueryClassroomsTeaching() *ClassroomQuery {
	return NewUserClient(_m.config).QueryClassroomsTeaching(_m)
}

// QueryClassroomMemberships queries the "classroom_memberships" edge of the User entity.
func (_m *User) QueryClassroomMemberships() *ClassroomMembershipQuery {
	return NewUserClient(_m.config).QueryClassroomMemberships(_m)
}

// QueryAssignmentSubmissions queries the "assignment_submissions" edge of the User entity.
func (_m *User) QueryAssignmentSubmissions() *AssignmentSubmissionQuery {
	return NewUserClient(_m.config).QueryAssignmentSubmissions(_m)
}

// QueryUserProgress queries the "user_progress" edge of the User entity.
func (_m *User) QueryUserProgress() *UserProgressQuery {
	return NewUserClient(_m.config).QueryUserProgress(_m)
}

// QueryAchievements queries the "achievements" edge of the User entity.
func (_m *User) QueryAchievements() *AchievementQuery {
	return NewUserClient(_m.config).QueryAchievements(_m)
}

// QueryBattleRoomsHosted queries the "battle_rooms_hosted" edge of the User entity.
func (_m *User) QueryBattleRoomsHosted() *BattleRoomQuery {
	return NewUserClient(_m.config).QueryBattleRoomsHosted(_m)
}

// QueryBattleSessions queries the "battle_sessions" edge of the User entity.
func (_m *User) QueryBattleSessions() *BattleSessionQuery {
	return NewUserClient(_m.config).QueryBattleSessions(_m)
}

// QueryLiveSessionsTeaching queries the "live_sessions_teaching" edge of the User entity.
func (_m *User) QueryLiveSessionsTeaching() *LiveSessionQuery {
	return NewUserClient(_m.config).QueryLiveSessionsTeaching(_m)
}

// QueryLiveSessionParticipations queries the "live_session_participations" edge of the User entity.
func (_m *User) QueryLiveSessionParticipations() *LiveSessionStudentQuery {
	return NewUserClient(_m.config).QueryLiveSessionParticipations(_m)
}

// QueryClassroomSessions queries the "classroom_sessions" edge of the User entity.
func (_m *User) QueryClassroomSessions() *ClassroomSessionQuery {
	return NewUserClient(_m.config).QueryClassroomSessions(_m)
}

// QueryShenbiSettings queries the "shenbi_settings" edge of the User entity.
func (_m *User) QueryShenbiSettings() *ShenbiSettingsQuery {
	return NewUserClient(_m.config).QueryShenbiSettings(_m)
}

// QuerySentInvitations queries the "sent_invitations" edge of the User entity.
func (_m *User) QuerySentInvitations() *OrganizationInvitationQuery {
	return NewUserClient(_m.config).QuerySentInvitations(_m)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("password_hash=")
	builder.WriteString(_m.PasswordHash)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("avatar_url=")
	builder.WriteString(_m.AvatarURL)
	builder.WriteString(", ")
	if v := _m.DeviceID; v != nil {
		builder.WriteString("device_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.GoogleID; v != nil {
		builder.WriteString("google_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AppleID; v != nil {
		builder.WriteString("apple_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("google_access_token=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("google_refresh_token=<sensitive>")
	builder.WriteString(", ")
	if v := _m.GoogleTokenExpiresAt; v != nil {
		builder.WriteString("google_token_expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("is_verified=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsVerified))
	builder.WriteString(", ")
	builder.WriteString("extra_data=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExtraData))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.LastLoginAt; v != nil {
		builder.WriteString("last_login_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
