// Code generated by ent, DO NOT EDIT.

package classroom

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"gigaboo.io/lem/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Classroom {
	return predicate.Classroom(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Classroom {
	return predicate.Classroom(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Classroom {
	return predicate.Classroom(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Classroom {
	return predicate.Classroom(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Classroom {
	return predicate.Classroom(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Classroom {
	return predicate.Classroom(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Classroom {
	return predicate.Classroom(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Classroom {
	return predicate.Classroom(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Classroom {
	return predicate.Classroom(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldEQ(FieldDescription, v))
}

// JoinCode applies equality check predicate on the "join_code" field. It's identical to JoinCodeEQ.
func JoinCode(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldEQ(FieldJoinCode, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.Classroom {
	return predicate.Classroom(sql.FieldEQ(FieldIsActive, v))
}

// AllowJoin applies equality check predicate on the "allow_join" field. It's identical to AllowJoinEQ.
func AllowJoin(v bool) predicate.Classroom {
	return predicate.Classroom(sql.FieldEQ(FieldAllowJoin, v))
}

// ActiveRoomCode applies equality check predicate on the "active_room_code" field. It's identical to ActiveRoomCodeEQ.
func ActiveRoomCode(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldEQ(FieldActiveRoomCode, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Classroom {
	return predicate.Classroom(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Classroom {
	return predicate.Classroom(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Classroom {
	return predicate.Classroom(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Classroom {
	return predicate.Classroom(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Classroom {
	return predicate.Classroom(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Classroom {
	return predicate.Classroom(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Classroom {
	return predicate.Classroom(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Classroom {
	return predicate.Classroom(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldContainsFold(FieldDescription, v))
}

// JoinCodeEQ applies the EQ predicate on the "join_code" field.
func JoinCodeEQ(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldEQ(FieldJoinCode, v))
}

// JoinCodeNEQ applies the NEQ predicate on the "join_code" field.
func JoinCodeNEQ(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldNEQ(FieldJoinCode, v))
}

// JoinCodeIn applies the In predicate on the "join_code" field.
func JoinCodeIn(vs ...string) predicate.Classroom {
	return predicate.Classroom(sql.FieldIn(FieldJoinCode, vs...))
}

// JoinCodeNotIn applies the NotIn predicate on the "join_code" field.
func JoinCodeNotIn(vs ...string) predicate.Classroom {
	return predicate.Classroom(sql.FieldNotIn(FieldJoinCode, vs...))
}

// JoinCodeGT applies the GT predicate on the "join_code" field.
func JoinCodeGT(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldGT(FieldJoinCode, v))
}

// JoinCodeGTE applies the GTE predicate on the "join_code" field.
func JoinCodeGTE(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldGTE(FieldJoinCode, v))
}

// JoinCodeLT applies the LT predicate on the "join_code" field.
func JoinCodeLT(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldLT(FieldJoinCode, v))
}

// JoinCodeLTE applies the LTE predicate on the "join_code" field.
func JoinCodeLTE(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldLTE(FieldJoinCode, v))
}

// JoinCodeContains applies the Contains predicate on the "join_code" field.
func JoinCodeContains(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldContains(FieldJoinCode, v))
}

// JoinCodeHasPrefix applies the HasPrefix predicate on the "join_code" field.
func JoinCodeHasPrefix(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldHasPrefix(FieldJoinCode, v))
}

// JoinCodeHasSuffix applies the HasSuffix predicate on the "join_code" field.
func JoinCodeHasSuffix(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldHasSuffix(FieldJoinCode, v))
}

// JoinCodeEqualFold applies the EqualFold predicate on the "join_code" field.
func JoinCodeEqualFold(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldEqualFold(FieldJoinCode, v))
}

// JoinCodeContainsFold applies the ContainsFold predicate on the "join_code" field.
func JoinCodeContainsFold(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldContainsFold(FieldJoinCode, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.Classroom {
	return predicate.Classroom(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.Classroom {
	return predicate.Classroom(sql.FieldNEQ(FieldIsActive, v))
}

// AllowJoinEQ applies the EQ predicate on the "allow_join" field.
func AllowJoinEQ(v bool) predicate.Classroom {
	return predicate.Classroom(sql.FieldEQ(FieldAllowJoin, v))
}

// AllowJoinNEQ applies the NEQ predicate on the "allow_join" field.
func AllowJoinNEQ(v bool) predicate.Classroom {
	return predicate.Classroom(sql.FieldNEQ(FieldAllowJoin, v))
}

// ActiveRoomCodeEQ applies the EQ predicate on the "active_room_code" field.
func ActiveRoomCodeEQ(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldEQ(FieldActiveRoomCode, v))
}

// ActiveRoomCodeNEQ applies the NEQ predicate on the "active_room_code" field.
func ActiveRoomCodeNEQ(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldNEQ(FieldActiveRoomCode, v))
}

// ActiveRoomCodeIn applies the In predicate on the "active_room_code" field.
func ActiveRoomCodeIn(vs ...string) predicate.Classroom {
	return predicate.Classroom(sql.FieldIn(FieldActiveRoomCode, vs...))
}

// ActiveRoomCodeNotIn applies the NotIn predicate on the "active_room_code" field.
func ActiveRoomCodeNotIn(vs ...string) predicate.Classroom {
	return predicate.Classroom(sql.FieldNotIn(FieldActiveRoomCode, vs...))
}

// ActiveRoomCodeGT applies the GT predicate on the "active_room_code" field.
func ActiveRoomCodeGT(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldGT(FieldActiveRoomCode, v))
}

// ActiveRoomCodeGTE applies the GTE predicate on the "active_room_code" field.
func ActiveRoomCodeGTE(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldGTE(FieldActiveRoomCode, v))
}

// ActiveRoomCodeLT applies the LT predicate on the "active_room_code" field.
func ActiveRoomCodeLT(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldLT(FieldActiveRoomCode, v))
}

// ActiveRoomCodeLTE applies the LTE predicate on the "active_room_code" field.
func ActiveRoomCodeLTE(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldLTE(FieldActiveRoomCode, v))
}

// ActiveRoomCodeContains applies the Contains predicate on the "active_room_code" field.
func ActiveRoomCodeContains(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldContains(FieldActiveRoomCode, v))
}

// ActiveRoomCodeHasPrefix applies the HasPrefix predicate on the "active_room_code" field.
func ActiveRoomCodeHasPrefix(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldHasPrefix(FieldActiveRoomCode, v))
}

// ActiveRoomCodeHasSuffix applies the HasSuffix predicate on the "active_room_code" field.
func ActiveRoomCodeHasSuffix(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldHasSuffix(FieldActiveRoomCode, v))
}

// ActiveRoomCodeIsNil applies the IsNil predicate on the "active_room_code" field.
func ActiveRoomCodeIsNil() predicate.Classroom {
	return predicate.Classroom(sql.FieldIsNull(FieldActiveRoomCode))
}

// ActiveRoomCodeNotNil applies the NotNil predicate on the "active_room_code" field.
func ActiveRoomCodeNotNil() predicate.Classroom {
	return predicate.Classroom(sql.FieldNotNull(FieldActiveRoomCode))
}

// ActiveRoomCodeEqualFold applies the EqualFold predicate on the "active_room_code" field.
func ActiveRoomCodeEqualFold(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldEqualFold(FieldActiveRoomCode, v))
}

// ActiveRoomCodeContainsFold applies the ContainsFold predicate on the "active_room_code" field.
func ActiveRoomCodeContainsFold(v string) predicate.Classroom {
	return predicate.Classroom(sql.FieldContainsFold(FieldActiveRoomCode, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Classroom {
	return predicate.Classroom(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Classroom {
	return predicate.Classroom(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Classroom {
	return predicate.Classroom(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Classroom {
	return predicate.Classroom(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Classroom {
	return predicate.Classroom(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Classroom {
	return predicate.Classroom(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Classroom {
	return predicate.Classroom(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Classroom {
	return predicate.Classroom(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Classroom {
	return predicate.Classroom(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Classroom {
	return predicate.Classroom(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Classroom {
	return predicate.Classroom(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Classroom {
	return predicate.Classroom(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Classroom {
	return predicate.Classroom(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Classroom {
	return predicate.Classroom(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Classroom {
	return predicate.Classroom(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Classroom {
	return predicate.Classroom(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasApp applies the HasEdge predicate on the "app" edge.
func HasApp() predicate.Classroom {
	return predicate.Classroom(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AppTable, AppColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAppWith applies the HasEdge predicate on the "app" edge with a given conditions (other predicates).
func HasAppWith(preds ...predicate.App) predicate.Classroom {
	return predicate.Classroom(func(s *sql.Selector) {
		step := newAppStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTeacher applies the HasEdge predicate on the "teacher" edge.
func HasTeacher() predicate.Classroom {
	return predicate.Classroom(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TeacherTable, TeacherColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeacherWith applies the HasEdge predicate on the "teacher" edge with a given conditions (other predicates).
func HasTeacherWith(preds ...predicate.User) predicate.Classroom {
	return predicate.Classroom(func(s *sql.Selector) {
		step := newTeacherStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMemberships applies the HasEdge predicate on the "memberships" edge.
func HasMemberships() predicate.Classroom {
	return predicate.Classroom(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MembershipsTable, MembershipsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMembershipsWith applies the HasEdge predicate on the "memberships" edge with a given conditions (other predicates).
func HasMembershipsWith(preds ...predicate.ClassroomMembership) predicate.Classroom {
	return predicate.Classroom(func(s *sql.Selector) {
		step := newMembershipsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAssignments applies the HasEdge predicate on the "assignments" edge.
func HasAssignments() predicate.Classroom {
	return predicate.Classroom(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AssignmentsTable, AssignmentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssignmentsWith applies the HasEdge predicate on the "assignments" edge with a given conditions (other predicates).
func HasAssignmentsWith(preds ...predicate.Assignment) predicate.Classroom {
	return predicate.Classroom(func(s *sql.Selector) {
		step := newAssignmentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLiveSessions applies the HasEdge predicate on the "live_sessions" edge.
func HasLiveSessions() predicate.Classroom {
	return predicate.Classroom(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, LiveSessionsTable, LiveSessionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLiveSessionsWith applies the HasEdge predicate on the "live_sessions" edge with a given conditions (other predicates).
func HasLiveSessionsWith(preds ...predicate.LiveSession) predicate.Classroom {
	return predicate.Classroom(func(s *sql.Selector) {
		step := newLiveSessionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasClassroomSessions applies the HasEdge predicate on the "classroom_sessions" edge.
func HasClassroomSessions() predicate.Classroom {
	return predicate.Classroom(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ClassroomSessionsTable, ClassroomSessionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasClassroomSessionsWith applies the HasEdge predicate on the "classroom_sessions" edge with a given conditions (other predicates).
func HasClassroomSessionsWith(preds ...predicate.ClassroomSession) predicate.Classroom {
	return predicate.Classroom(func(s *sql.Selector) {
		step := newClassroomSessionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Classroom) predicate.Classroom {
	return predicate.Classroom(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Classroom) predicate.Classroom {
	return predicate.Classroom(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Classroom) predicate.Classroom {
	return predicate.Classroom(sql.NotPredicates(p))
}
